%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais8-"1"
    e8-"2"
    dis4-"3"
    g1-"4"
    dis4-"5"
    gis4-"6"
    ais16-"7"
    fis16-"8"
    g2\f-"9"
    c4-"10"
    d2\mf-"11"
    e4-"12"
    a1-"13"
    c1-"14"
    d1-"15"
    c1-"16"
    cis8-"17"
    gis16-"18"
    dis4\mp-"19"
    e1-"20"
    e8\ff-"21"
    dis2\ff-"22"
    d4-"23"
    f4\mf-"24"
    d8-"25"
    d16-"26"
    fis8\pp-"27"
    f1-"28"
    e1-"29"
    d4-"30"
    fis16-"31"
    cis8\p-"32"
    e1-"33"
    a4-"34"
    c8-"35"
    dis8-"36"
    gis16-"37"
    e1-"38"
    g1-"39"
    e4-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"1"
    cis2\ff-"2"
    a16-"3"
    c4\p-"4"
    cis16-"5"
    d8-"6"
    c16-"7"
    cis8-"8"
    e8\ff-"9"
    dis16-"10"
    gis16-"11"
    g8\mf-"12"
    gis8-"13"
    e1-"14"
    ais1-"15"
    d2-"16"
    e16-"17"
    f16-"18"
    cis8-"19"
    g2\pp-"20"
    g4-"21"
    a16-"22"
    gis8\mp-"23"
    e1-"24"
    g16-"25"
    ais8-"26"
    cis1\mp-"27"
    ais1-"28"
    c4-"29"
    g2-"30"
    d1-"31"
    c8\mp-"32"
    d8-"33"
    g16-"34"
    b16-"35"
    ais16-"36"
    e2-"37"
    c1-"38"
    gis1-"39"
    gis4-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"1"
    a2-"2"
    fis1\ff-"3"
    gis8-"4"
    dis2-"5"
    cis4-"6"
    c16-"7"
    a2-"8"
    fis16-"9"
    e2-"10"
    dis1-"11"
    a4-"12"
    d4-"13"
    f8\p-"14"
    b4-"15"
    g1\p-"16"
    cis2-"17"
    c16\pp-"18"
    a16-"19"
    f8\f-"20"
    cis1-"21"
    g16-"22"
    d16-"23"
    c8-"24"
    fis1-"25"
    fis4\pp-"26"
    dis2-"27"
    ais16-"28"
    f8-"29"
    d16-"30"
    dis8-"31"
    e1-"32"
    c8-"33"
    cis2-"34"
    dis4-"35"
    d1\mp-"36"
    g1-"37"
    gis16-"38"
    fis16-"39"
    fis1\p-"40"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
