%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g8\mf-"1"
    ais2-"3"
    gis8-"6"
    c2-"4"
    gis8-"6"
    dis8-"9"
    b4-"2"
    ais2-"5"
    f4-"8"
    ais2-"3"
    gis8-"6"
    ais2-"5"
    f4-"12"
    dis8-"9"
    f4-"8"
    gis8-"6"
    c2-"4"
    c2-"4"
    c2-"4"
    c2-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b2-"1"
    b1-"3"
    c4-"6"
    g1-"4"
    c4-"6"
    c8-"9"
    g8\p-"2"
    b1-"5"
    cis8-"8"
    b1-"3"
    c4-"6"
    b1-"5"
    cis8-"12"
    c8-"9"
    cis8-"8"
    c4-"6"
    g1-"4"
    g1-"4"
    g1-"4"
    g1-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis16-"1"
    c4\p-"3"
    ais8-"6"
    d2-"4"
    ais8-"6"
    a4-"9"
    cis16-"2"
    c4\p-"5"
    ais2-"8"
    c4\p-"3"
    ais8-"6"
    c4\p-"5"
    ais2-"12"
    a4-"9"
    ais2-"8"
    ais8-"6"
    d2-"4"
    d2-"4"
    d2-"4"
    d2-"4"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
