%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   e'!2-"R7"
   fis'!2
   d'!4
   b'!2
   gis'!2.
   a'!4
   c'!2
   ais'!2
   dis'!2.
   cis'!2
   f'!4-"P5"
   dis'!2
   b'!4-"I11"
   cis'!4
   f'!4
   dis'!4
   gis'!4
   fis'!2.
   a'!2
   ais'!2
   g'!2.
   e'!2
   c'!2.
   d'!2-"RI11"
   c'!2
   e'!2
   g'!2.
   ais'!2.
   a'!4-"I9"
   b'!4
   dis'!2
   cis'!2.
   fis'!2-"I6"
   gis'!2
   c'!4
   ais'!4
   dis'!2.-"RI0"
   cis'!4
   f'!2.-"P5"
   dis'!2.
   b'!2.
   cis'!4
   gis'!4
   ais'!2-"I10"
   c'!4
   e'!2
   d'!2.
   g'!4
   f'!2.
   gis'!4
   a'!2.
   fis'!2.
   dis'!2
   b'!2.-"I11"
   cis'!2.
   f'!2.
   dis'!4
   gis'!4
   fis'!2-"R9"
   gis'!2
   e'!2
   cis'!2.-"R4"
   dis'!2
   b'!2.
   gis'!2.
   f'!2.
   fis'!2.
   a'!4
   g'!2
   c'!2
   ais'!2
   d'!2-"RI11"
   c'!4
   e'!2.
   g'!4
   ais'!2
   a'!2
   fis'!2
   gis'!2
   dis'!4
   f'!4-"R8"
   g'!2.
   dis'!2.
   c'!2
   a'!4
   ais'!2.
   cis'!2.-"I1"
   dis'!2
   g'!4
   f'!2
   ais'!4
   gis'!2
   b'!2.-"R2"
   cis'!2
   a'!2-"I9"
   b'!2
   dis'!4
   cis'!2-"I1"
   dis'!2.
   g'!2
   f'!2.
   ais'!2.
   gis'!4
   b'!2-"RI8"
   a'!2
   cis'!2.
   e'!4
   g'!2
   fis'!2
   dis'!2.
   f'!4
   c'!4
   d'!2-"RI11"
   c'!4
   e'!4
   g'!4
   ais'!2
   a'!2
   fis'!2
   gis'!2
   dis'!2
   f'!4
   cis'!2.-"P1"
   b'!4
   g'!2-"P7"
   f'!2
   cis'!4
   dis'!2
   ais'!2.
   c'!2
   a'!2
   gis'!2
   b'!2.-"I11"
   cis'!2.
   f'!2
   dis'!4
   gis'!4-"P8"
   fis'!4
   d'!4-"RI11"
   c'!2.
   e'!2.
   g'!2.
   ais'!2
   a'!4
   fis'!2.
   gis'!2
   dis'!2.
   f'!2.
   cis'!2
   b'!2-"I11"
   cis'!2
   f'!2
   dis'!2
   gis'!2-"R11"
   ais'!2
   fis'!2
   dis'!2.
   c'!2
   cis'!2.
   e'!2
   d'!2
   g'!2.
   f'!2-"RI2"
   dis'!2
   g'!4
   ais'!2
   cis'!2.
   c'!2
   a'!2
   b'!4
   fis'!4-"I6"
   gis'!2.
   c'!2.
   ais'!4
   dis'!2
   cis'!2
   e'!4
   f'!2.
   d'!4
   b'!4-"R2"
   cis'!2
   a'!4
   fis'!4
   dis'!2
   e'!2.
   g'!2
   f'!2-"I5"
   g'!4
   b'!2.
   a'!4
   d'!2.-"RI11"
   c'!2.
   e'!2
   g'!4
   ais'!2
   a'!4
   fis'!2
   gis'!2
   dis'!4
   f'!2.-"P5"
   dis'!2.
   b'!2
   cis'!2.
   gis'!2.
   ais'!2
   g'!2
   fis'!2-"RI3"
   e'!2.
   gis'!4
   b'!2
   d'!4-"RI11"
   c'!4
   e'!2
   g'!2
   ais'!2
   a'!4
   fis'!2.
   gis'!2
   dis'!4-"RI0"
   cis'!4
   f'!2-"R8"
   g'!2.
   dis'!4
   c'!4
   a'!2.
   ais'!2.
   cis'!2
   b'!2.
   e'!4
   d'!4
   fis'!4-"I6"
   gis'!4
   c'!4
   ais'!2
   dis'!2
   cis'!2.
   e'!4
   f'!2.-"P5"
   dis'!4
   b'!2
   cis'!4
   gis'!4
   ais'!4
   g'!4
   fis'!2
   a'!2.
   c'!2
   e'!2
   d'!2-"RI11"
   c'!2
   e'!4
   g'!4
   ais'!4
   a'!2
   fis'!4
   gis'!2.
   dis'!2.
   f'!2
   cis'!2
   b'!2.-"R2"
   cis'!2.
   a'!2.
   fis'!4
   dis'!2
   e'!4
   g'!2.
   f'!2.
   ais'!2
   gis'!4
   c'!2.-"I0"
   d'!2.
   fis'!2
   e'!2.
   a'!2
   g'!2
   ais'!2.
   b'!2
   gis'!2.
   f'!2.
   cis'!4
   dis'!2
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
