%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   cis'!2.-"I1"
   c'!4
   g'!2-"I7"
   fis'!4-"P6"
   g'!4
   c'!2.
   e'!2
   cis'!2
   d'!4
   f'!2
   gis'!2.
   b'!4
   a'!2.-"R0"
   e'!2
   dis'!4
   f'!4
   d'!2
   b'!2.-"R2"
   fis'!4
   f'!4-"P5"
   fis'!2
   b'!4-"I11"
   ais'!2.
   f'!4-"P5"
   fis'!4
   b'!4
   dis'!4
   c'!4
   cis'!4-"RI10"
   fis'!4
   g'!4
   f'!2.
   gis'!2
   b'!2.
   d'!2
   dis'!4-"I3"
   d'!4
   a'!2
   f'!2.
   gis'!2.
   g'!2
   e'!2.
   cis'!4-"I1"
   c'!2.
   g'!4
   dis'!2
   fis'!4
   f'!4
   d'!4
   b'!2
   gis'!2-"RI5"
   cis'!4
   d'!2
   c'!2.
   dis'!2.
   fis'!4
   a'!2
   ais'!4
   g'!2
   b'!4
   e'!4-"R7"
   b'!2.
   ais'!2
   c'!2
   a'!2.
   fis'!2.
   dis'!4-"I3"
   d'!2
   a'!4
   f'!4
   gis'!2
   g'!4
   e'!4
   cis'!2
   ais'!2.-"RI7"
   dis'!2
   e'!2.
   d'!4
   f'!2
   gis'!2.
   b'!4
   c'!2.
   a'!4-"RI6"
   d'!2
   dis'!2.
   cis'!4
   e'!4
   g'!2.
   ais'!4
   b'!4-"R2"
   fis'!2
   f'!2-"P5"
   fis'!2
   b'!2
   dis'!2
   c'!4
   cis'!2-"P1"
   d'!2.
   g'!2.
   b'!2.
   gis'!2
   a'!2
   c'!2.
   dis'!2.-"RI0"
   gis'!2.
   a'!2.
   g'!2
   ais'!2.
   cis'!2
   e'!2
   f'!4-"R8"
   c'!2
   b'!2
   cis'!4
   ais'!4
   g'!2
   e'!2
   dis'!4
   fis'!2.
   d'!2.-"P2"
   dis'!2
   gis'!2
   c'!2.
   a'!4-"RI6"
   d'!4
   dis'!2
   cis'!2.-"P1"
   d'!2
   g'!2.
   b'!2.
   gis'!2
   a'!4
   c'!2
   dis'!2
   fis'!2
   e'!4
   f'!4
   ais'!2.-"RI7"
   dis'!4
   e'!2.
   d'!2
   f'!4
   gis'!2
   b'!2
   c'!2
   a'!4
   cis'!4
   fis'!2-"R9"
   cis'!2.
   c'!2
   d'!2.
   b'!4
   gis'!2
   f'!4
   e'!2.
   g'!4
   dis'!2.-"I3"
   d'!2.
   a'!2.
   f'!2
   gis'!4
   g'!2-"P7"
   gis'!2.
   cis'!2
   f'!4
   d'!2
   dis'!2-"RI0"
   gis'!2
   a'!4
   g'!2
   ais'!4
   cis'!2
   e'!2.
   f'!2.
   d'!2
   fis'!2
   b'!4
   c'!2.-"RI9"
   f'!2.
   fis'!2
   e'!2
   g'!2.
   ais'!2.
   cis'!4
   d'!2.
   b'!4
   dis'!4-"RI0"
   gis'!2
   a'!2.-"R0"
   e'!4-"P4"
   f'!2
   ais'!2
   d'!4-"I2"
   cis'!2.
   gis'!2.
   e'!4
   g'!2.
   fis'!2
   dis'!2
   c'!4
   a'!2.
   b'!2-"I11"
   ais'!2
   f'!4-"RI2"
   ais'!2.
   b'!2
   a'!4
   c'!2.
   dis'!2.
   fis'!2.
   g'!2.-"P7"
   gis'!2
   cis'!2.
   f'!4-"R8"
   c'!2.
   b'!2.
   cis'!4
   ais'!2
   g'!4
   e'!2
   dis'!2
   fis'!2.
   d'!2.
   a'!2.-"P9"
   ais'!2-"R1"
   f'!2.
   e'!2
   fis'!4-"P6"
   g'!2.
   c'!2
   e'!4
   cis'!2
   d'!2.-"RI11"
   g'!4
   gis'!2.
   fis'!2.
   a'!2.
   c'!2-"RI9"
   f'!2.
   fis'!2.
   e'!4
   g'!2
   ais'!2
   cis'!2.
   d'!4
   b'!2.
   dis'!2-"R6"
   ais'!2.
   a'!2
   b'!2.
   gis'!2.
   f'!4-"I5"
   e'!2
   b'!2.
   g'!4
   ais'!4
   a'!2
   fis'!4
   dis'!2
   c'!2.-"I0"
   b'!2.
   fis'!2
   d'!2.
   f'!2.
   e'!2
   cis'!2
   ais'!4
   g'!4
   a'!2
   gis'!2.
   dis'!2.
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
