%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   dis'!2.-"I3"
   ais'!2.
   a'!2.
   d'!2.
   c'!2
   fis'!2
   e'!2
   g'!4-"R9"
   b'!2
   e'!2
   cis'!2.
   f'!2.
   gis'!2.
   fis'!2.
   c'!4-"R2"
   e'!2
   a'!2.
   fis'!2.
   ais'!2.
   cis'!4
   b'!2
   f'!4-"P5"
   ais'!4-"RI8"
   fis'!2
   cis'!2.
   e'!2
   c'!2
   a'!2.
   b'!4
   f'!2
   g'!4
   d'!2.
   dis'!4
   gis'!2.-"P8"
   cis'!2.
   d'!2.
   a'!4
   b'!4
   f'!2.-"I5"
   c'!4
   b'!2
   e'!2.
   d'!4
   gis'!2
   fis'!4
   a'!2
   cis'!4-"I1"
   gis'!2.-"I8"
   dis'!2.
   d'!2.
   g'!2.
   f'!2
   b'!2.
   a'!2
   c'!2.
   e'!2.
   cis'!2.
   fis'!2
   ais'!2-"RI8"
   fis'!2.
   cis'!2
   e'!2
   c'!2
   a'!2
   b'!4
   f'!2-"RI3"
   cis'!4
   gis'!2.
   b'!2-"R1"
   dis'!4
   gis'!2
   f'!4
   a'!4
   c'!4
   ais'!4
   e'!4
   d'!2.
   g'!4
   fis'!2
   cis'!2-"RI11"
   a'!2.
   e'!4
   g'!2.
   dis'!4
   c'!2.
   d'!2
   gis'!2
   ais'!4
   f'!2-"P5"
   ais'!2
   b'!4
   fis'!2
   gis'!4
   d'!2.
   e'!2-"I4"
   b'!2
   ais'!4
   dis'!2
   cis'!2
   g'!2
   f'!2-"RI3"
   cis'!4
   gis'!4
   b'!2
   g'!2
   e'!2.-"R6"
   gis'!2.
   cis'!2.
   ais'!2.
   d'!2.
   f'!4
   dis'!4
   a'!2.
   g'!2-"I7"
   d'!2.
   cis'!2.
   fis'!2.
   e'!4
   ais'!2.
   gis'!4-"P8"
   cis'!4-"R3"
   f'!4
   ais'!2.
   g'!4-"RI5"
   dis'!4
   ais'!2
   cis'!2.-"I1"
   gis'!2-"RI6"
   e'!4
   b'!2
   d'!2
   ais'!2.
   g'!2.
   a'!2
   dis'!2.
   f'!4
   c'!2
   cis'!4-"R3"
   f'!2
   ais'!4
   g'!2
   b'!2-"P11"
   e'!4
   f'!2
   c'!4
   d'!2
   gis'!2.
   ais'!2-"I10"
   f'!2
   e'!2.
   a'!4
   g'!2.
   cis'!4
   b'!2.
   d'!4
   fis'!4-"RI4"
   d'!2.
   a'!2.
   c'!4
   gis'!2
   f'!2.-"RI3"
   cis'!2-"RI11"
   a'!2.
   e'!2
   g'!2
   dis'!2
   c'!4
   d'!2
   gis'!2.
   ais'!2.
   f'!2.-"I5"
   c'!2.
   b'!2.
   e'!4
   d'!2
   gis'!2.
   fis'!2
   a'!4
   cis'!2.
   ais'!4-"R0"
   d'!4
   g'!4
   e'!2
   gis'!2
   b'!2.
   a'!2
   dis'!2
   cis'!4-"RI11"
   a'!2
   e'!4
   g'!2.
   dis'!2.
   c'!2.
   d'!2.
   gis'!4
   ais'!4
   f'!4
   fis'!4
   b'!2-"RI9"
   g'!2
   d'!4
   f'!2.
   cis'!2.
   ais'!2.-"I10"
   f'!4
   e'!4
   a'!4
   g'!2
   cis'!2-"I1"
   gis'!4
   g'!4
   c'!2.
   ais'!4-"R0"
   d'!4
   g'!2
   e'!4
   gis'!2.
   b'!2.
   a'!4
   dis'!2.
   cis'!2-"R3"
   f'!2.
   ais'!2.
   g'!2
   b'!2.
   d'!2.
   c'!4
   fis'!2.-"P6"
   b'!2
   c'!2.
   g'!2.
   a'!4
   dis'!2.
   f'!2
   d'!2
   ais'!2.-"RI8"
   fis'!4
   cis'!2.
   e'!4
   c'!2.
   a'!2
   b'!2.
   f'!2-"I5"
   c'!2
   b'!2.
   e'!2.
   d'!2.
   gis'!2
   fis'!2.
   a'!4
   cis'!2.-"I1"
   gis'!2.
   g'!2.
   c'!4-"RI10"
   gis'!2
   dis'!4
   fis'!2
   d'!2.
   b'!2
   cis'!4-"I1"
   gis'!2.
   g'!2
   c'!2.
   ais'!2.
   e'!4
   d'!4
   f'!2.
   a'!4
   fis'!2.
   b'!2.
   dis'!2.-"RI1"
   b'!2
   fis'!2
   a'!2.
   f'!2
   d'!2
   e'!2.
   ais'!2.
   c'!2
   g'!2.
   gis'!2.
   cis'!2.-"RI11"
   a'!2
   e'!2.
   g'!2.
   dis'!2
   c'!2
   d'!4
   gis'!2.-"RI6"
   e'!2.
   b'!2
   d'!4
   ais'!2.
   g'!2
   a'!4
   dis'!2
   f'!2.
   c'!2
   cis'!2
   fis'!2.-"RI4"
   d'!2.
   a'!2
   c'!2
   gis'!2.
   f'!2.
   g'!2.
   cis'!4-"RI11"
   a'!2.
   e'!2.
   g'!2
   dis'!4
   c'!2
   d'!4
   gis'!4
   ais'!4
   f'!2
   fis'!4
   b'!2-"I11"
   fis'!4
   f'!4
   ais'!2.
   gis'!2
   d'!2.
   c'!2.
   dis'!2
   g'!4
   e'!2.
   a'!2
   cis'!2-"P1"
   fis'!2.
   g'!2
   d'!4
   e'!2.
   ais'!4
   c'!2
   a'!4
   f'!2
   gis'!2
   dis'!2
   b'!2-"P11"
   e'!4
   f'!2.
   c'!2.
   d'!2.
   gis'!2
   ais'!2.
   g'!2
   dis'!2.
   fis'!2.
   cis'!2-"RI11"
   a'!2
   e'!2
   g'!2
   dis'!4
   c'!4
   d'!2
   gis'!2
   ais'!4
   f'!4-"I5"
   c'!2.
   b'!4
   e'!2
   d'!4
   gis'!2.
   fis'!2
   a'!2
   cis'!2-"R3"
   f'!4
   ais'!2.
   g'!2
   b'!2
   d'!2.
   c'!2.
   fis'!2.
   e'!2
   a'!2.-"I9"
   e'!4
   dis'!2.
   gis'!2.
   fis'!4
   c'!2
   ais'!4
   cis'!2.-"RI11"
   a'!4
   e'!4
   g'!2-"R9"
   b'!2
   e'!2.-"P4"
   a'!4
   ais'!2.
   f'!4
   g'!2-"I7"
   d'!4
   cis'!2
   fis'!2.
   e'!2
   ais'!4
   gis'!4
   b'!4
   dis'!2
   c'!2
   f'!2-"P5"
   ais'!2.
   b'!2
   fis'!2
   gis'!2
   d'!2.
   e'!2
   cis'!4
   a'!2.
   c'!4
   g'!4
   dis'!2.-"P3"
   gis'!2
   a'!4
   e'!2.
   fis'!2
   c'!2.
   d'!2.
   b'!4
   g'!2-"P7"
   c'!2
   cis'!2.
   gis'!2.
   ais'!2
   e'!2.
   fis'!4
   dis'!4
   b'!4-"I11"
   fis'!2
   f'!2.
   ais'!4
   gis'!2.
   d'!4
   c'!2
   dis'!4
   g'!2.
   e'!2
   a'!4
   cis'!4-"I1"
   gis'!4
   g'!2.
   c'!4-"I0"
   g'!2
   fis'!4
   b'!2.
   a'!2
   dis'!2
   cis'!4
   e'!2
   gis'!4
   f'!4
   ais'!2
   d'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
