%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b8-"9"
    ais1-"6"
    ais1-"11"
    e8-"10"
    e8-"12"
    c16-"5"
    b8-"7"
    e8-"12"
    b8-"7"
    ais1-"11"
    c16-"5"
    ais1-"11"
    b8-"9"
    g4\f-"4"
    b8-"7"
    c16-"8"
    e8-"12"
    ais1-"11"
    c16-"5"
    ais1-"11"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e8\mf-"9"
    g4-"6"
    g4-"11"
    gis4-"10"
    gis4-"12"
    d4-"5"
    e8\mf-"7"
    gis4-"12"
    e8\mf-"7"
    g4-"11"
    d4-"5"
    g4-"11"
    e8\mf-"9"
    f1-"4"
    e8\mf-"7"
    d4-"8"
    gis4-"12"
    g4-"11"
    d4-"5"
    g4-"11"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis2\pp-"9"
    e2\mf-"6"
    e2\mf-"11"
    fis8-"10"
    fis8-"12"
    ais16-"5"
    fis2\pp-"7"
    fis8-"12"
    fis2\pp-"7"
    e2\mf-"11"
    ais16-"5"
    e2\mf-"11"
    fis2\pp-"9"
    gis8\mf-"4"
    fis2\pp-"7"
    ais16-"8"
    fis8-"12"
    e2\mf-"11"
    ais16-"5"
    e2\mf-"11"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
