%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b4-"3"
    a'16-"2"
    b'2\f-"4"
    f'4-"6"
    b4-"3"
    a2-"1"
    b'2\f-"4"
    b'2\f-"4"
    a2-"1"
    a'16-"2"
    a2-"5"
    b'2\f-"4"
    a'16-"2"
    a'16-"2"
    a'16-"2"
    a2-"1"
    b4-"7"
    a2-"1"
    b'2\f-"4"
    b'2\f-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a16-"3"
    d'1-"2"
    e2-"4"
    d1-"6"
    a16-"3"
    f'4-"1"
    e2-"4"
    e2-"4"
    f'4-"1"
    d'1-"2"
    f'4-"5"
    e2-"4"
    d'1-"2"
    d'1-"2"
    d'1-"2"
    f'4-"1"
    a16-"7"
    f'4-"1"
    e2-"4"
    e2-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c'4\f-"3"
    g1-"2"
    d'4-"4"
    c'2-"6"
    c'4\f-"3"
    c'8-"1"
    d'4-"4"
    d'4-"4"
    c'8-"1"
    g1-"2"
    c'8-"5"
    d'4-"4"
    g1-"2"
    g1-"2"
    g1-"2"
    c'8-"1"
    c'4\f-"7"
    c'8-"1"
    d'4-"4"
    d'4-"4"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
