%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1\pp-"8"
    ais16-"9"
    gis1-"11"
    d1-"10"
    gis1-"6"
    f1\mf-"2"
    f1\mf-"2"
    gis1-"11"
    d1-"10"
    gis1\pp-"8"
    f1\mf-"2"
    d1-"10"
    gis1-"6"
    gis1-"11"
    gis1\pp-"3"
    ais16-"12"
    ais16-"12"
    gis1\pp-"8"
    ais16-"12"
    ais16-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a16-"8"
    g16-"9"
    gis8-"11"
    b2-"10"
    gis8-"6"
    ais4-"2"
    ais4-"2"
    gis8-"11"
    b2-"10"
    a16-"8"
    ais4-"2"
    b2-"10"
    gis8-"6"
    gis8-"11"
    a16-"3"
    g16-"12"
    g16-"12"
    a16-"8"
    g16-"12"
    g16-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d16-"8"
    c1-"9"
    b1-"11"
    dis16-"10"
    b1-"6"
    b4\pp-"2"
    b4\pp-"2"
    b1-"11"
    dis16-"10"
    d16-"8"
    b4\pp-"2"
    dis16-"10"
    b1-"6"
    b1-"11"
    d16-"3"
    c1-"12"
    c1-"12"
    d16-"8"
    c1-"12"
    c1-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
