%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   d'!4-"I2"
   dis'!2
   cis'!2-"P1"
   c'!2.
   d'!2.
   e'!4
   gis'!4
   g'!2
   b'!4
   ais'!4
   a'!4
   f'!2.
   fis'!2-"RI8"
   dis'!4-"P3"
   d'!4
   e'!4
   fis'!2.
   ais'!2
   a'!2.
   cis'!2.
   c'!4
   b'!4
   g'!2.-"P7"
   fis'!2-"P6"
   f'!4
   g'!2
   a'!2
   cis'!4
   c'!2.
   e'!4
   dis'!4
   d'!4
   ais'!2.
   b'!2-"I11"
   c'!4
   ais'!2.
   gis'!2.
   e'!2.
   f'!2.
   cis'!4
   d'!2
   dis'!2.-"P3"
   d'!4
   e'!4
   fis'!4
   ais'!4
   a'!4
   cis'!4
   c'!2
   b'!4-"R9"
   d'!2
   cis'!4
   f'!4
   fis'!2
   g'!2
   dis'!2.
   e'!2
   c'!4
   ais'!4
   gis'!4
   a'!4-"R7"
   c'!2.
   b'!4
   dis'!2
   e'!2-"I4"
   f'!2
   dis'!2
   cis'!4-"R11"
   e'!4
   dis'!2
   g'!2
   gis'!2
   a'!2
   f'!2.
   fis'!2.
   d'!2
   c'!4-"RI2"
   a'!4
   ais'!4
   fis'!4
   f'!2
   e'!2.
   gis'!2-"I8"
   a'!4
   g'!4
   f'!2
   cis'!4
   d'!2.-"I2"
   dis'!2
   cis'!2
   b'!2
   g'!2.
   gis'!2.
   e'!4
   f'!2-"R3"
   gis'!2
   g'!2
   b'!4
   c'!4
   cis'!2.
   a'!2-"RI11"
   fis'!2.
   g'!2
   dis'!4
   d'!2
   cis'!2.
   f'!2.
   e'!2
   gis'!4-"RI10"
   f'!4
   fis'!2
   d'!2
   cis'!4
   c'!2
   e'!4
   dis'!4
   g'!2.
   a'!2.
   b'!2.
   ais'!4-"I10"
   b'!2.
   a'!2.
   g'!4
   dis'!2
   e'!4
   c'!2.
   cis'!2.
   d'!2.-"P2"
   cis'!2.
   dis'!2.
   f'!2.-"RI7"
   d'!2
   dis'!4
   b'!2
   ais'!2.
   a'!2.-"R7"
   c'!4
   b'!2
   dis'!2.
   e'!4
   f'!2
   cis'!4
   d'!2.
   ais'!2
   gis'!2.
   fis'!2.-"I6"
   g'!2
   f'!2.
   dis'!4
   b'!4
   c'!2
   gis'!2.
   a'!2
   ais'!2.-"P10"
   a'!2.
   b'!2
   cis'!2
   f'!2.
   e'!2-"I4"
   f'!2
   dis'!2.
   cis'!2.
   a'!2
   ais'!2.-"I10"
   b'!2-"RI1"
   gis'!2.
   a'!2.
   f'!4
   e'!4
   dis'!4-"R1"
   fis'!2
   f'!2.-"P5"
   e'!4
   fis'!2
   gis'!4
   c'!2
   b'!2.
   dis'!4
   d'!4-"RI4"
   b'!4-"RI1"
   gis'!2
   a'!2.
   f'!2.
   e'!4
   dis'!2
   g'!2
   fis'!2
   ais'!4
   c'!4-"I0"
   cis'!2
   b'!4
   a'!2.
   f'!4
   fis'!4
   d'!2.
   dis'!2
   e'!2
   gis'!2.
   g'!2
   ais'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
