%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   b'2-"P11"
   a'4
   ais'2
   gis'4
   d'2
   f'2.-"R1"
   dis'2
   a'4
   fis'2
   d'2.
   gis'2.
   g'2.
   e'2.-"RI8"
   fis'4-"RI10"
   gis'2
   d'2.
   f'4
   a'4
   dis'2
   e'2.
   g'2
   cis'2.
   b'2-"P11"
   a'2.
   ais'2.
   gis'2-"I8"
   ais'4
   a'2
   b'4
   f'2.
   d'2.
   cis'2
   g'2
   dis'4
   c'2-"I0"
   d'2.
   cis'4
   dis'2.-"I3"
   f'4
   e'4
   fis'4
   c'2
   a'4
   gis'2.
   d'4
   ais'2.-"I10"
   c'4
   b'4
   cis'2
   g'2.
   e'2.
   dis'2-"RI7"
   f'2
   b'4
   d'2
   fis'2
   c'4
   cis'2
   e'2
   ais'2
   gis'2.
   a'4
   g'2-"R3"
   f'4
   b'2.
   gis'2.
   e'2
   ais'2.
   a'2.
   fis'2.
   c'2
   d'2-"R10"
   c'4
   fis'2.
   dis'4
   b'2-"I11"
   cis'2
   c'4
   d'2
   gis'2.
   f'4
   e'4
   ais'4
   fis'4-"RI10"
   gis'4
   d'2
   f'2.-"I5"
   g'4
   fis'4
   gis'2-"P8"
   fis'2
   g'2
   f'2.
   b'2
   d'2.
   dis'2
   a'2.-"RI1"
   b'2
   f'2.
   gis'2
   c'2.
   fis'2
   g'2.-"P7"
   f'4
   fis'2.
   e'2
   ais'2.
   cis'2.
   d'2.
   gis'4
   c'4
   dis'2
   a'2.
   b'2.-"R7"
   a'4
   dis'2
   c'2
   gis'2
   d'2
   cis'4
   ais'2.
   e'2.-"P4"
   d'2
   dis'2.
   cis'2
   g'4
   ais'2.
   b'2.
   f'2
   a'4-"I9"
   b'2
   ais'2.
   c'2
   fis'2
   dis'2.-"R11"
   cis'2.
   g'2.
   e'2.
   c'2
   fis'2.
   f'2.
   d'4
   gis'4
   ais'2-"RI2"
   c'2
   fis'2.
   a'2.
   cis'4
   g'4
   gis'4-"RI0"
   ais'4
   e'2.
   g'2
   b'2
   f'2.
   fis'2
   a'2
   dis'2.
   cis'2.
   d'2.
   c'2.-"P0"
   ais'4
   b'4
   a'4
   dis'4
   fis'2
   g'2
   cis'4
   f'2
   gis'2
   d'4
   e'4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
