%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   f'!4-"RI1"
   b'!4-"R3"
   f'!2
   e'!2.
   gis'!4
   ais'!2.
   d'!4
   c'!4
   g'!2.
   cis'!4
   fis'!4
   a'!2-"I9"
   dis'!2
   fis'!2.
   b'!2-"RI7"
   f'!2
   fis'!2
   d'!4
   c'!2-"RI8"
   fis'!2
   g'!2
   dis'!4
   cis'!2
   a'!2
   b'!2
   e'!2.
   ais'!4-"P10"
   e'!2.
   cis'!2.
   gis'!4
   d'!2
   g'!2.
   a'!2.
   f'!4
   dis'!4
   b'!2.-"RI7"
   f'!2.
   fis'!2
   d'!4-"P2"
   gis'!4
   f'!2.
   c'!4
   fis'!2
   b'!2.
   cis'!2
   a'!2.
   g'!2
   dis'!2-"I3"
   a'!2
   c'!4
   f'!2
   b'!2.-"I11"
   f'!2.
   gis'!2.
   cis'!2.
   g'!4
   d'!2.
   c'!2.
   e'!2
   fis'!2
   ais'!2
   a'!4
   dis'!2.-"I3"
   a'!4
   c'!4
   f'!2
   b'!2-"R3"
   f'!2
   e'!2.
   gis'!4
   ais'!4
   d'!2.
   c'!2
   g'!2
   cis'!2
   fis'!2.
   a'!4-"P9"
   dis'!4
   c'!2.
   g'!2.
   cis'!2.
   fis'!2.
   gis'!2.
   e'!2-"P4"
   ais'!4-"P10"
   e'!2.
   cis'!2
   gis'!2.
   d'!2.
   g'!2.-"RI3"
   cis'!2
   d'!2.
   ais'!2.
   gis'!4
   e'!2.
   fis'!2.
   b'!2.
   f'!2.
   c'!2.
   a'!2.-"P9"
   dis'!2
   c'!2.
   g'!4
   cis'!4
   fis'!2
   gis'!4
   e'!4-"I4"
   ais'!2.
   cis'!2
   fis'!4
   c'!2
   g'!4
   f'!2.
   a'!4
   b'!4
   dis'!2
   d'!2.-"RI10"
   gis'!4
   a'!2
   f'!2
   dis'!2.
   b'!4-"I11"
   f'!2-"P5"
   b'!4
   gis'!2
   dis'!4-"RI11"
   a'!2.
   ais'!4
   fis'!2.
   e'!2
   c'!2
   d'!2.
   g'!2
   cis'!2.
   gis'!2.
   f'!4-"I5"
   b'!2.
   d'!2
   g'!4
   cis'!2.
   gis'!2
   fis'!4
   ais'!4
   c'!2
   e'!2-"RI0"
   ais'!2
   b'!4
   g'!2.
   f'!2.
   cis'!4
   dis'!4
   gis'!4
   d'!2
   a'!2.-"RI5"
   dis'!2
   e'!2.
   c'!2
   ais'!2
   fis'!2
   gis'!2
   cis'!2.
   g'!2
   d'!4
   b'!4
   f'!2-"R9"
   b'!2
   ais'!2
   d'!2.
   e'!2
   gis'!2.-"RI4"
   d'!2.
   dis'!4
   b'!2
   a'!2.
   f'!4
   g'!4
   c'!2-"RI8"
   fis'!4
   g'!2
   dis'!2
   cis'!2
   a'!4
   b'!2.-"R3"
   f'!2.
   e'!2
   gis'!4
   ais'!2.
   d'!4
   c'!2
   g'!2-"I7"
   cis'!4
   e'!2.-"I4"
   ais'!4
   cis'!2
   fis'!4
   c'!4
   g'!2.
   f'!2.
   a'!4
   b'!4
   dis'!4-"R7"
   a'!4
   gis'!4
   c'!4
   d'!2.
   fis'!2.
   e'!4
   b'!4
   f'!4
   ais'!4
   cis'!2.
   g'!2.-"RI3"
   cis'!4
   d'!2
   ais'!2
   gis'!2.
   e'!2.
   fis'!2
   b'!2.-"RI7"
   f'!2-"P5"
   b'!2
   gis'!4
   dis'!2-"RI11"
   a'!4
   ais'!2.
   fis'!2.
   e'!2.
   c'!4-"RI8"
   fis'!2
   g'!2.
   dis'!2
   cis'!4
   a'!2.
   b'!4
   e'!2.
   ais'!2-"RI6"
   e'!2.
   f'!2.
   cis'!2.
   b'!4
   g'!4
   a'!2.-"P9"
   dis'!2
   c'!2
   g'!2
   cis'!2.
   fis'!2
   gis'!2.
   e'!4-"I4"
   ais'!2
   cis'!4
   fis'!2.
   c'!4
   g'!2
   f'!4
   a'!4
   b'!4-"P11"
   f'!4
   d'!2.
   a'!2.
   dis'!2
   gis'!4
   ais'!2
   fis'!4
   e'!2-"I4"
   ais'!2.
   cis'!2
   fis'!2
   c'!2
   g'!4
   f'!4
   a'!2
   b'!4
   dis'!2
   d'!2-"P2"
   gis'!2
   f'!4
   c'!4
   fis'!2
   b'!2
   cis'!2.
   a'!2
   g'!2
   dis'!2.
   e'!2.
   ais'!2-"RI6"
   e'!4
   f'!4
   cis'!4-"R5"
   g'!2.
   fis'!2
   ais'!4
   c'!2
   e'!2
   d'!4-"R6"
   gis'!2.
   g'!4
   b'!2.
   cis'!2.
   f'!2
   dis'!2.
   ais'!4
   e'!2.
   a'!4
   c'!2.-"RI8"
   fis'!4
   g'!2
   dis'!4
   cis'!2
   a'!2
   b'!2
   e'!2.
   ais'!2-"R2"
   e'!4
   dis'!4
   g'!4
   a'!4
   cis'!2
   b'!2
   fis'!4
   c'!2-"RI8"
   fis'!2
   g'!2.
   dis'!2.
   cis'!2.-"I1"
   g'!2.
   ais'!4
   dis'!4
   a'!2.
   e'!4
   d'!4
   fis'!2.
   gis'!4
   c'!2.-"I0"
   fis'!4
   a'!2.
   d'!2.
   gis'!4
   dis'!4
   cis'!4
   f'!2.
   g'!2
   b'!2
   ais'!2.
   e'!2
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
