%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g8\mf-"1"
    dis4-"2"
    b4-"3"
    c2-"4"
    f4-"5"
    ais2-"6"
    ais4-"7"
    dis8-"8"
    gis8-"9"
    cis8-"10"
    e2-"11"
    cis2\ff-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b2-"1"
    b16\ff-"2"
    g8\p-"3"
    g1-"4"
    cis8-"5"
    b1-"6"
    b1\f-"7"
    c8-"8"
    c4-"9"
    ais4-"10"
    e4\mf-"11"
    b8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis16-"1"
    ais16\ff-"2"
    cis16-"3"
    d2-"4"
    ais2-"5"
    c4\p-"6"
    gis16-"7"
    a4-"8"
    ais8-"9"
    dis8-"10"
    cis16-"11"
    e1-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
