%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=470\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 470\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 470\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   e'!4-"R2"
   g'!2.
   f'!2
   cis'!4
   dis'!2
   ais'!2
   b'!4-"P11"
   f'!2
   fis'!2
   dis'!2
   a'!4
   gis'!2
   g'!2.
   c'!2.
   ais'!4
   d'!2-"I2"
   gis'!2.
   g'!2
   ais'!4
   e'!2
   f'!2.
   fis'!2
   cis'!4
   dis'!4
   b'!4
   a'!2-"P9"
   dis'!2.
   e'!2
   cis'!2
   g'!2.
   fis'!2.
   f'!2.
   ais'!2
   gis'!2.
   c'!4
   d'!2.
   b'!2.-"R9"
   d'!2.
   c'!4
   gis'!2.
   ais'!2
   f'!4-"I5"
   b'!2
   ais'!2
   cis'!2.
   g'!2
   gis'!2.
   a'!2
   e'!2.
   fis'!2.
   d'!2.
   c'!4
   dis'!4-"R1"
   fis'!2
   e'!2.
   c'!2.
   d'!2.
   a'!4
   ais'!2
   b'!2
   f'!2.-"R3"
   gis'!2
   fis'!4-"RI8"
   dis'!2
   f'!2
   a'!4-"P9"
   dis'!4
   e'!4
   cis'!4
   g'!2
   fis'!2
   f'!4
   ais'!2
   gis'!2.
   c'!2-"I0"
   fis'!2.
   f'!2
   gis'!2.
   d'!4
   dis'!2
   e'!2.
   b'!2
   cis'!2.
   a'!2.
   g'!2.
   ais'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
