%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   e'4-"RI8"
   fis'2.
   c'2.
   dis'2
   g'2.
   cis'2.
   d'4
   f'2
   b'2.
   a'2
   ais'4
   gis'2-"I8"
   ais'4
   a'2.
   b'2.
   f'2.
   d'2
   cis'2
   g'2
   dis'4
   c'4
   fis'4
   e'2-"I4"
   fis'4-"P6"
   e'2.
   f'2
   dis'2.
   a'4
   c'2
   cis'4
   g'2.-"P7"
   f'2.
   fis'4
   e'4
   ais'2-"P10"
   gis'2.
   a'2.
   g'2.
   cis'2
   e'4
   f'2-"R1"
   dis'2.
   a'4
   fis'2.
   d'4
   gis'4
   g'4
   e'2-"R0"
   d'2.-"I2"
   e'2-"P4"
   d'4
   dis'2
   cis'4
   g'2
   ais'4
   b'2
   f'2
   a'4
   c'2.
   fis'4
   gis'4-"P8"
   fis'4-"RI10"
   gis'2-"I8"
   ais'2
   a'4
   b'4
   f'4
   d'2.
   cis'4
   g'2-"P7"
   f'4
   fis'2.-"R2"
   e'4-"R0"
   d'2
   gis'2.
   f'2
   cis'2.
   g'2
   fis'2
   dis'4
   a'2.
   b'2.
   ais'4
   c'2-"P0"
   ais'2.
   b'2.
   a'4
   dis'2
   fis'2.
   g'2.
   cis'2
   f'2.
   gis'4
   d'2.
   e'2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
