%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=470\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 470\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 470\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   ais'!2-"R8"
   cis'!2
   b'!2.
   g'!4
   a'!2.
   e'!2
   f'!4
   fis'!2
   c'!2.
   dis'!4
   d'!2.-"I2"
   gis'!4
   g'!2-"I7"
   cis'!2.
   c'!4
   dis'!2.
   a'!2
   ais'!4-"I10"
   e'!2.
   dis'!2
   fis'!2.
   c'!2
   cis'!4
   d'!2.
   a'!2
   b'!4
   g'!2.-"R5"
   ais'!4
   gis'!2.
   e'!2
   fis'!2
   cis'!2.-"I1"
   g'!2
   fis'!4
   a'!4
   dis'!2.
   e'!2
   f'!2.
   c'!4
   d'!2
   ais'!2
   gis'!4
   b'!2-"RI1"
   gis'!2.
   ais'!2
   d'!2
   c'!4-"R10"
   dis'!2
   cis'!2.
   a'!2.
   b'!4
   fis'!2
   g'!4-"R5"
   ais'!4
   gis'!2.
   e'!2
   fis'!2.-"R4"
   a'!4
   g'!2-"R5"
   ais'!2.
   gis'!4
   e'!2
   fis'!2-"P6"
   c'!2
   cis'!2.
   ais'!4
   e'!4
   dis'!2.
   d'!2
   g'!2.
   f'!2
   a'!2-"R7"
   c'!4
   ais'!2
   fis'!2.
   gis'!2.
   dis'!2.
   e'!4
   f'!2.
   b'!2
   d'!2.
   cis'!4-"R11"
   e'!2.
   d'!2.
   ais'!2
   c'!4
   g'!4
   gis'!4
   a'!4
   dis'!2-"P3"
   a'!4
   ais'!4
   g'!2
   cis'!2.
   c'!2.
   b'!4
   e'!4
   d'!2.
   fis'!2.-"RI8"
   dis'!2.
   f'!4
   a'!2.
   g'!2.-"R5"
   ais'!4
   gis'!4
   e'!2.
   fis'!2.
   cis'!2.
   d'!2.-"R0"
   f'!2.
   dis'!2.
   b'!2
   cis'!2.
   gis'!4
   a'!2.
   ais'!2.
   e'!2
   g'!2
   fis'!2
   c'!2.-"P0"
   fis'!4
   g'!4
   e'!2.
   ais'!4
   a'!4
   gis'!2.
   cis'!2.
   b'!2.
   dis'!2
   f'!2.
   d'!4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
