%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   b'!4-"I11"
   cis'!2
   f'!2.
   dis'!2.
   gis'!4-"R11"
   ais'!4-"P10"
   gis'!2
   e'!2
   fis'!2.-"R9"
   gis'!2
   e'!2.
   cis'!4
   ais'!4
   b'!2
   d'!2
   c'!2.
   f'!2-"I5"
   g'!2.
   b'!2.
   a'!2
   d'!2.
   c'!2-"I0"
   d'!4
   fis'!2.
   e'!2.
   a'!2
   g'!4
   ais'!2
   b'!2.
   gis'!4-"R11"
   ais'!2
   fis'!2
   dis'!2.-"P3"
   cis'!4
   a'!2
   b'!2
   fis'!2
   gis'!2
   f'!4
   e'!4
   g'!4-"RI4"
   f'!2.
   a'!2-"P9"
   g'!4
   dis'!2
   f'!4
   c'!2
   d'!4
   b'!2
   ais'!4-"P10"
   gis'!2.-"RI5"
   fis'!2.
   ais'!2.
   cis'!2
   e'!4-"P4"
   d'!2
   ais'!4-"P10"
   gis'!2.
   e'!4
   fis'!2.
   cis'!4
   dis'!2.
   c'!2
   b'!2
   d'!2.
   f'!4
   a'!2.
   g'!2-"RI4"
   f'!4
   a'!2
   c'!2
   dis'!2.
   d'!2
   b'!2
   cis'!2
   gis'!2.-"R11"
   ais'!4
   fis'!4
   dis'!2
   c'!2
   cis'!2.-"I1"
   dis'!4
   g'!2-"P7"
   f'!2
   cis'!2.
   dis'!2
   ais'!4
   c'!2-"P0"
   ais'!4
   fis'!2
   gis'!4
   dis'!4
   f'!4
   d'!2.
   cis'!4
   e'!2
   g'!4
   b'!2.
   a'!2.
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
