%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c2-"8"
    dis2-"11"
    a16-"5"
    a16-"3"
    a16-"5"
    g1-"4"
    dis8-"6"
    dis8-"6"
    dis2-"11"
    e8\p-"10"
    c2-"8"
    dis2-"11"
    e8\p-"10"
    dis2-"1"
    a1-"2"
    g1-"4"
    dis2-"11"
    a16-"3"
    a1-"9"
    a1-"9"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis1\mp-"8"
    gis4-"11"
    fis16-"5"
    fis16-"3"
    fis16-"5"
    ais16-"4"
    f1-"6"
    f1-"6"
    gis4-"11"
    dis4-"10"
    cis1\mp-"8"
    gis4-"11"
    dis4-"10"
    gis4-"1"
    f4-"2"
    ais16-"4"
    gis4-"11"
    fis16-"3"
    f4-"9"
    f4-"9"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c16-"8"
    e1-"11"
    ais4-"5"
    ais4-"3"
    ais4-"5"
    ais2\pp-"4"
    d1-"6"
    d1-"6"
    e1-"11"
    dis8-"10"
    c16-"8"
    e1-"11"
    dis8-"10"
    e1-"1"
    d1-"2"
    ais2\pp-"4"
    e1-"11"
    ais4-"3"
    d1-"9"
    d1-"9"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
