%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis4
    f1
    b8
    cis1
    cis2
    gis2
    fis16
    a16
    e16
    d1
    ais1
    fis8
    cis8
    gis1\mf
    d16
    f16
    g8
    c2
    dis16
    c2\mp
    b2\mp
    f2
    c1
    fis1
    d8
    g1
    cis2\mf
    b4\pp
    d2
    ais4
    f8
    d8
    f2\pp
    e8\ff
    a8
    fis4
    d16
    fis1
    c16\p
    cis2
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e4
    b4
    a2
    e8
    cis4\p
    f4
    ais16
    c1
    ais16
    fis2
    cis1
    b1
    cis2
    b16\p
    c2
    b4
    fis2
    cis8
    e2
    cis16\mf
    d16
    f8
    f4
    gis8\ff
    g8
    f4
    e4
    fis4
    ais16
    cis2\pp
    c16
    dis2\mp
    e4\mp
    g8\f
    e1
    b1
    a2
    f1
    g1
    c1
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f8
    e8
    c2\p
    dis1
    f4
    c8
    fis16
    f8
    g8
    ais16
    fis8
    a4
    c1
    g8
    f8
    b2
    a1
    b2\f
    a8
    dis1
    gis4\mf
    e8\mp
    ais2\ff
    a16
    cis2
    f1
    fis2
    b4\ff
    ais4
    cis16
    f4
    c16
    ais2\mp
    a2
    a16
    dis4
    fis4
    a16
    f1
    gis2\mf
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
