%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   d2.-"I 2"
   dis4
   g2
   cis2
   a2.
   ais2
   e2.
   gis4
   c2.
   fis2.
   f2.
   b2.-"R 8"
   f2.
   e2
   ais2
   d4
   fis2.
   c2.
   cis2.
   a2
   dis4
   g2-"I 7"
   gis2
   c2.
   fis2.
   d2
   dis2.-"RI 6"
   a2
   ais2
   e4
   c4
   gis2.
   d4-"P 2"
   cis2
   a2.
   dis2.
   g4-"I 7"
   gis4
   c2.
   fis2.
   d2
   dis2
   a4
   cis4
   f2.
   b4
   ais2.-"I 10"
   b2
   dis4
   a4
   f4
   fis2.
   c2.
   e4
   gis2
   d2-"R 11"
   gis2
   g2.
   cis4
   f4-"I 5"
   fis4-"I 6"
   g2
   b4
   f2.-"R 2"
   b4
   ais2
   e4
   gis2.
   c4
   fis2-"P 6"
   f2.
   cis2
   g2
   b2.
   ais2.
   e4
   c4
   gis4
   d2.
   dis2-"P 3"
   d2.
   ais4
   e2
   gis2
   g2.
   cis4
   a2
   f2.-"RI 8"
   b2.
   c4
   fis4-"P 6"
   f2.
   cis4
   g2.
   b2.
   ais2
   e4
   c4
   gis2.-"I 8"
   a2
   cis4
   g2.
   dis2.
   e2
   ais2
   d2
   fis2.
   c4-"RI 3"
   fis2.
   g4
   cis2
   a2
   f2.
   b2
   ais2
   d2
   gis2.
   e2
   dis4-"RI 6"
   a4
   ais2.-"I 10"
   b2
   dis2
   a2-"R 6"
   dis2
   d2
   gis2
   c2.
   e2
   ais4
   b4
   g2-"I 7"
   gis2
   c4
   fis2.
   d2
   dis4
   a2.
   cis2
   f2.
   b4-"P 11"
   ais2.
   fis2.
   c2
   e4
   dis2
   a2
   f4
   cis2.
   g2.
   gis4-"P 8"
   g4
   dis2
   a2
   cis2
   c2.
   fis2
   d2-"I 2"
   dis2.
   g2.
   cis4
   a2-"RI 0"
   dis4
   e4-"P 4"
   dis4
   b2
   f2.
   a4
   gis2.
   d2
   ais2
   fis2-"R 3"
   c2
   b2
   f4
   a2.
   cis2
   g2.
   gis2
   e2.
   ais2.
   d4-"P 2"
   cis2
   a2.
   dis2
   g2.
   fis2.
   c2.
   gis2
   e2
   ais2.-"I 10"
   b2.
   dis2
   a2
   f2.
   fis2
   c2.
   e2
   gis2
   d4
   cis4
   g2.-"RI 10"
   cis2.
   d2.
   gis2.
   e4-"R 1"
   ais2.
   a2.
   dis2
   g2.
   b2-"R 8"
   f2.
   e2
   ais2
   d4
   fis4-"P 6"
   f2.
   cis2
   g2.
   b4
   ais2.
   e2
   c2
   gis2.
   d4
   dis2
   a2-"RI 0"
   dis4
   e4
   ais4
   fis4
   d2
   gis2.
   g2.
   b2
   f2
   cis4
   c4-"RI 3"
   fis2-"I 6"
   g2.
   b2.
   f2
   cis2
   d2
   gis2.
   c2.
   e2-"R 1"
   ais2.
   a2
   dis4
   g2.
   b2.
   f2.
   fis4
   d2.
   gis2.
   c2-"P 0"
   b2.
   g4
   cis4
   f2
   e2.
   ais4
   fis2.
   d2
   gis4
   a2
   dis4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
