%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a8
    dis1
    f4
    fis2
    f16
    gis2
    c4
    ais4
    fis2
    fis16
    f4
    dis4
    dis1
    dis2
    a2
    a16
    cis1
    dis16\mp
    g1
    d16
    e4
    gis16
    g2
    fis1
    g4
    e2
    d8
    fis2
    g4
    c16
    gis16\f
    d2
    cis4
    fis4
    a4
    d2
    ais1
    e2\f
    gis2
    c16
    b1
    c4
    d4
    cis1
    gis16
    e1
    b1
    b4
    dis16
    c8
    cis4
    e1
    g4
    cis4
    g2
    d16
    ais16
    c4
    fis8
    c2
    f2
    cis2\f
    c2
    g2
    e16
    ais4
    gis2
    g2\ff
    b1
    g4\mp
    ais8
    cis1
    ais1
    e2
    b2
    g16\p
    g8
    dis1
    e16\p
    dis2
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis2
    b8
    e8
    dis2
    a8\ff
    dis8
    fis16
    gis1\pp
    a16\mp
    gis4
    cis1
    f2
    d8
    b2
    fis16
    cis8
    f8
    f1
    gis2
    gis8
    dis4
    cis16
    ais4
    e1
    e1
    f2
    d8
    e8
    ais1
    dis1
    a16
    f4
    a1\mf
    fis8
    fis16
    dis8
    dis8
    f16
    ais2
    c4
    e2
    e4
    dis16
    e8
    ais2
    gis16
    a16
    fis1
    f16
    a2
    d16
    g2
    d4
    b1
    d8
    gis4\f
    cis2
    fis8
    gis2
    cis2
    dis1
    ais2\mf
    fis16
    a8
    fis16
    d4
    dis8
    gis4
    b4\p
    f4
    f2
    a2
    c16
    b4
    a1
    cis8
    a4\ff
    g16
    a1
    f4
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a4
    b4
    e1\pp
    c4
    f2
    gis4
    b2
    b2\ff
    b16\ff
    ais2\p
    cis4\pp
    f8
    d2
    cis16
    f4
    c1
    b1\pp
    f1
    c16
    b1
    fis4
    b4
    dis4
    e2
    dis16
    ais8\p
    d1
    c16
    d4
    dis1
    gis8
    gis4
    f16
    gis16
    f1
    b4
    c1
    c16
    fis16
    d1\ff
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
