%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis1-"1"
    ais16-"2"
    f2-"3"
    g1-"4"
    gis8-"5"
    g4-"6"
    f16-"7"
    gis4\mf-"8"
    e8-"9"
    ais8-"10"
    cis2-"11"
    a8-"12"
    ais2-"13"
    gis16-"14"
    cis2-"15"
    f8-"16"
    cis8\mf-"17"
    ais4-"18"
    dis4-"19"
    fis1\mp-"20"
    e8\mf-"21"
    ais4-"22"
    d2-"23"
    b2-"24"
    g2-"25"
    ais2-"26"
    a8-"27"
    gis4\f-"28"
    e1-"29"
    g16-"30"
    gis2-"31"
    ais4-"32"
    b1-"33"
    a16\f-"34"
    d1-"35"
    f1\p-"36"
    c16-"37"
    a1-"38"
    fis8\ff-"39"
    e4-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a8-"1"
    a16-"2"
    c8-"3"
    d8-"4"
    cis4\pp-"5"
    gis1\ff-"6"
    e1-"7"
    ais16-"8"
    d1-"9"
    cis1-"10"
    gis1-"11"
    b8-"12"
    fis16\mp-"13"
    ais8\f-"14"
    gis4\p-"15"
    c8\mp-"16"
    g1-"17"
    c16-"18"
    a2-"19"
    b2-"20"
    f1-"21"
    b4-"22"
    fis4-"23"
    d8-"24"
    g16\ff-"25"
    dis16-"26"
    f2-"27"
    fis4-"28"
    g4-"29"
    d1-"30"
    cis1-"31"
    d2-"32"
    b4-"33"
    a8-"34"
    e1-"35"
    cis8-"36"
    d1-"37"
    ais1-"38"
    gis4\mf-"39"
    g1-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a2-"1"
    b1-"2"
    ais2\ff-"3"
    gis16-"4"
    d2-"5"
    g8-"6"
    dis8-"7"
    ais16-"8"
    fis8-"9"
    g16-"10"
    d2-"11"
    d2-"12"
    b8\mp-"13"
    gis1-"14"
    cis2-"15"
    ais1-"16"
    f1\p-"17"
    gis1\ff-"18"
    dis4-"19"
    e8-"20"
    c1-"21"
    d2\pp-"22"
    a2-"23"
    cis16-"24"
    gis2-"25"
    ais16-"26"
    gis1-"27"
    dis4-"28"
    c1\f-"29"
    b16-"30"
    b16\f-"31"
    gis16-"32"
    cis2-"33"
    gis2-"34"
    ais2-"35"
    ais1-"36"
    a2-"37"
    fis8-"38"
    d8\mp-"39"
    e4-"40"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
