%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   d'!2.-"P2"
   cis'!2.
   g'!2.
   f'!2
   ais'!2
   b'!2
   a'!2
   e'!2
   gis'!2.
   fis'!2-"RI7"
   a'!4
   dis'!4
   cis'!2
   f'!2
   c'!4
   ais'!2.-"R9"
   g'!2
   cis'!4
   dis'!4-"I3"
   e'!4
   ais'!2
   c'!2.-"I0"
   cis'!2
   g'!2
   a'!2.
   e'!4
   dis'!4-"R2"
   c'!4
   fis'!4
   gis'!4
   e'!4
   a'!2
   b'!4
   ais'!2
   f'!2.-"P5"
   e'!2.
   ais'!4
   gis'!4
   cis'!2.-"RI2"
   e'!2.
   ais'!2
   gis'!4
   c'!4
   g'!2
   f'!4
   fis'!4
   b'!4-"I11"
   c'!2
   fis'!2
   gis'!2
   dis'!2-"P3"
   d'!4
   gis'!4-"R7"
   f'!2.
   b'!4
   cis'!2-"RI2"
   e'!2
   ais'!2
   gis'!2.-"I8"
   a'!2.
   dis'!2.
   f'!4
   c'!4
   b'!4
   cis'!2.-"RI2"
   e'!2.
   ais'!4
   gis'!4
   c'!2
   g'!2.
   f'!4
   fis'!2.
   b'!2.
   a'!4-"R8"
   fis'!4
   c'!2
   d'!4
   ais'!4
   dis'!4-"I3"
   e'!2.
   ais'!2
   c'!4
   g'!2.
   fis'!2
   gis'!2.
   cis'!2
   a'!2
   b'!2.
   f'!4
   d'!4-"I2"
   dis'!4
   a'!2
   b'!2
   fis'!4
   f'!4
   g'!2.-"I7"
   gis'!2
   d'!2.
   e'!2.
   b'!2.
   ais'!4-"RI11"
   cis'!2
   g'!2.
   f'!4
   a'!2
   e'!2.
   d'!4
   dis'!2
   gis'!2.
   fis'!4
   c'!2.-"RI1"
   dis'!2.
   a'!2.-"R8"
   fis'!2
   c'!2.
   d'!2.
   ais'!4
   dis'!4
   f'!2.
   e'!4-"RI5"
   g'!4
   cis'!4-"RI2"
   e'!2.
   ais'!2.
   gis'!4
   c'!2-"P0"
   b'!2
   f'!4
   dis'!2
   gis'!2.
   a'!2.
   g'!4
   d'!2
   fis'!2
   e'!2
   ais'!4
   cis'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
