%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g8\mf-"1"
    dis4-"2"
    b4-"3"
    c2-"4"
    f4-"5"
    ais2-"6"
    ais4-"7"
    dis8-"8"
    gis8-"9"
    cis8-"10"
    e2-"11"
    cis2\ff-"12"
    b8-"13"
    e4-"14"
    b1-"15"
    d4-"16"
    cis16-"17"
    f4-"18"
    c8\ff-"19"
    e8-"20"
    b8-"21"
    b8\mf-"22"
    fis16\pp-"23"
    g2-"24"
    b8-"25"
    cis4-"26"
    b8-"27"
    fis8-"28"
    ais4-"29"
    cis2-"30"
    a2-"31"
    a8-"32"
    b4-"33"
    dis8-"34"
    ais2\p-"35"
    g1\f-"36"
    ais1-"37"
    cis8\p-"38"
    gis1-"39"
    b4-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b2-"1"
    b16\ff-"2"
    g8\p-"3"
    g1-"4"
    cis8-"5"
    b1-"6"
    b1\f-"7"
    c8-"8"
    c4-"9"
    ais4-"10"
    e4\mf-"11"
    b8-"12"
    fis1\mp-"13"
    fis2-"14"
    cis2\f-"15"
    f1-"16"
    e1\pp-"17"
    f2-"18"
    d8-"19"
    ais1-"20"
    g4-"21"
    fis4-"22"
    d2-"23"
    b1-"24"
    dis4-"25"
    b16-"26"
    d8-"27"
    e2\f-"28"
    b1-"29"
    cis1-"30"
    fis1-"31"
    d8-"32"
    d4-"33"
    c2-"34"
    fis4-"35"
    fis1-"36"
    c1-"37"
    g2-"38"
    c16-"39"
    dis16-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis16-"1"
    ais16\ff-"2"
    cis16-"3"
    d2-"4"
    ais2-"5"
    c4\p-"6"
    gis16-"7"
    a4-"8"
    ais8-"9"
    dis8-"10"
    cis16-"11"
    e1-"12"
    c1-"13"
    ais16-"14"
    e4-"15"
    b8-"16"
    a2-"17"
    c4-"18"
    d4\ff-"19"
    g16\mp-"20"
    ais8-"21"
    gis16-"22"
    gis1-"23"
    e16\f-"24"
    cis2-"25"
    gis1-"26"
    cis8-"27"
    ais4-"28"
    cis16-"29"
    b4\pp-"30"
    c4-"31"
    f8-"32"
    fis1-"33"
    ais2-"34"
    g8-"35"
    g1\mf-"36"
    ais1\pp-"37"
    dis4-"38"
    g2-"39"
    ais16-"40"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
