%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   dis'!2.-"RI11"
   f'!4
   ais'!2
   d'!2
   a'!2
   cis'!2.
   c'!4
   fis'!2.
   gis'!2
   e'!2.
   g'!4-"P7"
   b'!2.
   d'!4
   ais'!2.
   c'!2
   fis'!2.-"R10"
   e'!2.
   b'!2
   g'!4-"P7"
   b'!2.
   d'!2
   ais'!2.-"RI6"
   c'!4
   f'!2.
   a'!2
   e'!4
   gis'!2
   g'!4
   cis'!4
   dis'!4-"RI11"
   f'!4
   ais'!4
   d'!4
   a'!2.
   cis'!2
   c'!2.
   fis'!2.
   gis'!2.
   e'!4
   g'!2
   b'!2-"R3"
   a'!2
   e'!4
   c'!2.
   f'!2
   cis'!4
   d'!2
   gis'!4-"I8"
   e'!2
   cis'!4
   f'!2.
   dis'!2.-"RI11"
   f'!4
   ais'!2
   d'!2
   a'!4
   cis'!2
   c'!4
   fis'!4
   gis'!2
   e'!4
   g'!2.
   b'!2.-"R3"
   a'!4
   e'!2-"P4"
   gis'!2
   b'!2-"RI7"
   cis'!2.
   fis'!2.
   ais'!2
   f'!2
   a'!2.
   gis'!4
   d'!4-"P2"
   fis'!2.
   a'!2.
   f'!2.
   g'!2.-"RI3"
   a'!2
   d'!4
   fis'!2.
   cis'!2.
   f'!4
   e'!2.
   ais'!2
   c'!2-"RI8"
   d'!4
   g'!2.-"RI3"
   a'!2.
   d'!4
   fis'!2
   cis'!2.-"R5"
   b'!2.
   fis'!2.
   d'!2
   g'!2
   dis'!2
   e'!2.
   ais'!2
   gis'!2.
   c'!4
   a'!2
   f'!4-"P5"
   a'!2.
   c'!2.-"I0"
   gis'!2.
   f'!2.
   a'!4
   g'!2
   cis'!2
   d'!2.
   ais'!2
   dis'!2
   b'!2.
   fis'!2.
   e'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
