%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a8-"7"
    a8-"6"
    cis1-"9"
    g1-"4"
    cis2-"10"
    f16-"12"
    f16-"12"
    ais8-"5"
    f16-"1"
    g1-"11"
    g1-"4"
    a8-"7"
    g1-"11"
    a8-"7"
    g1-"11"
    f16-"1"
    cis2-"10"
    g1-"4"
    cis2-"10"
    f16-"1"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b8-"7"
    b8-"6"
    a8-"9"
    d8-"4"
    gis1-"10"
    e1-"12"
    e1-"12"
    cis1-"5"
    e1-"1"
    d8-"11"
    d8-"4"
    b8-"7"
    d8-"11"
    b8-"7"
    d8-"11"
    e1-"1"
    gis1-"10"
    d8-"4"
    gis1-"10"
    e1-"1"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d2-"7"
    d2-"6"
    a2-"9"
    gis16-"4"
    d2-"10"
    dis8-"12"
    dis8-"12"
    g16-"5"
    dis8-"1"
    gis16-"11"
    gis16-"4"
    d2-"7"
    gis16-"11"
    d2-"7"
    gis16-"11"
    dis8-"1"
    d2-"10"
    gis16-"4"
    d2-"10"
    dis8-"1"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
