%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1-"5"
    fis1-"3"
    dis4-"2"
    g4-"7"
    dis4-"2"
    g4-"7"
    fis2\mp-"4"
    g4-"7"
    fis1-"3"
    dis4-"2"
    g4-"7"
    b2-"1"
    b2-"1"
    g4-"7"
    fis1-"5"
    dis4-"2"
    fis2\mp-"4"
    fis1-"5"
    fis2\mp-"4"
    dis4-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b1\mf-"5"
    b1\mf-"3"
    a4-"2"
    g2-"7"
    a4-"2"
    g2-"7"
    fis4-"4"
    g2-"7"
    b1\mf-"3"
    a4-"2"
    g2-"7"
    fis2-"1"
    fis2-"1"
    g2-"7"
    b1\mf-"5"
    a4-"2"
    fis4-"4"
    b1\mf-"5"
    fis4-"4"
    a4-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c1-"5"
    c1-"3"
    cis8-"2"
    fis16-"7"
    cis8-"2"
    fis16-"7"
    a4-"4"
    fis16-"7"
    c1-"3"
    cis8-"2"
    fis16-"7"
    e4-"1"
    e4-"1"
    fis16-"7"
    c1-"5"
    cis8-"2"
    a4-"4"
    c1-"5"
    a4-"4"
    cis8-"2"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
