%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   c'!2.-"RI1"
   dis'!2
   a'!2
   g'!2.
   b'!2
   fis'!4
   e'!4
   f'!2.
   ais'!2
   gis'!4
   d'!4-"RI3"
   f'!4
   b'!2.
   a'!4
   cis'!2
   gis'!2.
   fis'!2.
   g'!2.
   c'!4
   ais'!2.
   e'!4
   dis'!2.-"P3"
   d'!4
   gis'!4
   fis'!2
   b'!2
   c'!2
   ais'!2.-"RI11"
   cis'!2.
   g'!4
   f'!4
   a'!2.
   e'!2
   d'!2.
   dis'!4-"P3"
   d'!2
   gis'!2
   fis'!2
   b'!4
   c'!2
   ais'!4-"RI11"
   cis'!2.
   g'!2.
   f'!4
   a'!2
   e'!2.
   d'!2
   dis'!2
   gis'!4-"R7"
   f'!2.
   b'!2-"I11"
   c'!2
   fis'!2
   gis'!4
   dis'!2.
   d'!2
   e'!2.
   a'!2.-"I9"
   ais'!4
   e'!2
   fis'!2.
   cis'!2
   c'!4
   d'!2.
   g'!2
   dis'!2
   f'!4
   b'!4
   gis'!2.-"I8"
   a'!2
   dis'!2.
   f'!2
   c'!4
   b'!4
   cis'!2.-"R0"
   ais'!2-"RI11"
   cis'!2.
   g'!2.
   f'!2.
   a'!2
   e'!2
   d'!2.
   dis'!2.
   gis'!2-"RI9"
   b'!4
   f'!4
   dis'!4
   g'!2
   d'!2
   c'!4
   cis'!2.
   fis'!2
   e'!2
   ais'!2.-"RI11"
   cis'!2
   g'!2.
   f'!2
   a'!2.
   e'!2
   d'!2
   dis'!4
   gis'!2.-"I8"
   a'!2-"P9"
   gis'!4
   d'!2.
   c'!4
   f'!2-"P5"
   e'!2
   ais'!2
   gis'!2.-"R7"
   f'!2.
   b'!4
   cis'!4
   a'!2.
   d'!2.
   e'!2.-"I4"
   f'!2
   b'!2
   cis'!2.
   gis'!2
   g'!2
   a'!4
   d'!4
   ais'!2
   c'!2.
   fis'!2.-"P6"
   f'!2
   b'!2
   a'!4
   d'!2
   dis'!4
   cis'!4
   gis'!2
   c'!4
   ais'!4
   e'!2-"R3"
   cis'!4
   g'!4
   a'!4
   f'!2-"I5"
   fis'!4
   c'!2
   d'!2
   a'!4
   gis'!2.
   ais'!2.-"RI11"
   cis'!2
   g'!2
   f'!2.
   a'!2.
   e'!4
   d'!2
   dis'!2.-"P3"
   d'!4
   gis'!2.
   fis'!2
   b'!2.
   c'!2.
   ais'!2.
   f'!2-"RI6"
   gis'!4
   d'!4
   c'!2.
   e'!2
   b'!2.
   a'!2-"R8"
   fis'!2.
   c'!4
   d'!2
   ais'!2
   dis'!2
   f'!2
   e'!4
   b'!4
   cis'!4
   g'!2.
   gis'!4-"P8"
   g'!2
   cis'!4
   b'!2.
   e'!4
   f'!2-"I5"
   fis'!2
   c'!2.
   d'!2
   a'!2.
   gis'!2
   ais'!2
   dis'!2.
   b'!4-"I11"
   c'!2.
   fis'!2.
   gis'!2.
   dis'!2-"RI4"
   fis'!4
   c'!2.
   ais'!4-"RI11"
   cis'!4
   g'!2.
   f'!4
   a'!2
   e'!4
   d'!2.
   dis'!4
   gis'!4-"R7"
   f'!2
   b'!2.
   cis'!2.
   a'!2
   d'!2.
   e'!2.
   dis'!4
   ais'!2.-"RI11"
   cis'!2
   g'!2.
   f'!4
   a'!4
   e'!2.
   d'!4
   dis'!2.
   gis'!4-"I8"
   a'!4-"P9"
   gis'!2
   d'!2
   c'!2.
   f'!2.
   fis'!2.
   e'!4
   b'!4-"RI0"
   d'!2.
   gis'!2
   fis'!2.
   ais'!2
   f'!2.
   dis'!4
   e'!4
   a'!4-"P9"
   gis'!2
   d'!2
   c'!2
   f'!4
   fis'!2.
   e'!4
   b'!2
   dis'!2
   cis'!2.
   g'!2
   ais'!2-"RI11"
   cis'!4
   g'!2
   f'!2.
   a'!2
   e'!4
   d'!4-"RI3"
   f'!4
   b'!2.
   a'!4
   cis'!2
   gis'!2.
   fis'!2
   g'!2.
   c'!2.
   ais'!4
   e'!2.
   dis'!4-"P3"
   d'!2.
   gis'!2
   fis'!4
   b'!4
   c'!2
   ais'!2-"RI11"
   cis'!4
   g'!2.
   f'!4
   a'!2.
   e'!4
   d'!2
   dis'!2.
   gis'!2.-"I8"
   a'!2
   dis'!2
   f'!2
   c'!2.
   b'!2.
   cis'!4
   fis'!2
   d'!2.-"R1"
   b'!2.
   f'!2.
   g'!4
   dis'!2.
   gis'!2.
   ais'!4
   a'!4
   e'!2.
   fis'!2.-"P6"
   f'!2
   b'!4-"P11"
   ais'!2.
   e'!2.
   d'!2.
   g'!2
   gis'!4
   fis'!2
   cis'!2.
   f'!2
   dis'!2.
   a'!2.-"R8"
   fis'!2
   c'!2.
   d'!2
   ais'!4
   dis'!4
   f'!2
   e'!4
   b'!4
   cis'!2
   g'!4
   gis'!2.-"R7"
   f'!4
   b'!2.
   cis'!2
   a'!2.
   d'!4-"R1"
   b'!2.
   f'!2
   g'!2.
   dis'!4
   gis'!2-"I8"
   a'!2.
   dis'!2
   f'!4
   c'!4
   b'!2.
   cis'!2.
   fis'!2.
   d'!2.
   e'!2.
   ais'!2
   g'!2.-"P7"
   fis'!2.
   c'!4
   ais'!4
   dis'!2
   e'!2
   d'!4
   a'!4
   cis'!2.
   b'!4-"I11"
   c'!4
   fis'!2
   gis'!4
   dis'!2.
   d'!4
   e'!2.
   a'!4
   f'!4-"R4"
   d'!2.
   gis'!4-"R7"
   f'!2.
   b'!4-"RI0"
   d'!4
   gis'!4
   fis'!2.-"RI7"
   a'!2.-"P9"
   gis'!2
   d'!2.
   c'!2.
   f'!2.-"I5"
   fis'!4
   c'!2
   d'!4
   a'!2
   gis'!2.
   ais'!2
   dis'!4-"R2"
   c'!4
   fis'!2.
   gis'!2
   e'!2
   a'!2.
   b'!2
   ais'!2-"RI11"
   cis'!2
   g'!2.
   f'!4
   a'!2.
   e'!2.
   d'!2
   dis'!4
   gis'!2.
   fis'!2
   c'!4-"P0"
   b'!2
   f'!4
   dis'!4
   gis'!2
   a'!2.
   g'!4
   d'!2.
   fis'!2.
   e'!2
   ais'!2
   cis'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
