%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais8-"4"
    g2\f-"5"
    gis4-"7"
    g1-"1"
    dis4-"9"
    dis4-"2"
    e8-"6"
    ais8-"4"
    g2\f-"5"
    c4-"12"
    e8-"6"
    e4-"10"
    gis4-"7"
    dis4-"2"
    gis4-"11"
    c4-"12"
    dis4-"9"
    gis4-"11"
    gis4-"7"
    e8-"6"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"4"
    e8\ff-"5"
    d8-"7"
    c4\p-"1"
    cis16-"9"
    cis16-"2"
    cis2\ff-"6"
    dis8-"4"
    e8\ff-"5"
    dis16-"12"
    cis2\ff-"6"
    g8\mf-"10"
    d8-"7"
    cis16-"2"
    d8-"11"
    dis16-"12"
    cis16-"9"
    d8-"11"
    d8-"7"
    cis2\ff-"6"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"4"
    fis16-"5"
    cis4-"7"
    gis8-"1"
    dis2-"9"
    dis2-"2"
    a2-"6"
    gis1-"4"
    fis16-"5"
    e2-"12"
    a2-"6"
    a4-"10"
    cis4-"7"
    dis2-"2"
    cis4-"11"
    e2-"12"
    dis2-"9"
    cis4-"11"
    cis4-"7"
    a2-"6"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
