%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   a4-I 9
   ais2
   gis2.
   c2.-RI 6
   dis2
   e2
   gis2.
   b2.
   ais2
   cis2
   d4
   a2
   f2
   g4-RI 1
   ais2.
   b4
   dis2.
   fis2
   f4
   gis4
   a2.
   e2.
   c2-P 0
   b2
   cis4
   a2.
   e2.
   f2-R 11
   d2
   cis2.-R 7
   ais2.
   a2
   f4
   d2
   dis2.
   c2
   b2
   e2-P 4
   dis2
   f2.
   cis4
   gis2.
   a2
   c2
   b4
   d2.-P 2
   cis4-P 1
   c4-RI 6
   dis2.
   e2
   gis2.
   b2
   ais2-I 10
   b2.
   a4-I 9
   ais2.-P 10
   a2.
   b2
   g2
   d4
   dis2
   fis2.
   f2
   gis2.
   c4
   cis2-P 1
   c2.
   d2.
   ais4
   f2
   fis4
   a2.-R 3
   fis4
   f2-I 5
   fis2
   e2
   gis2.
   cis4
   c4
   a2.-I 9
   ais2.
   gis4
   c4
   f4
   e4-P 4
   dis2.
   f2
   cis4
   gis4
   a4
   c4-R 6
   a2.
   gis2
   e2
   cis2
   d2.
   b4
   ais2
   dis2
   g2-RI 1
   ais4-I 10
   b2.
   a4
   cis4
   fis2
   f4
   d4
   dis4
   c2.
   gis4
   g4-I 7
   gis4
   fis2.
   ais2
   dis4
   d4
   b2
   c4
   a2-P 9
   gis2.
   ais2.
   fis4
   cis4
   d4
   f2.
   e2.
   g4
   b2.
   c2.-P 0
   b2.
   cis4
   a2.
   e4
   f2
   gis2.
   g2.
   ais4
   d2
   dis2.
   fis4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
