%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   ais4-"P 10"
   g2.-"P 7"
   e4
   dis4
   a2.
   fis4
   ais4
   c4
   b2
   cis2.
   f4-"P 5"
   d2.
   cis2.-"R 0"
   g2.-"P 7"
   e2.
   dis4
   a2-"R 8"
   dis2
   fis4
   d2
   c4
   cis4
   b2
   g2
   ais2
   e2
   f4-"P 5"
   d2
   cis4-"R 0"
   g2.
   ais4-"RI 11"
   e2.
   cis2.
   f2.
   g2.
   fis2.
   gis2
   c4
   a2.-"RI 10"
   dis4
   c4
   e2.
   fis2.-"I 6"
   a2
   ais2.-"RI 11"
   e2
   cis4
   f2.
   g2.
   fis2
   gis2
   c2
   a2
   dis4
   d2
   b4-"RI 0"
   f4
   d4
   fis2
   gis2.
   g4-"RI 8"
   cis4
   ais2
   d4
   e2
   dis2
   f4
   a2
   fis2.
   c2
   b2
   gis2.-"R 7"
   d2.
   f2
   cis2
   b4
   c2.
   ais4
   fis4
   a2.-"R 8"
   dis4
   fis2.
   d4-"P 2"
   b4
   ais4-"RI 11"
   e2.
   cis4
   f2.
   g4-"P 7"
   e2.
   dis2
   a2
   fis4
   ais2-"RI 11"
   e2
   cis2
   f4
   g4-"RI 8"
   cis2.
   ais2
   d2.
   e2
   dis2
   f4-"I 5"
   gis4
   a2.
   dis4
   fis2.
   d4
   c4
   cis4
   b2
   g2
   ais4-"RI 11"
   e2-"RI 5"
   ais2.-"RI 11"
   e2.
   cis2
   f4
   g2.
   fis2
   gis4
   c4
   a4
   dis4-"RI 4"
   a2
   fis4
   ais4
   c2.
   b2
   cis2
   f2.
   d2
   gis4
   g2.-"P 7"
   e2
   dis2.
   a2
   fis4
   ais2
   c2.-"R 11"
   fis2.
   a4
   f4
   dis4-"RI 4"
   a2.
   fis2.
   ais4
   c4
   b2
   cis2.
   f2.
   d2
   gis2
   g4
   e2.-"P 4"
   cis4
   c2.
   fis2
   dis2.
   g2.
   a2.
   gis4
   ais4
   d2-"P 2"
   b2
   ais2-"RI 11"
   e2
   cis4-"P 1"
   ais2.
   a4
   dis2.
   c2.
   e2.
   fis2
   f4
   g2-"RI 8"
   cis2.-"R 0"
   g2.
   ais2
   fis4
   e4
   f2.
   dis2.
   b4
   d2
   gis4
   a2.
   c2.-"R 11"
   fis2
   a2.
   f4
   dis4
   e2
   d4
   ais2
   cis2.-"I 1"
   e2
   f4
   b4
   d4
   ais2
   gis4
   a4
   g2.
   dis4
   fis2.
   c4-"R 11"
   fis4
   a2-"I 9"
   c4-"P 0"
   a2.
   gis4
   d4
   b2.
   dis4
   f2.
   e4
   fis4
   ais2
   g2.
   cis2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
