%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   e2-"R 3"
   ais2-"R 9"
   e2.
   g2
   dis2
   cis2.
   d2.
   c4
   gis4
   b4
   f2.
   fis2
   a2.-"RI 10"
   dis2
   c2
   e4-"R 3"
   ais2.
   cis4
   a4
   g4-"RI 8"
   cis2
   ais2.
   d2
   e4
   dis4-"R 2"
   a4
   c2
   gis2.
   fis4
   g2.
   f4
   cis2.
   e2.
   ais2
   b2.-"I 11"
   d4
   dis4
   a2
   c4
   gis2.
   fis2
   g4
   f4-"RI 6"
   b4
   gis2.-"RI 9"
   d2.
   b2.
   dis2.
   f2.
   e2.
   fis2
   ais2.
   g2.-"RI 8"
   cis2.
   ais4
   d2.
   e2.
   dis4
   f2
   a4
   fis4
   c4
   b2
   gis4-"RI 9"
   d2.
   b4
   dis4
   f4
   e2-"P 4"
   cis4
   c2-"I 0"
   dis4
   e4
   ais4
   cis2
   a2.
   g2.
   gis4
   fis2.
   d2.
   f4
   b4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
