%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   g'2.-"R0"
   cis'4
   e'2.
   ais'2.
   fis'2.-"R11"
   c'2-"R5"
   fis'4
   a'2.
   dis'2
   b'4
   e'2.
   ais'2.
   gis'2
   cis'2.
   g'4
   d'2.
   f'4-"RI0"
   b'2
   gis'2.
   d'2.
   fis'4-"RI1"
   c'4
   a'2
   dis'4-"RI10"
   a'4
   fis'4
   c'2.
   e'2.
   b'2
   f'2.
   g'2.
   d'2-"P2"
   b'4
   e'2.
   ais'4
   f'2.
   g'2
   cis'2.
   gis'2
   c'4
   fis'4
   dis'2-"RI10"
   a'2
   fis'2-"I6"
   a'2.-"RI4"
   dis'2
   c'2
   fis'2
   ais'2.
   f'2
   b'2
   cis'2
   gis'4
   d'2.
   g'2.-"I7"
   ais'2.
   f'4
   b'4
   e'2.
   d'2
   gis'2.
   cis'4
   a'2
   dis'2-"P3"
   c'2
   f'2.
   b'2
   fis'2
   gis'2
   d'2
   a'2
   cis'4
   g'2.
   e'2.-"P4"
   cis'2.
   fis'2.
   c'2
   g'2.
   a'2.
   dis'2.-"I3"
   fis'2.
   cis'2.
   g'4
   c'4
   ais'4
   e'2
   a'2
   f'2
   b'4
   d'2.-"RI9"
   gis'2
   f'2
   b'2-"P11"
   gis'2
   cis'2
   g'2.-"I7"
   ais'2.
   f'2.
   b'4-"RI6"
   f'2-"RI0"
   b'4
   gis'2.
   d'4
   fis'2-"P6"
   dis'2
   gis'2
   d'2.
   a'4
   b'4
   f'4
   c'2.
   e'2.
   ais'2-"P10"
   g'2.
   c'2
   fis'2.
   cis'2.
   dis'2.
   a'4
   e'2.
   gis'2.
   d'2
   b'2-"RI6"
   f'2
   d'2
   gis'2.
   c'2.
   g'2.
   cis'2.
   dis'2.-"R8"
   a'2.
   c'2.-"R5"
   fis'4
   a'4
   dis'2
   b'4
   e'2
   ais'2
   gis'4
   cis'2.-"RI8"
   g'2
   e'2.
   ais'2
   d'4
   a'2.
   dis'2-"R8"
   a'2
   c'4
   fis'2.
   d'2.
   g'2
   cis'2
   b'2.
   e'4
   ais'2.
   f'4
   gis'2.-"RI3"
   d'4
   b'2.
   f'2
   a'2
   e'2
   ais'4
   c'2.
   g'2.
   cis'4
   fis'4
   dis'2.-"I3"
   fis'2
   cis'4
   g'4
   c'2.
   ais'2
   e'2
   a'2
   f'4
   b'2-"R4"
   f'2
   gis'4
   d'2
   ais'4
   dis'4
   a'4
   g'2-"I7"
   ais'2
   f'4
   b'4
   e'2
   d'4
   gis'4
   cis'2.
   a'4-"R2"
   dis'4
   fis'2
   c'2
   gis'4
   cis'2.
   g'2-"I7"
   ais'4
   f'2
   b'2.
   e'2.
   d'2
   gis'2
   cis'4
   a'2
   dis'2.-"P3"
   c'4
   f'2.
   b'2
   fis'2.
   gis'2.
   d'4-"I2"
   f'4
   c'2
   fis'4
   b'2.
   a'2.
   dis'2-"R8"
   a'2.
   c'4
   fis'2
   d'2.
   g'2
   cis'4-"R6"
   g'4
   ais'2.
   e'2
   c'4
   f'2.
   b'2
   a'2.-"R2"
   dis'2
   fis'2.
   c'2
   gis'2
   cis'4
   g'2.
   f'2.-"P5"
   d'4
   g'2.
   cis'2.
   gis'4
   ais'2-"P10"
   g'4-"I7"
   ais'2.-"P10"
   g'2
   c'4
   fis'2.
   cis'2.
   dis'4
   a'2
   e'2
   gis'2.
   d'2
   b'2.-"I11"
   d'2
   a'2
   dis'4
   gis'4
   fis'2
   c'2-"I0"
   dis'4
   ais'2.
   e'2
   a'2.
   g'4
   cis'4
   fis'4
   d'2.
   gis'2.
   b'2.
   f'4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
