%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1
    dis1
    b16
    a2
    ais1
    gis8
    g4\mf
    c8
    e1
    fis1
    b1\mf
    dis2
    a8\mp
    g1
    g8
    d8\ff
    dis2
    d1
    c4
    a4
    a8
    ais16
    f16
    f16
    gis2
    g16\p
    fis2\f
    d4
    d1
    a16\pp
    e16
    a16
    gis2
    e2
    a1
    a8
    a1\f
    gis4
    d2
    f16
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8
    b16
    cis1
    a1\mp
    dis8
    ais2
    cis4
    c8
    fis4
    g1
    dis2
    f8\pp
    c2
    d1
    c8
    dis1
    d1
    g4
    b8
    d2
    f2
    e8
    ais4\p
    ais4
    fis1
    ais2
    c16\pp
    f1
    cis16
    gis2\mf
    e8
    g8
    c2
    g4
    g8
    d4\f
    ais2\mf
    c8
    gis2
    dis2\p
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c16
    d2
    d16
    d16
    dis16
    c4
    fis2
    d4
    e8
    c8
    c4
    d16
    a1
    d8
    fis4
    d2
    g8
    a4
    ais2
    ais16
    d4
    cis1
    b8
    cis4
    d8
    a1
    g16
    b1
    dis2
    gis8
    ais2
    d1\mf
    e2
    b16
    e8\mp
    f16
    a2
    g16\p
    b2
    cis4
    dis8
    fis2
    e1\mf
    b1
    d8
    ais4
    a1
    f1
    gis16
    ais1
    c4
    f16
    b16
    d16
    d1
    ais4\p
    gis4
    b4
    b1
    a2
    fis1
    cis16
    e4
    e2
    ais16
    dis8
    b8\mp
    ais8
    cis2
    gis8
    c1
    d16
    ais1
    cis1
    a1
    cis2
    ais16
    b16
    cis4\f
    fis16\mf
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
