%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   cis'!4-"RI9"
   f'!2.
   ais'!4-"R2"
   fis'!2
   cis'!4
   a'!2.
   c'!2.
   g'!4
   dis'!2.-"RI11"
   g'!2
   c'!2
   e'!4
   cis'!2.
   fis'!2-"P6"
   gis'!2.
   a'!2
   dis'!2.
   c'!2.
   g'!2.
   b'!2-"P11"
   cis'!2.
   d'!2.
   gis'!2.
   f'!4
   c'!4
   e'!2
   a'!4
   fis'!2
   ais'!4
   dis'!4
   g'!2.-"R11"
   dis'!2
   ais'!2
   fis'!2
   a'!4
   e'!2.
   c'!2.
   f'!4
   gis'!2.-"RI4"
   c'!2.
   f'!2.
   a'!2
   fis'!4
   b'!4
   dis'!4
   ais'!2
   g'!2-"P7"
   a'!2
   ais'!2
   e'!2
   cis'!2
   gis'!4
   c'!2.
   f'!2.
   d'!2.
   fis'!2-"P6"
   gis'!4
   a'!4
   dis'!2.
   c'!4
   g'!2-"R11"
   dis'!2.-"RI11"
   g'!4
   c'!2.
   e'!2
   cis'!4
   fis'!4
   ais'!2-"I10"
   gis'!2
   g'!4
   cis'!4
   e'!2
   a'!2
   f'!2.
   c'!4-"I0"
   ais'!2
   a'!2
   dis'!4
   fis'!2
   b'!4
   g'!4
   d'!2
   f'!2
   cis'!2.
   gis'!2
   e'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
