%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1
    g2
    f1\mp
    dis2
    d1
    dis1
    f16
    ais2\mp
    f16
    e2
    cis2
    ais1
    e4
    dis16
    a8
    cis4\mf
    c16
    f4
    cis4
    c16
    dis4\mf
    a8
    g16\f
    d2
    ais1
    dis8
    dis1
    fis1
    c16
    ais8\f
    c16
    a2
    b16
    fis4
    ais16\mf
    e1
    cis4
    ais16\pp
    gis2
    d16
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis16
    cis2
    dis16
    c2\mf
    e2
    d1
    e2
    b16
    gis4
    g2
    c1\mp
    f1
    a16\f
    gis8
    c8
    fis2
    cis1
    dis8
    b2\mf
    cis8
    ais8\mf
    a8
    ais2
    gis8
    e16\f
    cis16
    cis1
    g2
    dis2
    gis16
    cis8
    cis1\pp
    c8\f
    e4
    cis1
    f4
    d16
    dis1
    c1
    dis1
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis8
    d4
    a2
    fis2
    g8\pp
    b4
    gis8
    cis16
    gis16
    ais4\ff
    g1
    gis1
    ais4
    d8
    d16
    a8\pp
    cis4\mp
    f2
    f4
    e8\mp
    fis2\f
    f16
    gis8\pp
    e1
    ais2
    b1
    cis4
    e16
    f8
    b4
    gis8
    a8
    a2
    ais1
    f2
    g8\pp
    d4
    fis16
    c16
    ais16
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
