%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   g4-P 7
   fis2.
   gis2.-R 2
   f2.
   e4
   c2
   a2-RI 3
   c2.
   cis2.
   f2-RI 11
   gis4
   a2
   cis2
   e2
   dis4
   fis2.
   g4
   d2.
   ais2
   c4
   b2.-P 11
   ais2
   c4
   gis2-RI 2
   b2.
   c2
   e2
   g2.
   fis2.
   a2-RI 3
   c2.
   cis4
   f2.
   gis2.
   g2.
   ais4
   b2-P 11
   ais4
   c2
   gis2.
   dis2
   e2
   g4
   fis4
   a2-RI 3
   c2
   cis4
   f4
   gis2.
   g2
   ais4
   b2.-P 11
   ais4
   c2
   gis2.
   dis4
   e4
   g4
   fis4
   a4
   cis2.
   d2.
   f2-I 5
   fis2
   e2
   gis4
   cis2.
   c4
   a2
   ais4
   g2-R 1
   e2.-R 10
   cis4
   c4
   gis2
   f2.
   fis2.
   dis2
   d2.
   g4
   b4-P 11
   ais2
   c4
   gis4
   dis2.
   e4
   g2.
   fis2.
   a4
   cis2
   d2.
   f2-I 5
   fis2.
   e4
   gis4
   cis2
   c2
   a4
   ais4
   g4-R 1
   e2
   dis2.
   b4
   gis4
   a4
   fis4
   f2.-RI 11
   gis2.
   a2.
   cis2
   e2.
   dis2.
   fis2.
   g2.
   d2.
   ais2.
   c2.
   b2-R 5
   gis4
   g2
   dis4
   c2
   cis4
   ais2
   a2
   d4
   fis2
   e2
   f4-I 5
   fis4
   e2.
   gis2
   cis2
   c2
   a4-R 3
   fis4
   f2
   cis2.
   ais4
   b2
   gis2.
   g4
   c2
   e2.
   d4
   dis2-R 9
   c2
   b4
   g2
   e4
   f2.
   d2.
   cis2.
   fis4
   ais2.
   gis2.-I 8
   a2
   g4
   b2.
   e4
   dis2.
   c4
   cis2
   ais2
   fis2.
   f4-RI 11
   gis4
   a4
   cis2
   e2
   dis4
   fis4
   g4-R 1
   e4-P 4
   dis2.
   f4
   cis4
   gis2
   a4
   c4
   b2.-P 11
   ais2.
   c2.
   gis4
   dis2.
   e4
   g2
   fis2
   a2.
   cis4-RI 7
   e2
   f4
   a2
   c4
   b4
   d2.
   dis4
   ais2.
   fis4
   gis2
   g2.-P 7
   fis2.
   gis4
   e2.
   b2
   c4-P 0
   b2.
   cis2
   a2
   e4
   f2
   gis2.
   g2
   ais4
   d4
   dis2
   fis4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
