%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais2-"1"
    gis1-"2"
    fis8-"3"
    gis8\pp-"4"
    g8-"5"
    b1-"6"
    f8-"7"
    d1-"8"
    f1\mf-"9"
    ais16-"10"
    gis1\pp-"11"
    f1-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c2-"1"
    gis8-"2"
    f1-"3"
    fis1-"4"
    ais4\mf-"5"
    gis16-"6"
    g16-"7"
    b2-"8"
    ais4-"9"
    g16-"10"
    a16-"11"
    e4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis8-"1"
    b1-"2"
    cis8-"3"
    d16-"4"
    f1-"5"
    g8-"6"
    a16-"7"
    dis16-"8"
    b4\pp-"9"
    c1-"10"
    d16-"11"
    ais16-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
