%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g4
    gis8
    d16
    ais8
    dis8
    g4
    e1
    d16\mp
    fis8
    d16
    b8\mf
    gis4\p
    gis2
    a4
    cis1
    g4
    e1
    ais1\mp
    fis16
    a16\ff
    b1
    dis1
    fis1
    ais16\mf
    ais2
    d16
    ais8
    b1
    ais1
    cis8\f
    b1
    b1
    f8
    a2
    b1
    e2
    cis2
    a4
    dis1\pp
    fis8
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis1
    e1
    gis2\mf
    gis16\ff
    a8\f
    e4\f
    c16
    dis2
    e8
    e16
    cis16
    g16
    ais2
    g8\f
    c4
    dis16
    g16\pp
    c16
    d8
    f2
    a2
    cis8
    fis2
    c8\p
    ais1
    b16
    gis1\ff
    c8
    g1
    c1
    cis4
    gis1
    f8
    gis1
    g4
    dis8
    a1
    fis1
    e8
    ais8
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b2
    ais2
    ais1
    dis1
    d2
    cis16
    e16
    a4
    dis1
    g16
    fis8
    gis16
    gis4
    b16\mf
    fis4
    gis1
    a4\p
    fis4
    f4
    cis4\ff
    f8
    a2
    gis8
    c8
    a16
    dis16
    ais8
    a2\f
    f4\ff
    dis8\pp
    e8
    a8
    c1
    e16
    f4\pp
    c8
    g4
    fis2\p
    b2
    ais4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
