%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f1\f-"1"
    d16-"2"
    g1-"3"
    dis8-"4"
    a16-"5"
    c2-"6"
    fis1\f-"7"
    dis2-"8"
    cis4-"9"
    e8\p-"10"
    a1-"11"
    gis16-"12"
    c2-"13"
    cis1\f-"14"
    f2-"15"
    cis4-"16"
    d8-"17"
    a8\ff-"18"
    f16-"19"
    dis1-"20"
    cis16-"21"
    cis1-"22"
    fis1-"23"
    a2\ff-"24"
    dis2-"25"
    a1-"26"
    fis16-"27"
    dis16-"28"
    d16-"29"
    gis2-"30"
    e16-"31"
    ais2-"32"
    a16-"33"
    d2-"34"
    d4-"35"
    a2-"36"
    a4-"37"
    ais4\mp-"38"
    fis8\ff-"39"
    dis4-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"1"
    g1-"2"
    ais16-"3"
    f1-"4"
    fis16-"5"
    cis1\mp-"6"
    g2-"7"
    gis4-"8"
    d16-"9"
    dis4-"10"
    f4-"11"
    b4-"12"
    f4-"13"
    g4-"14"
    d1-"15"
    b16-"16"
    b16-"17"
    dis16-"18"
    fis8-"19"
    cis1-"20"
    dis1-"21"
    cis2-"22"
    b8-"23"
    ais8-"24"
    c8\f-"25"
    e1-"26"
    cis8-"27"
    cis16-"28"
    dis4-"29"
    d8-"30"
    fis8-"31"
    ais8-"32"
    gis4-"33"
    gis8\mp-"34"
    ais4-"35"
    e2-"36"
    b16-"37"
    a16-"38"
    f8-"39"
    gis4-"40"
    e16-"41"
    e16-"42"
    e1-"43"
    fis2-"44"
    g16-"45"
    ais4\p-"46"
    fis16-"47"
    gis16-"48"
    b1-"49"
    ais8-"50"
    g16-"51"
    gis4\f-"52"
    c16-"53"
    a8-"54"
    g16-"55"
    gis16-"56"
    f1-"57"
    d16\mf-"58"
    f2\f-"59"
    e4-"60"
    f2-"61"
    gis8-"62"
    cis16-"63"
    fis4-"64"
    ais16-"65"
    ais4-"66"
    a1-"67"
    c8-"68"
    e4-"69"
    cis16-"70"
    d8-"71"
    dis8-"72"
    e2-"73"
    f8\mf-"74"
    c2-"75"
    d2-"76"
    g8-"77"
    ais8-"78"
    ais4-"79"
    ais2-"80"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16-"1"
    cis8-"2"
    ais2\pp-"3"
    d1-"4"
    ais4-"5"
    c16-"6"
    e16-"7"
    e1-"8"
    f2-"9"
    dis8-"10"
    d1-"11"
    gis16-"12"
    c16-"13"
    e4-"14"
    ais8-"15"
    dis2-"16"
    c1-"17"
    gis8-"18"
    gis8-"19"
    g16\ff-"20"
    a8-"21"
    a1-"22"
    dis8-"23"
    c2-"24"
    f16-"25"
    ais4\ff-"26"
    e1-"27"
    c2\ff-"28"
    a4-"29"
    c16-"30"
    b16-"31"
    g2-"32"
    e4-"33"
    ais2\p-"34"
    e2\pp-"35"
    d16-"36"
    dis16-"37"
    a1-"38"
    cis1-"39"
    b8-"40"
    f16-"41"
    gis8-"42"
    c1-"43"
    dis2-"44"
    f16-"45"
    f8-"46"
    ais2-"47"
    c16-"48"
    b1-"49"
    b2-"50"
    dis8\ff-"51"
    gis2\pp-"52"
    dis16-"53"
    ais16-"54"
    f1-"55"
    d8-"56"
    dis16-"57"
    e1-"58"
    g2-"59"
    f8-"60"
    gis16-"61"
    fis16-"62"
    d16-"63"
    e2-"64"
    f1-"65"
    c8-"66"
    cis2-"67"
    g1-"68"
    f8-"69"
    c16-"70"
    c2-"71"
    c2-"72"
    fis2-"73"
    ais2-"74"
    g2-"75"
    b2-"76"
    ais8-"77"
    cis4-"78"
    gis1-"79"
    gis2-"80"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
