%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis1-"1"
    ais16-"2"
    f2-"3"
    g1-"4"
    gis8-"5"
    g4-"6"
    f16-"7"
    gis4\mf-"8"
    e8-"9"
    ais8-"10"
    cis2-"11"
    a8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a8-"1"
    a16-"2"
    c8-"3"
    d8-"4"
    cis4\pp-"5"
    gis1\ff-"6"
    e1-"7"
    ais16-"8"
    d1-"9"
    cis1-"10"
    gis1-"11"
    b8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a2-"1"
    b1-"2"
    ais2\ff-"3"
    gis16-"4"
    d2-"5"
    g8-"6"
    dis8-"7"
    ais16-"8"
    fis8-"9"
    g16-"10"
    d2-"11"
    d2-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
