%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d1-"3"
    d1-"3"
    d1-"5"
    dis1-"6"
    d1-"5"
    dis1-"6"
    dis1-"4"
    f1\mp-"1"
    d1-"5"
    dis1-"6"
    f1\mp-"1"
    f1\mp-"1"
    d1-"3"
    f1\mp-"1"
    dis2-"7"
    dis2-"7"
    d1-"5"
    f1\mp-"2"
    dis2-"7"
    f1\mp-"1"

\midi{}
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e2-"3"
    e2-"3"
    e2-"5"
    d1-"6"
    e2-"5"
    d1-"6"
    d1-"4"
    dis16-"1"
    e2-"5"
    d1-"6"
    dis16-"1"
    dis16-"1"
    e2-"3"
    dis16-"1"
    c2\mf-"7"
    c2\mf-"7"
    e2-"5"
    dis16-"2"
    c2\mf-"7"
    dis16-"1"

\midi{}
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g8\pp-"3"
    g8\pp-"3"
    g8\pp-"5"
    b4-"6"
    g8\pp-"5"
    b4-"6"
    b4-"4"
    a2-"1"
    g8\pp-"5"
    b4-"6"
    a2-"1"
    a2-"1"
    g8\pp-"3"
    a2-"1"
    fis2-"7"
    fis2-"7"
    g8\pp-"5"
    a2-"2"
    fis2-"7"
    a2-"1"

\midi{}
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
