%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e16-"1"
    cis4\mp-"2"
    ais1\f-"3"
    dis2-"4"
    ais1-"5"
    fis8-"6"
    b8-"7"
    f8-"8"
    a16-"9"
    g4\f-"10"
    e8-"11"
    c16-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis8-"1"
    f2-"2"
    g8\p-"3"
    e2-"4"
    g4-"5"
    e2-"6"
    e8\mf-"7"
    b16-"8"
    cis16-"9"
    f1-"10"
    gis4-"11"
    d4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis4-"1"
    g4\mf-"2"
    dis8-"3"
    e8-"4"
    e2\mf-"5"
    b1-"6"
    fis2\pp-"7"
    f1-"8"
    ais16-"9"
    gis8\mf-"10"
    fis8-"11"
    ais16-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
