%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   c'!2-"RI5"
   e'!4
   ais'!4
   fis'!2.
   b'!4-"R6"
   g'!2
   cis'!2.
   f'!2-"I5"
   d'!2
   dis'!2.
   cis'!2
   g'!4
   gis'!2.
   a'!2.-"R4"
   f'!2
   b'!4-"R6"
   g'!2
   cis'!4
   f'!2.-"R0"
   cis'!4
   g'!4
   b'!2.
   fis'!2-"RI11"
   ais'!4
   e'!2.
   c'!2
   f'!2
   dis'!2
   d'!4-"I2"
   b'!2-"I11"
   gis'!4
   a'!4
   g'!2.
   cis'!2-"P1"
   e'!4
   dis'!2
   f'!4-"RI10"
   a'!4
   dis'!2
   b'!2.
   e'!2.
   d'!4
   cis'!2.-"P1"
   e'!2.
   dis'!2-"P3"
   fis'!4-"RI11"
   ais'!2
   e'!2
   c'!2
   f'!2
   dis'!2
   d'!2
   cis'!4-"RI6"
   f'!4
   b'!2
   g'!2
   c'!2
   ais'!4
   a'!2-"P9"
   c'!2.
   b'!2-"P11"
   d'!4
   cis'!4
   dis'!2.
   a'!2
   gis'!4-"R3"
   e'!2.
   ais'!2.
   d'!2.
   a'!4
   b'!2-"I11"
   gis'!4
   a'!4
   g'!4
   cis'!2.-"RI6"
   f'!4
   b'!2
   g'!2.
   c'!2
   ais'!4
   a'!2.
   gis'!4
   d'!2
   e'!2.
   dis'!2
   fis'!2.-"I6"
   dis'!2.
   e'!2.
   d'!2.
   gis'!2
   a'!2
   ais'!4
   c'!2
   g'!2.
   b'!2
   f'!2
   cis'!4-"RI6"
   f'!4
   b'!2.
   g'!2.
   c'!2
   ais'!4
   a'!2
   gis'!2-"R3"
   e'!2.
   ais'!4
   d'!2.
   a'!2.
   b'!4
   c'!2.-"P0"
   dis'!2.
   d'!2
   e'!2.
   ais'!2
   a'!4
   gis'!2
   fis'!2
   b'!2
   g'!4
   cis'!2.
   f'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
