%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   c'!2-"R1"
   ais'!4
   d'!2.
   g'!4
   gis'!2.
   fis'!2.
   f'!4-"P5"
   gis'!2
   cis'!2
   dis'!4
   g'!2-"RI6"
   a'!2.
   f'!4
   c'!2
   b'!2.-"RI10"
   cis'!2.
   a'!2.
   e'!2.
   dis'!2-"R4"
   cis'!2.
   f'!2
   ais'!2.
   b'!4
   a'!4
   gis'!4-"I8"
   f'!2
   c'!4
   ais'!2-"R11"
   gis'!2.
   c'!2
   f'!4
   fis'!2.
   e'!4
   dis'!4-"P3"
   fis'!2
   b'!2.
   cis'!4
   f'!4
   g'!2
   gis'!2.
   ais'!2.
   a'!2
   e'!2-"R5"
   d'!2.
   fis'!2.
   b'!2
   c'!2
   ais'!4
   a'!4
   g'!4
   dis'!4-"I3"
   c'!4-"R1"
   ais'!2.
   d'!2
   g'!2.
   gis'!2.
   fis'!4
   f'!2.
   dis'!4-"RI2"
   f'!2
   cis'!4
   gis'!2
   g'!2.
   a'!2
   ais'!4
   c'!2.
   e'!2.
   fis'!2
   b'!2
   d'!2.-"I2"
   b'!4
   fis'!2.
   e'!2.-"P4"
   g'!4
   c'!2
   d'!2
   fis'!4
   gis'!2.
   a'!4
   b'!2.
   ais'!4-"P10"
   cis'!4
   fis'!2.
   gis'!2.-"I8"
   f'!2.
   c'!4
   ais'!2
   fis'!2.
   e'!2.
   dis'!2
   cis'!2
   d'!2
   g'!2
   b'!4
   a'!2.-"RI8"
   b'!4
   g'!4
   d'!4
   cis'!2-"I1"
   ais'!4
   f'!2.
   dis'!4
   b'!2
   a'!2.-"I9"
   fis'!2.
   cis'!4
   b'!4-"R0"
   a'!2.
   cis'!2.
   fis'!2.
   g'!2.
   f'!2
   e'!4
   d'!2-"P2"
   f'!4-"P5"
   gis'!2.
   cis'!2.
   dis'!2
   g'!4
   a'!2
   ais'!2
   c'!2-"R1"
   ais'!2
   d'!4
   g'!2.
   gis'!4
   fis'!2
   f'!4
   dis'!2
   b'!2.
   a'!2.
   e'!2
   cis'!4-"R2"
   b'!2.
   dis'!4
   gis'!2
   a'!2.
   g'!2.
   fis'!2
   e'!2.
   c'!4
   ais'!2
   f'!2.-"I5"
   d'!4
   a'!2.
   g'!2.
   dis'!4
   cis'!2.
   c'!2-"RI11"
   d'!2
   ais'!2.
   f'!2.-"I5"
   d'!4
   a'!2.-"RI8"
   b'!2.
   g'!4
   d'!2
   cis'!2
   dis'!2-"R4"
   cis'!2
   f'!2
   ais'!2.
   b'!2
   a'!2.
   gis'!2.
   fis'!2.
   d'!2.
   c'!4-"I0"
   a'!4
   e'!4
   d'!2
   ais'!4
   gis'!2.
   g'!2.
   f'!4
   fis'!2
   b'!2.
   dis'!2.
   cis'!2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
