%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis4\mf-"1"
    dis8-"2"
    fis2\mp-"3"
    e2-"4"
    ais2-"5"
    gis16-"6"
    gis2-"7"
    gis4-"8"
    a4-"9"
    d2-"10"
    cis1-"11"
    fis16\mp-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e16-"1"
    cis4-"2"
    f16-"3"
    f2-"4"
    f4-"5"
    b2-"6"
    c8\f-"7"
    fis1-"8"
    a16-"9"
    b8-"10"
    a16\f-"11"
    f16-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis4-"1"
    e4\mp-"2"
    e2-"3"
    dis4-"4"
    fis8\p-"5"
    g16-"6"
    a2-"7"
    fis16-"8"
    gis4-"9"
    gis16-"10"
    dis8-"11"
    dis2-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
