%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16\mp-"10"
    ais2-"3"
    fis2\mp-"5"
    ais2-"3"
    ais2-"3"
    fis2\mp-"2"
    gis16-"8"
    dis8-"6"
    fis2\mp-"5"
    ais2-"12"
    ais2-"3"
    fis2\mp-"5"
    fis2\mp-"4"
    ais2-"12"
    d2-"1"
    ais2-"9"
    fis2\mp-"11"
    fis16\mp-"10"
    gis4-"7"
    ais2-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f16-"10"
    f4-"3"
    f16-"5"
    f4-"3"
    f4-"3"
    f16-"2"
    b2-"8"
    cis4-"6"
    f16-"5"
    f4-"12"
    f4-"3"
    f16-"5"
    f16-"4"
    f4-"12"
    b8-"1"
    f4-"9"
    f16-"11"
    f16-"10"
    fis1-"7"
    f4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis2-"10"
    fis8\p-"3"
    e2-"5"
    fis8\p-"3"
    fis8\p-"3"
    e2-"2"
    g16-"8"
    e4\mp-"6"
    e2-"5"
    fis8\p-"12"
    fis8\p-"3"
    e2-"5"
    e2-"4"
    fis8\p-"12"
    gis16-"1"
    fis8\p-"9"
    e2-"11"
    dis2-"10"
    fis16-"7"
    fis8\p-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
