%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a8-"1"
    dis1-"2"
    f4-"3"
    fis2-"4"
    f16-"5"
    gis2-"6"
    c4-"7"
    ais4-"8"
    fis2-"9"
    fis16-"10"
    f4-"11"
    dis4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis2-"1"
    b8-"2"
    e8-"3"
    dis2-"4"
    a8\ff-"5"
    dis8-"6"
    fis16-"7"
    gis1\pp-"8"
    a16\mp-"9"
    gis4-"10"
    cis1-"11"
    f2-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a4-"1"
    b4-"2"
    e1\pp-"3"
    c4-"4"
    f2-"5"
    gis4-"6"
    b2-"7"
    b2\ff-"8"
    b16\ff-"9"
    ais2\p-"10"
    cis4\pp-"11"
    f8-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
