%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1-"1"
    dis1-"2"
    b16-"3"
    a2-"4"
    ais1-"5"
    gis8-"6"
    g4\mf-"7"
    c8-"8"
    e1-"9"
    fis1-"10"
    b1\mf-"11"
    dis2-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"1"
    b16-"2"
    cis1-"3"
    a1\mp-"4"
    dis8-"5"
    ais2-"6"
    cis4-"7"
    c8-"8"
    fis4-"9"
    g1-"10"
    dis2-"11"
    f8\pp-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    c16-"1"
    d2-"2"
    d16-"3"
    d16-"4"
    dis16-"5"
    c4-"6"
    fis2-"7"
    d4-"8"
    e8-"9"
    c8-"10"
    c4-"11"
    d16-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
