%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16
    fis1
    dis4
    g4
    b2
    cis4
    fis2\mp
    cis2\f
    fis1
    f8
    dis2
    dis2
    a2
    a4\pp
    gis1
    g2
    f2\p
    f4
    c2
    ais2
    g4
    dis1
    e1
    cis8
    d1
    d2
    d2
    a16
    ais2
    e4\ff
    a16
    e4
    cis4
    a4
    gis8
    g1
    cis2\f
    a4\ff
    b2\mp
    dis8
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a2
    b1\mf
    a4
    g2
    fis2
    fis1
    fis4
    f4
    dis1
    d4
    fis4
    a4
    d8\mf
    fis1
    e8\p
    gis2
    d16
    g16\ff
    b8
    f2
    a4
    a2
    gis4
    ais4\f
    g8
    dis4
    dis8
    g2
    cis2
    e2\f
    c4
    fis1
    g8\ff
    fis4
    a16
    d1
    gis1
    b2
    dis16\f
    fis8
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f1
    c1
    cis8
    fis16
    e4
    b16
    a4
    c8
    e1
    dis16
    c2
    ais16
    a4
    fis16
    ais2\pp
    d8
    dis1
    b4
    gis4\f
    cis16
    cis16
    gis4
    b4
    c4
    d8
    cis16
    a4
    e1
    ais1
    f16
    d16
    fis16
    c2\mf
    cis1
    e16
    cis8
    a4
    cis2
    a1
    e4
    cis4\f
    cis2
    b4
    dis16
    gis4
    gis2
    cis1
    a1
    c8
    g8
    ais1
    e1
    gis2\ff
    b16\p
    gis8
    cis16
    b1
    a16
    d2
    e4
    c8
    g4
    b2
    g4\pp
    f16
    c1
    e8
    ais8
    cis16\mf
    d4
    d8
    g8
    d8
    f2
    f8
    cis2
    gis2
    g16
    dis2
    ais16
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
