%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"1"
    gis1\p-"2"
    ais8-"3"
    gis8-"4"
    a8-"5"
    gis8-"6"
    cis1\p-"7"
    g8-"8"
    fis8-"9"
    c2-"10"
    ais1-"11"
    dis8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b4-"1"
    fis2\p-"2"
    ais16-"3"
    g16\pp-"4"
    dis1-"5"
    dis8-"6"
    gis1-"7"
    dis2-"8"
    gis8\mp-"9"
    c4-"10"
    c2\pp-"11"
    ais8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e1-"1"
    a16-"2"
    fis4-"3"
    dis2-"4"
    cis1-"5"
    a2-"6"
    g4-"7"
    g16-"8"
    ais8-"9"
    c1-"10"
    cis1-"11"
    g1-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
