%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e16-"3"
    c8-"2"
    d8\mp-"1"
    e16-"3"
    b1\p-"5"
    b1\p-"5"
    e4-"7"
    c8-"2"
    d8\mp-"1"
    e16-"3"
    c8-"2"
    d8\mp-"1"
    e16-"3"
    e4-"7"
    e16-"3"
    b1\p-"5"
    e16-"3"
    e4-"7"
    b1\p-"5"
    d8\mp-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d'2-"3"
    g8\pp-"2"
    g'4-"1"
    d'2-"3"
    c'1-"5"
    c'1-"5"
    g2-"7"
    g8\pp-"2"
    g'4-"1"
    d'2-"3"
    g8\pp-"2"
    g'4-"1"
    d'2-"3"
    g2-"7"
    d'2-"3"
    c'1-"5"
    d'2-"3"
    g2-"7"
    c'1-"5"
    g'4-"4"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f2-"3"
    g'2-"2"
    f'16-"1"
    f2-"3"
    c'4-"5"
    c'4-"5"
    e8-"7"
    g'2-"2"
    f'16-"1"
    f2-"3"
    g'2-"2"
    f'16-"1"
    f2-"3"
    e8-"7"
    f2-"3"
    c'4-"5"
    f2-"3"
    e8-"7"
    c'4-"5"
    f'16-"4"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
