%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"1"
    gis1\p-"2"
    ais8-"3"
    gis8-"4"
    a8-"5"
    gis8-"6"
    cis1\p-"7"
    g8-"8"
    fis8-"9"
    c2-"10"
    ais1-"11"
    dis8-"12"
    cis4-"13"
    cis4\ff-"14"
    cis1-"15"
    ais2-"16"
    dis8-"17"
    g8-"18"
    gis16\mp-"19"
    cis2-"20"
    dis1-"21"
    b1-"22"
    fis4-"23"
    d8-"24"
    a16-"25"
    e8\mp-"26"
    g8\f-"27"
    e2-"28"
    ais8-"29"
    gis2-"30"
    dis16-"31"
    c16\ff-"32"
    b4\mp-"33"
    d4-"34"
    e8-"35"
    e2-"36"
    f1-"37"
    fis4-"38"
    ais2-"39"
    e8-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b4-"1"
    fis2\p-"2"
    ais16-"3"
    g16\pp-"4"
    dis1-"5"
    dis8-"6"
    gis1-"7"
    dis2-"8"
    gis8\mp-"9"
    c4-"10"
    c2\pp-"11"
    ais8-"12"
    g2\ff-"13"
    a1-"14"
    c4\pp-"15"
    g2-"16"
    cis2-"17"
    b4-"18"
    cis8-"19"
    d4-"20"
    f4-"21"
    cis8-"22"
    e4-"23"
    f8-"24"
    f2\f-"25"
    fis4-"26"
    f2-"27"
    b1-"28"
    f2-"29"
    g4-"30"
    ais8-"31"
    fis8-"32"
    dis16-"33"
    d8-"34"
    g2\ff-"35"
    d1-"36"
    b16-"37"
    fis2-"38"
    c16-"39"
    f2-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e1-"1"
    a16-"2"
    fis4-"3"
    dis2-"4"
    cis1-"5"
    a2-"6"
    g4-"7"
    g16-"8"
    ais8-"9"
    c1-"10"
    cis1-"11"
    g1-"12"
    g16-"13"
    ais1\pp-"14"
    g8-"15"
    dis2-"16"
    e8\f-"17"
    b1-"18"
    cis1\ff-"19"
    d1\mp-"20"
    ais8-"21"
    fis4-"22"
    f2-"23"
    fis2-"24"
    gis8\ff-"25"
    dis1-"26"
    cis2-"27"
    cis1-"28"
    d4-"29"
    d4\p-"30"
    a4\ff-"31"
    g4-"32"
    f2\mp-"33"
    b4-"34"
    b4-"35"
    fis4-"36"
    g8-"37"
    dis8-"38"
    a2-"39"
    cis8-"40"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
