%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   dis'!2.-"P3"
   fis'!2.
   b'!2
   cis'!2.
   f'!2.
   g'!2
   gis'!4
   ais'!4
   a'!2
   e'!4-"P4"
   g'!4
   c'!2
   d'!4
   fis'!2.
   gis'!4
   a'!2-"R10"
   g'!2.
   b'!4
   e'!4
   f'!2
   dis'!2.
   d'!2.
   c'!2
   gis'!2.
   fis'!4
   cis'!4
   ais'!2.-"R11"
   gis'!4
   c'!2
   f'!2.
   fis'!2
   e'!2.
   dis'!4
   cis'!2
   a'!2-"R10"
   g'!2
   b'!2
   e'!4
   f'!2-"RI4"
   g'!4
   dis'!2.
   ais'!2.-"R11"
   gis'!4
   c'!4-"RI11"
   d'!2
   ais'!4
   f'!2.
   e'!2.
   fis'!2.
   g'!2
   a'!4
   cis'!2.
   dis'!4
   gis'!2.-"P8"
   b'!2.
   e'!4
   fis'!2
   ais'!2
   c'!2
   cis'!4
   dis'!4
   d'!4
   a'!2
   f'!4-"RI4"
   g'!2.
   dis'!2
   ais'!2.
   a'!4
   b'!2
   c'!2-"RI11"
   d'!2-"RI1"
   e'!2.
   c'!4
   g'!4
   fis'!2.-"RI5"
   gis'!2
   e'!2.
   b'!2.
   ais'!2.
   c'!2
   cis'!2.
   dis'!2.
   g'!2
   a'!4
   d'!4-"RI1"
   e'!2
   c'!4
   g'!2.
   fis'!4
   gis'!2
   a'!4
   b'!2.
   dis'!2.
   f'!2.
   ais'!2
   cis'!2-"I1"
   ais'!2.
   f'!4
   dis'!2.
   b'!2
   a'!4
   gis'!4
   fis'!2.
   g'!2
   c'!2.-"R1"
   ais'!2
   d'!2.
   g'!4
   gis'!4
   fis'!4
   f'!2.
   dis'!2.
   b'!2.
   a'!2.
   e'!2-"RI3"
   fis'!4
   d'!4-"RI1"
   e'!2.
   c'!2
   g'!2
   fis'!4
   gis'!4
   a'!2-"R10"
   g'!4
   b'!2.
   e'!2
   f'!2.
   dis'!4
   d'!2
   c'!4-"R1"
   ais'!2
   d'!2.
   g'!2.-"I7"
   e'!2.
   b'!4
   a'!2.
   f'!2.
   dis'!4
   d'!2-"RI1"
   e'!2
   c'!2
   g'!2
   fis'!2-"RI5"
   gis'!4
   e'!4
   b'!2.
   ais'!2
   c'!2.-"R1"
   ais'!4
   d'!2
   g'!2
   gis'!4
   fis'!4
   f'!4
   dis'!2-"I3"
   c'!2
   g'!2
   f'!4
   cis'!4
   b'!2
   ais'!2.
   gis'!2.
   a'!2
   d'!4-"RI1"
   e'!4
   c'!2.
   g'!2
   fis'!2.
   gis'!4
   a'!2-"R10"
   g'!2
   b'!2
   e'!4
   f'!2.
   dis'!4
   d'!2
   c'!2-"RI11"
   d'!4
   ais'!4
   f'!4
   e'!2.
   fis'!4
   g'!4
   a'!2.
   cis'!2.
   dis'!2.
   gis'!2.
   b'!2-"I11"
   gis'!2.
   dis'!4
   cis'!2
   a'!4
   g'!2
   fis'!4
   e'!4
   f'!2.
   ais'!2
   d'!2-"P2"
   f'!2
   ais'!2.
   c'!2
   e'!2.
   fis'!2
   g'!2
   a'!2.
   gis'!4
   dis'!2.
   b'!2
   cis'!2.-"RI0"
   dis'!2.
   b'!2
   fis'!4
   f'!2.
   g'!2
   gis'!4
   ais'!2.
   d'!2-"R3"
   c'!4
   e'!4
   a'!2.
   ais'!2.
   gis'!4
   g'!2
   f'!2.-"RI4"
   g'!2
   dis'!4
   ais'!4
   a'!4
   b'!2.
   c'!2.
   d'!2.-"R3"
   c'!4-"P0"
   dis'!4
   gis'!4
   ais'!2.
   d'!2
   e'!2
   f'!2.
   g'!4
   fis'!4
   cis'!2.
   a'!2
   b'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
