%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   g2.-I 7
   c2.
   ais2.
   dis2.
   a2
   b2.-RI 5
   d4
   fis4
   c2
   dis2.
   e2
   a2
   g2
   cis2.
   gis2
   ais2
   f4-RI 11
   gis2.
   c2.
   fis4
   a2.
   ais2.
   dis2.
   cis2.
   g4
   d2.-P 2
   a2
   b2
   fis4-I 6
   b4
   a2.
   d2.
   gis2.
   ais2.-I 10
   dis2.
   cis4
   fis2
   c4
   d2
   a4
   gis2-I 8
   cis4
   b2.
   e4-R 10
   cis4
   a4
   dis2
   c2
   b4-P 11
   fis4
   gis4
   dis2.
   a2-P 9
   e4
   fis2
   cis2.
   g4-I 7
   c2
   ais4
   dis2.
   a2.
   b4-P 11
   fis2-RI 0
   a4
   cis2.
   g2-I 7
   c2
   ais4
   dis2.
   a2.
   b2
   fis2.
   f2
   d2
   gis2.-RI 2
   b4
   dis2
   a4
   c4
   cis2
   fis2
   e2.
   ais4
   f2.
   g4
   d4-R 8
   b4
   g2.
   cis2
   ais2
   a2
   e4
   fis2-RI 0
   a4
   cis2.
   g2.
   ais2.
   b4
   e2
   d2
   gis4
   dis2.-R 9
   c2
   gis4
   d2
   b2
   ais2
   f2
   g2.
   cis2
   fis4-RI 0
   a2.
   cis2.
   g2.
   ais4
   b2
   e4
   d2.
   gis2-RI 2
   b2-I 11
   e4
   d2
   g2.-R 1
   e2
   c2.
   fis4
   dis2.
   d2
   a2.
   b2
   f4
   ais2-I 10
   dis4
   cis4
   fis2.
   c2
   d2.
   a2.
   gis2.
   f2
   b2.-R 5
   gis2.
   e2.
   ais2.
   g2
   fis4
   cis2
   dis2.-RI 9
   fis2.
   ais2.
   e4-R 10
   cis4
   a2
   dis2.
   c2.
   b4
   fis2.
   gis2
   d4
   g2.
   f2
   ais2.-I 10
   dis2
   cis2
   fis2
   c2
   d4
   a2
   gis2-I 8
   cis2
   b2.-RI 5
   d2.
   fis2
   c4
   dis4
   e2
   a4
   g2.
   cis2-P 1
   gis4
   ais2.
   f4
   b4
   a2
   d4-R 8
   b2
   g4
   cis2.
   ais2
   a4
   e4
   fis2
   c2.
   f2.
   dis4
   gis4-I 8
   cis2.
   b4
   e2.
   ais2.
   c2.
   g4
   fis4-P 6
   cis2
   dis4
   ais2
   e4
   d4
   g2-R 1
   e4
   c4
   fis2
   dis2
   d2.
   a2.
   b4-RI 5
   d2
   fis2.
   c4
   dis2
   e2
   a2.
   g2
   cis2
   gis4
   ais2
   f2.-I 5
   ais4
   gis4
   cis2.
   g2.
   a2
   e2.
   dis4
   c4
   fis2-I 6
   b2.
   a4
   d2.
   gis2
   ais2
   f4
   e2.-R 10
   cis2.
   a2
   dis2.
   c2.
   b2
   fis4
   gis4-I 8
   cis4
   b2.
   e2
   ais4
   c2
   g4-R 1
   e4
   c2
   fis4
   dis4
   d4
   a2.
   b2.-R 5
   gis2
   e4
   ais2
   g2.
   fis4
   cis2
   dis2.
   a2.
   d2.
   c4
   f2-RI 11
   gis2
   c2.
   fis2.-RI 0
   a2.
   cis4
   g2.
   ais4
   b4-RI 5
   d2.
   fis2-RI 0
   a4-RI 3
   c2
   e2.
   ais4
   cis4
   d4
   g4
   f4
   b2.-I 11
   e2
   d4
   g4-P 7
   d4
   e4
   b2-R 5
   gis4
   e2.
   ais2.
   g4
   fis4
   cis2.-RI 7
   e4
   gis4
   d2
   f2
   fis2.-P 6
   cis2.
   dis2.
   ais4
   e4
   d2.
   g4
   gis4
   b2.-P 11
   fis2.
   gis2
   dis2.
   a2.-P 9
   e2.
   fis2-P 6
   cis2
   dis2.
   ais2.
   e4
   d2.
   g4
   gis2.
   b4-I 11
   e2.
   d2.
   g2.
   cis4
   dis4
   ais4
   a2.
   fis4-P 6
   cis2
   dis2
   ais2
   e2.
   d2.
   g2.
   gis4
   b2.
   f2.
   a2.
   c2.-P 0
   g4
   a2
   e4
   ais2
   gis4
   cis4
   d4
   f2.
   b2
   dis2.
   fis2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
