%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   f'!4-"I5"
   c'!4
   b'!2.
   e'!4-"RI2"
   c'!4
   g'!4
   ais'!4
   fis'!2
   dis'!2.
   f'!2
   b'!2
   cis'!2.
   gis'!2
   a'!4
   d'!2-"R4"
   fis'!2.-"I6"
   cis'!4
   c'!4-"P0"
   f'!2.
   fis'!2.
   cis'!2.
   dis'!4
   a'!2
   b'!2.
   gis'!2
   e'!2.-"R6"
   gis'!4
   cis'!2.
   ais'!2-"I10"
   f'!2.-"I5"
   c'!2
   b'!2.
   e'!2.
   d'!4
   gis'!4
   fis'!2.-"R8"
   ais'!2
   dis'!2
   c'!4
   e'!4
   g'!2
   f'!2.-"I5"
   c'!2.
   b'!2
   e'!2
   d'!4
   gis'!4
   fis'!4
   a'!2.
   cis'!4-"I1"
   gis'!2
   g'!4
   c'!2
   ais'!2
   e'!4
   d'!2.
   f'!2.
   a'!2.
   fis'!4
   b'!4
   dis'!4-"R5"
   g'!4
   c'!2.
   a'!4
   cis'!2
   e'!2.
   d'!2.
   gis'!2.-"I8"
   dis'!2.
   d'!2.
   g'!4
   f'!2
   b'!2
   a'!4
   c'!4
   e'!2.
   cis'!2.
   fis'!4-"R8"
   ais'!4
   dis'!2
   c'!2
   e'!4
   g'!2.
   f'!2.
   b'!2
   a'!4
   d'!2.
   cis'!2.
   gis'!4-"R10"
   c'!2
   f'!2.
   d'!2.
   fis'!4
   a'!2.
   g'!4-"P7"
   c'!2
   cis'!2
   gis'!2
   ais'!2-"RI8"
   fis'!2
   cis'!4
   e'!2
   c'!2.
   a'!2.
   b'!4-"RI9"
   g'!2.
   d'!2.
   f'!2.
   cis'!4
   ais'!4
   c'!4
   fis'!2
   gis'!2
   dis'!2.
   e'!2.-"P4"
   a'!2.
   ais'!2.
   f'!2.
   g'!4-"RI5"
   dis'!2
   ais'!2.
   cis'!4
   a'!2
   fis'!2.
   gis'!2-"I8"
   dis'!2
   d'!2.
   g'!2.
   f'!4
   b'!4
   a'!2.
   c'!4
   e'!4
   cis'!2-"RI11"
   a'!2
   e'!2
   g'!4
   dis'!4
   c'!2.
   d'!2.
   gis'!4-"I8"
   dis'!2
   d'!2-"P2"
   g'!2
   gis'!4
   dis'!2
   f'!2.
   b'!2
   cis'!2.
   ais'!4
   fis'!2
   a'!4
   e'!4-"P4"
   a'!2.
   ais'!4
   f'!2
   g'!2
   cis'!2.-"P1"
   fis'!2.
   g'!4
   d'!2
   e'!4
   ais'!2
   c'!2
   a'!2-"RI7"
   f'!2
   c'!2.-"I0"
   g'!2.
   fis'!2.
   b'!2
   a'!2.
   dis'!4
   cis'!2
   e'!2
   gis'!2.
   f'!2.
   ais'!4
   d'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
