%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   d'2-"P2"
   fis'2.
   c'2
   a'4
   gis'2.
   e'4
   b'4
   f'2.
   g'4-"R11"
   ais'4
   c'2.
   e'4
   d'4
   gis'4
   cis'4
   f'2.-"I5"
   cis'2.
   g'4
   ais'2.
   b'2.
   dis'2
   gis'2
   d'2
   c'2.
   e'2.
   fis'2-"RI2"
   dis'2.
   cis'2.
   a'2.
   b'2
   f'2
   c'4
   gis'2.
   g'2.-"I7"
   dis'2.-"RI11"
   c'2-"RI8"
   a'2
   g'2-"I7"
   dis'2.
   a'4
   c'4
   cis'2.
   f'2.
   ais'2.
   e'4-"R8"
   g'4
   a'2
   cis'2
   b'4
   f'2-"R9"
   gis'4-"R0"
   b'2.
   cis'2.
   f'2
   dis'2.
   a'2.
   d'4
   fis'2
   g'4
   ais'4-"I10"
   fis'2
   c'4
   dis'2-"R7"
   fis'4
   gis'2.
   c'2
   ais'4
   e'2-"I4"
   c'4
   fis'2.
   a'2
   ais'2.
   d'2
   g'2
   cis'2.
   b'2
   dis'2.
   f'2-"R9"
   gis'2
   ais'2
   d'2.
   c'2
   fis'2.
   b'2.-"R3"
   d'4
   e'4
   gis'4
   fis'2.
   c'2
   f'2
   a'2.
   ais'2-"R2"
   cis'2
   dis'4-"RI11"
   c'2.
   ais'4
   fis'2
   gis'4
   d'4-"R6"
   f'4
   g'2-"P7"
   b'2
   f'2.
   d'2.
   cis'2.
   a'2
   e'4
   ais'4
   c'4
   gis'2.
   fis'2.-"RI2"
   dis'2
   cis'4
   a'4
   b'2
   f'4-"P5"
   a'2
   dis'2
   c'4
   b'2.
   g'4
   d'2.
   gis'2.
   ais'2
   fis'2
   e'2.-"I4"
   c'4
   fis'2.
   a'2
   ais'2-"RI6"
   g'2
   f'4
   cis'4
   dis'2.
   a'2.
   e'2
   c'2.
   b'2.-"I11"
   g'2-"P7"
   b'2.
   f'2.
   d'2.
   cis'4
   a'2
   e'2.
   ais'2.
   c'4
   gis'2-"I8"
   e'2.
   ais'4
   cis'4
   d'4
   fis'4
   b'2.
   f'2
   dis'2-"RI11"
   c'4
   ais'2
   fis'2
   gis'2.
   d'2
   a'4
   f'2.
   e'2
   cis'2.
   g'2.
   b'2.-"RI7"
   gis'4
   fis'2.
   d'4
   e'4
   ais'2.
   f'4
   cis'2-"RI9"
   ais'2.
   gis'2
   e'4
   fis'4
   c'2-"RI8"
   a'2.
   g'4
   dis'2-"P3"
   g'2.
   cis'2.
   ais'4
   a'2
   f'2.
   c'2
   fis'2.-"R10"
   a'4
   b'2.
   dis'4
   cis'2
   g'4
   c'2-"P0"
   e'2
   ais'4
   g'4
   fis'2.
   d'4
   a'2
   dis'4
   f'2
   cis'2.
   b'2
   gis'2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
