%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   gis'!4-"RI9"
   c'!4
   d'!2-"RI3"
   fis'!4
   gis'!4
   f'!4
   cis'!4
   b'!4
   g'!2.
   c'!2.-"P0"
   b'!4-"R10"
   g'!2.
   f'!2
   gis'!2
   c'!2
   d'!2
   fis'!2.
   cis'!4-"I1"
   d'!4
   gis'!2
   g'!2.
   ais'!2
   f'!4
   a'!4
   b'!4-"P11"
   ais'!2
   e'!2
   f'!2
   d'!4
   g'!4
   dis'!2
   cis'!4
   a'!4
   fis'!4-"RI7"
   ais'!2
   c'!2
   a'!2
   f'!4
   dis'!4
   b'!2-"I11"
   c'!2.
   fis'!2.
   f'!4
   gis'!4
   dis'!2-"I3"
   e'!4-"R3"
   c'!2.-"P0"
   b'!2
   f'!4
   fis'!4
   dis'!4
   gis'!4-"R7"
   e'!2
   d'!4
   f'!2
   a'!2.
   b'!2.
   dis'!2.
   ais'!2.-"P10"
   a'!2.
   dis'!2
   e'!4
   cis'!2.-"I1"
   d'!4
   gis'!4
   g'!2
   ais'!4
   f'!2.
   a'!2.
   b'!4
   dis'!2.
   fis'!2.-"RI7"
   ais'!2.
   c'!2
   a'!2
   f'!2.
   dis'!2
   b'!2.
   e'!4
   cis'!2.-"I1"
   d'!4
   gis'!2
   g'!2.
   ais'!2
   f'!2.
   a'!2.
   b'!4
   dis'!4
   fis'!4
   e'!2-"I4"
   f'!2
   b'!2.
   ais'!2
   cis'!2.
   gis'!4-"RI9"
   c'!2
   d'!4
   b'!4
   g'!2.
   f'!2
   cis'!2.
   fis'!4
   dis'!4
   e'!4
   ais'!2
   a'!2.-"P9"
   gis'!4
   d'!2.
   dis'!4
   c'!2
   f'!2
   cis'!4-"P1"
   c'!2.
   fis'!4
   g'!4
   e'!2.
   a'!2.
   f'!2
   dis'!2.
   b'!2
   gis'!4
   ais'!2.
   d'!2.-"I2"
   dis'!4
   a'!2
   gis'!2
   b'!4
   fis'!4
   ais'!4
   c'!2.
   e'!2.
   g'!2
   f'!2.-"R4"
   cis'!2
   b'!4
   d'!2.
   fis'!2
   gis'!4
   c'!2.
   g'!2-"RI8"
   b'!4
   cis'!4
   ais'!2-"RI11"
   d'!4-"R1"
   ais'!2
   gis'!4
   b'!2.
   dis'!2
   f'!2
   a'!2-"P9"
   gis'!2
   d'!4
   dis'!2
   c'!4
   f'!4
   cis'!2.
   b'!2.
   g'!2.-"RI8"
   b'!2
   cis'!2
   ais'!4-"R9"
   fis'!4
   e'!2.
   g'!2.
   b'!2
   cis'!4
   f'!4
   c'!2
   dis'!2.
   d'!2-"R1"
   ais'!2
   gis'!2.
   b'!2.
   dis'!2
   f'!2.
   a'!4
   e'!2
   g'!2-"R6"
   dis'!4
   cis'!2.-"RI2"
   f'!2.
   g'!4
   e'!2.
   c'!2
   ais'!2
   fis'!2.
   b'!4
   gis'!2
   a'!2.
   dis'!2.-"P3"
   d'!2.
   gis'!2.
   a'!2
   fis'!4
   b'!2-"P11"
   ais'!2.
   e'!2
   f'!2.
   d'!2.
   g'!2.
   dis'!2.
   cis'!2.
   a'!2
   fis'!4-"R5"
   d'!2.-"I2"
   dis'!4
   a'!2
   gis'!2.
   b'!2-"P11"
   ais'!4
   e'!2.
   f'!2
   d'!4
   g'!2
   dis'!2.
   cis'!4-"RI2"
   f'!4
   g'!4
   e'!4
   c'!2.
   ais'!2
   fis'!2
   b'!4
   gis'!2.-"R7"
   e'!4-"RI5"
   gis'!2
   ais'!2.
   g'!2-"I7"
   gis'!4
   d'!4
   cis'!4
   e'!4
   b'!2.
   dis'!2
   f'!2
   a'!2.
   c'!2.
   ais'!2.-"R9"
   fis'!2
   e'!4
   g'!2.
   b'!2.
   cis'!4
   f'!2.
   c'!2-"P0"
   b'!2.
   f'!2.
   fis'!2
   dis'!2.
   gis'!4
   e'!2
   d'!2.
   ais'!2.
   g'!4
   a'!2.
   cis'!2
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
