%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   a4-"RI 0"
   dis2
   e4
   ais2
   fis2
   d2.
   gis2
   g4
   b2
   f2.
   cis4
   c2-"I 0"
   cis2
   f2.
   b2
   g4
   gis2-"RI 11"
   d2.
   dis2
   a2
   f2.
   cis2
   g2.
   fis2.
   ais2
   e2.
   c2-"R 9"
   fis2.
   f2.
   b2.
   dis4
   g4
   cis4
   d2.
   ais2
   e4
   gis2-"RI 11"
   d2.
   dis4
   a2.
   f4-"RI 8"
   b2.
   c2.
   fis2.
   d2.
   ais2
   e2.-"P 4"
   dis4
   b4
   f2-"I 5"
   fis4
   ais2
   e4
   c4
   cis2.
   g2
   b2.-"R 8"
   f2
   e2.
   ais2
   d2
   fis2.
   c2
   cis2
   a2.
   dis2.-"RI 6"
   a2
   ais4
   e2.
   c2
   gis2
   d2
   cis4
   f2.-"P 5"
   e2.
   c4
   fis2.
   ais4
   a2.-"RI 0"
   dis2
   e2
   ais4
   fis2.
   d2.
   gis2.
   g2.
   b4-"P 11"
   ais4
   fis2.
   c2.
   e4
   dis2
   a4
   f4-"RI 8"
   b2
   c2.
   fis2
   d4
   ais4
   e2.
   dis2.
   g4
   cis2.-"RI 4"
   g2
   gis2
   d2.
   ais2
   fis2.
   c2
   b4-"I 11"
   c4
   e2.
   ais4
   fis4
   g2.
   cis4
   f2
   a2
   dis2.
   d2
   gis2-"P 8"
   g2.
   dis4
   a4
   cis2
   c4
   fis2
   d4
   ais2
   e2.
   f2
   b2-"I 11"
   c2
   e2.
   ais4
   fis2.
   g2.
   cis2.
   f2.
   a2.-"P 9"
   gis2.
   e2
   ais4
   d4
   cis2.
   g2
   dis2.
   b4
   f2
   fis2.-"RI 9"
   c2
   cis2.
   g4
   dis2
   b2.-"I 11"
   c2.
   e4
   ais4
   fis2
   g2.
   cis2
   f4-"R 2"
   b2-"I 11"
   c4
   e2
   ais4
   fis2.
   g2
   cis2
   f4
   a2.
   dis4-"R 0"
   a2
   gis2.
   d4
   fis4
   ais4
   e2.
   f4
   cis2
   g2.
   b4-"P 11"
   ais4
   fis2.
   c2
   e2-"RI 7"
   ais2
   b4
   f2.
   cis2
   a4
   dis2
   d4
   fis2.
   c2
   gis2.
   g2-"R 4"
   cis4
   c2
   fis4
   ais4
   d2
   gis2.
   a2.
   f4
   b2-"P 11"
   ais2
   fis2
   c4-"R 9"
   fis2
   f4
   b2
   dis2
   g2
   cis4
   d4
   ais4-"P 10"
   a2.
   f4
   b2.
   dis4
   d2.
   gis2.
   e2
   c2.
   fis2.
   g2
   cis2.-"I 1"
   d2
   fis2
   c2
   gis4
   a2.
   dis2.
   g2.
   b4-"R 8"
   f2.
   e4
   ais4
   d4
   fis2.
   c2
   cis2
   a2.
   dis4
   g2.-"I 7"
   gis4
   c4
   fis4
   d2
   dis4
   a2.
   cis4
   f4-"P 5"
   e2.
   c2
   fis2
   ais4-"I 10"
   b2
   dis2
   a4
   f4
   fis2
   c4-"R 9"
   fis2.
   f2.
   b4
   dis2
   g2.
   cis4
   d4
   ais2-"P 10"
   a2
   f2
   b2.-"R 8"
   f4
   e2
   ais2.
   d4-"R 11"
   gis4
   g2
   cis4
   f4
   a2.
   dis2.
   e2
   c2
   fis2
   ais4
   b2.-"I 11"
   c2.
   e4-"P 4"
   dis4
   b2
   f2-"RI 8"
   b2
   c2-"R 9"
   fis4
   f2.-"RI 8"
   b4
   c2.
   fis2
   d2.-"R 11"
   gis4
   g2
   cis2.
   f4
   a2
   dis2.
   e4-"RI 7"
   ais2
   b4-"R 8"
   f2.
   e2.
   ais2
   d2.
   fis2
   c4
   cis2-"R 10"
   g2
   fis2
   c2.
   e2
   gis4
   d2.
   dis2
   b2.
   f4-"P 5"
   e2
   c2.
   fis2.
   ais4
   a2.
   dis2.
   b4
   g2
   cis2.
   d2
   gis2.-"RI 11"
   d2
   dis2.
   a4
   f2.
   cis4
   g4
   fis2.
   ais4
   e4-"RI 7"
   ais2.
   b4
   f4-"I 5"
   fis2
   ais2.
   e2.-"RI 7"
   ais2
   b2
   f2
   cis2.
   a2.
   dis4
   d2.
   fis4-"RI 9"
   c4
   cis4
   g2
   dis2
   b4
   f2
   e2.-"RI 7"
   ais2
   b2
   f4
   cis4
   a2
   dis2
   d2.
   fis4
   c4-"RI 3"
   fis2
   g4
   cis4
   a2
   f2.
   b2.-"R 8"
   f2
   e2-"I 4"
   f2
   a4
   dis2.
   b2.-"RI 2"
   f2
   fis2.
   c2.
   gis4
   e2
   ais2.
   a4
   cis4
   g4
   dis4
   d4-"I 2"
   dis4
   g2
   cis2
   a2.
   ais2.
   e4
   gis2.
   c2.
   fis4
   f2-"P 5"
   e2
   c2.
   fis2
   ais2.
   a2.
   dis2-"RI 6"
   a2.
   ais2
   e4
   c2
   gis4
   d4
   cis4
   f2.-"RI 8"
   b2.
   c2.
   fis2.
   d2.
   ais2
   e2.-"R 1"
   ais2
   a4
   dis2.
   g2.
   b4
   f4-"RI 8"
   b2
   c2.
   fis2.
   d4
   ais2
   e2
   dis4
   g2.-"P 7"
   fis2.
   d2
   gis2
   c2
   b4-"R 8"
   f4
   e2-"RI 7"
   ais2
   b2
   f4
   cis2-"R 10"
   g2
   fis2
   c2
   e4
   gis2.-"RI 11"
   d2.
   dis2
   a2
   f2.-"P 5"
   e2
   c4
   fis4
   ais2
   a4-"R 6"
   dis2
   d4
   gis4
   c4
   e4
   ais4
   b2-"I 11"
   c4
   e2.
   ais2
   fis2.
   g2
   cis2.
   f2
   a2.
   dis2
   d4
   gis2.-"RI 11"
   d4
   dis2.
   a4
   f2.
   cis2
   g2
   fis4
   ais4
   e2.-"RI 7"
   ais2.
   b2
   f4
   cis4
   a2.
   dis2.
   d2
   fis4
   c2.-"P 0"
   b2.
   g2.
   cis2
   f2
   e4
   ais4
   fis4
   d2.
   gis4
   a2.
   dis4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
