%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f4-"1"
    c1-"2"
    c8-"3"
    d1-"4"
    a2-"5"
    ais8-"6"
    cis8-"7"
    gis8-"8"
    gis1-"9"
    g8-"10"
    fis4-"11"
    gis8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g16\p-"1"
    e1-"2"
    d1-"3"
    d1-"4"
    cis8-"5"
    f1-"6"
    cis4-"7"
    fis2-"8"
    f2-"9"
    dis1-"10"
    b2-"11"
    a8-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1-"1"
    a1-"2"
    b8-"3"
    c2-"4"
    fis2-"5"
    e2\p-"6"
    e4\pp-"7"
    ais16\pp-"8"
    e1-"9"
    a16-"10"
    gis2-"11"
    e2-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
