%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis2-"5"
    gis2-"8"
    dis4-"6"
    dis4-"6"
    dis4-"6"
    dis1-"12"
    dis4-"11"
    dis4-"6"
    dis1-"12"
    dis4-"9"
    dis1-"12"
    ais4-"2"
    dis4-"6"
    f4-"7"
    gis2-"3"
    dis1-"12"
    gis2-"8"
    dis4-"6"
    f16-"1"
    ais4-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"5"
    dis8-"8"
    f2-"6"
    f2-"6"
    f2-"6"
    b8-"12"
    f2-"11"
    f2-"6"
    b8-"12"
    f2-"9"
    b8-"12"
    gis1\pp-"2"
    f2-"6"
    cis1-"7"
    dis8-"3"
    b8-"12"
    dis8-"8"
    f2-"6"
    a8\ff-"1"
    gis1\pp-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis4-"5"
    gis4-"8"
    f8-"6"
    f8-"6"
    f8-"6"
    b4-"12"
    f8-"11"
    f8-"6"
    b4-"12"
    f8-"9"
    b4-"12"
    b2\ff-"2"
    f8-"6"
    cis4\pp-"7"
    gis4-"3"
    b4-"12"
    gis4-"8"
    f8-"6"
    f2-"1"
    b2\ff-"2"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
