%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   c'2.-"R1"
   e'4
   gis'2.
   f'4
   ais'2
   d'2.
   fis'2.
   b'2.-"R0"
   dis'2
   g'4
   e'4
   a'2
   cis'4
   f'2.-"R6"
   a'2.
   cis'2
   ais'4
   dis'2
   g'2
   b'2
   e'2
   gis'2.
   c'4-"R1"
   e'4
   gis'2
   f'2.
   ais'4-"R11"
   d'4
   fis'2.
   dis'2.
   gis'4-"I8"
   c'4
   d'4
   fis'2
   ais'4
   dis'2.
   g'2.
   b'2.
   e'4
   cis'2.-"RI0"
   a'2.
   f'4
   gis'2.
   dis'2
   b'2.
   g'2
   d'2.-"I2"
   fis'2.
   gis'2-"I8"
   c'4
   d'2.
   fis'2
   ais'2
   dis'2
   g'2
   b'2.
   e'2.
   cis'4-"R2"
   f'2.
   a'2
   fis'4
   b'2.
   dis'2.-"R4"
   g'2
   b'4
   gis'4
   cis'2.
   f'2.
   a'2-"P9"
   f'2
   dis'2
   b'2.
   g'2.
   d'2.
   ais'2
   fis'2
   cis'4
   e'2-"RI3"
   c'2.
   gis'2
   b'2.
   fis'2.
   d'4
   ais'2.
   f'4
   cis'2
   a'4-"RI8"
   f'4
   cis'4
   e'2.
   b'2.-"P11"
   g'4
   f'2
   cis'4
   a'2.-"R10"
   cis'2
   f'2
   d'2.
   g'2
   b'2
   dis'4
   gis'4
   c'2.
   e'4
   fis'2.
   ais'4-"I10"
   d'2.-"P2"
   ais'2.
   gis'2
   e'2
   c'2.
   g'2.
   dis'2.-"P3"
   b'4
   a'4
   f'2
   cis'2.
   gis'2
   e'2.
   c'2.
   g'4
   ais'2.-"RI9"
   fis'4
   d'4
   f'2.-"I5"
   a'2.
   b'4
   dis'2.-"I3"
   g'2
   a'2
   cis'4
   f'2.
   ais'2
   d'2
   fis'4
   b'2.
   gis'2.
   c'2.-"RI11"
   gis'2
   e'2.-"I4"
   gis'2
   ais'2.
   d'2-"P2"
   ais'2.
   gis'2.-"RI7"
   e'4
   c'2
   dis'2.
   ais'2
   fis'4
   d'2.
   a'2.
   f'4
   cis'4
   b'4-"R0"
   dis'2
   g'4-"R8"
   b'2
   dis'2.
   c'2.
   f'2
   a'4
   cis'4
   fis'2.
   ais'2
   d'4-"R3"
   fis'4
   ais'4
   g'2
   c'4
   e'4-"P4"
   c'2.
   ais'2
   fis'2.
   d'2-"I2"
   fis'2.
   gis'4-"R9"
   c'2.
   e'4-"R5"
   gis'4
   c'2.
   a'2
   d'2.
   fis'4-"P6"
   d'2.
   c'2.
   gis'4
   e'2-"P4"
   c'2.-"RI11"
   gis'4
   e'2.
   g'4
   d'2
   ais'2.
   fis'2
   cis'2.-"P1"
   a'2
   g'2
   dis'2
   b'2.
   fis'4
   d'4
   ais'2.
   f'2
   gis'2-"I8"
   c'2
   d'4
   fis'2
   ais'2
   dis'2
   g'4
   b'4
   e'2
   cis'2-"P1"
   a'2.
   g'2.
   dis'2.
   b'2.-"I11"
   dis'4
   f'4
   a'2
   cis'2
   fis'4
   ais'2.
   d'4
   g'4
   e'2.-"P4"
   c'2.
   ais'2
   fis'2.
   d'2.-"R3"
   fis'4
   ais'2
   g'2.-"RI6"
   dis'2-"P3"
   b'2.
   a'4
   f'4
   cis'2
   gis'4
   e'2.
   c'2
   g'2-"RI6"
   dis'4
   b'2.
   d'2.
   a'2.
   f'2
   cis'2
   gis'2
   e'2-"RI3"
   c'2
   gis'4-"P8"
   e'2
   d'4
   ais'2.
   fis'4
   cis'2
   a'2.-"R10"
   cis'2
   f'2
   d'2
   g'2
   b'4-"P11"
   g'4
   f'2
   cis'2
   a'4-"I9"
   cis'4
   dis'2.
   g'2.
   b'2.-"R0"
   dis'4
   g'2
   e'2.
   a'4
   cis'2
   f'4
   ais'2.
   d'4
   fis'2.
   gis'2
   c'2-"I0"
   e'2
   fis'4
   ais'2
   d'2
   g'4
   b'4
   dis'4
   gis'2.
   f'2
   a'4
   cis'2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
