%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e16-"1"
    cis4\mp-"2"
    ais1\f-"3"
    dis2-"4"
    ais1-"5"
    fis8-"6"
    b8-"7"
    f8-"8"
    a16-"9"
    g4\f-"10"
    e8-"11"
    c16-"12"
    fis4-"13"
    d8-"14"
    g1-"15"
    g16-"16"
    b16-"17"
    f8-"18"
    c2-"19"
    dis16-"20"
    d16-"21"
    a1-"22"
    g8-"23"
    dis16\ff-"24"
    f2-"25"
    e4-"26"
    ais8\ff-"27"
    f4\f-"28"
    cis2-"29"
    f2-"30"
    gis16-"31"
    fis8\p-"32"
    cis2-"33"
    cis16-"34"
    e16-"35"
    a1\p-"36"
    e4-"37"
    fis8-"38"
    cis8-"39"
    d2-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    cis8-"1"
    f2-"2"
    g8\p-"3"
    e2-"4"
    g4-"5"
    e2-"6"
    e8\mf-"7"
    b16-"8"
    cis16-"9"
    f1-"10"
    gis4-"11"
    d4-"12"
    dis8-"13"
    fis1-"14"
    b4\pp-"15"
    gis2-"16"
    e2-"17"
    c16-"18"
    gis2-"19"
    d2-"20"
    b2\p-"21"
    c4-"22"
    cis8\pp-"23"
    e4-"24"
    ais16-"25"
    dis1-"26"
    gis2-"27"
    gis16-"28"
    c8-"29"
    ais16-"30"
    gis2-"31"
    f16-"32"
    c4-"33"
    a16\pp-"34"
    a1-"35"
    a4-"36"
    g16-"37"
    ais8-"38"
    dis8\mf-"39"
    g2\p-"40"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis4-"1"
    g4\mf-"2"
    dis8-"3"
    e8-"4"
    e2\mf-"5"
    b1-"6"
    fis2\pp-"7"
    f1-"8"
    ais16-"9"
    gis8\mf-"10"
    fis8-"11"
    ais16-"12"
    e4-"13"
    g8-"14"
    gis1-"15"
    dis4-"16"
    ais2-"17"
    e1-"18"
    dis8-"19"
    gis16\ff-"20"
    dis16-"21"
    gis2-"22"
    gis16-"23"
    ais16-"24"
    f1-"25"
    g4-"26"
    f8-"27"
    cis8-"28"
    d16-"29"
    gis1-"30"
    gis4-"31"
    b2\p-"32"
    b16-"33"
    fis8\f-"34"
    c4-"35"
    d8-"36"
    gis1-"37"
    dis8-"38"
    g8-"39"
    fis4\ff-"40"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
