%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"1"
    gis8-"9"
    fis8-"2"
    dis8-"8"
    gis1-"7"
    gis1\p-"3"
    gis1-"1"
    cis1\p-"12"
    g8-"4"
    gis8-"9"
    fis8-"2"
    gis1-"7"
    gis1\p-"3"
    gis1-"1"
    g8-"4"
    dis8-"8"
    ais8-"6"
    gis1\p-"3"
    dis8-"8"
    cis1\p-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    b4-"1"
    g16\pp-"9"
    gis8\mp-"2"
    ais8-"8"
    b4-"7"
    fis2\p-"3"
    b4-"1"
    gis1-"12"
    dis2-"4"
    g16\pp-"9"
    gis8\mp-"2"
    b4-"7"
    fis2\p-"3"
    b4-"1"
    dis2-"4"
    ais8-"8"
    ais16-"6"
    fis2\p-"3"
    ais8-"8"
    gis1-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    e1-"1"
    dis2-"9"
    ais8-"2"
    g1-"8"
    e1-"7"
    a16-"3"
    e1-"1"
    g4-"12"
    g16-"4"
    dis2-"9"
    ais8-"2"
    e1-"7"
    a16-"3"
    e1-"1"
    g16-"4"
    g1-"8"
    fis4-"6"
    a16-"3"
    g1-"8"
    g4-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
