%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   gis'2-"P8"
   b'2.
   c'2.
   d'2.
   ais'2
   e'2.
   cis'4
   f'2-"I5"
   d'2.
   cis'2.
   b'2-"P11"
   d'4
   dis'2.
   f'4-"RI0"
   d'2.
   cis'2
   b'2
   dis'4
   g'4
   e'2.
   ais'2
   fis'4
   gis'4-"RI3"
   f'2.
   e'4
   d'4
   fis'4
   ais'4-"RI5"
   g'4
   fis'2
   e'4
   gis'2.
   c'2
   a'2
   dis'4
   b'4-"P11"
   d'2
   dis'2.
   f'2
   cis'2.
   g'4
   e'2-"RI11"
   cis'2.
   c'4
   ais'4
   d'2.
   fis'4
   dis'2
   a'2.
   f'2.-"I5"
   d'2.
   cis'2
   b'2-"P11"
   d'2
   dis'2
   f'2.
   cis'2.-"P1"
   e'2.
   f'2.
   g'2.
   dis'2-"P3"
   fis'2.-"I6"
   dis'2
   d'2
   c'2
   e'4
   ais'2.
   cis'2
   a'2.
   f'2.
   g'4
   gis'2.
   b'4-"I11"
   gis'2.
   g'4
   f'2.
   a'4
   dis'2.
   fis'4-"RI1"
   dis'2.
   d'2
   c'2
   e'4
   gis'4
   f'2
   b'2
   g'4
   a'4
   ais'4-"R3"
   cis'2.
   d'2.
   e'4
   c'2
   gis'2.
   b'4
   f'4
   a'2-"RI4"
   fis'4
   f'2
   dis'2.
   g'4
   b'4
   gis'2
   d'2.
   ais'2
   c'4
   cis'2.
   e'2.-"P4"
   g'2.-"I7"
   e'2
   dis'4
   cis'4
   f'2.
   b'2.
   d'2.
   ais'2-"I10"
   g'2
   fis'2.
   e'2.-"P4"
   g'2
   gis'4
   ais'2.
   fis'2
   c'4
   a'2.
   cis'2
   f'4
   dis'2-"P3"
   fis'2
   g'2.
   a'4
   f'2.
   b'2.-"RI6"
   gis'2.
   g'4
   f'4-"I5"
   d'2
   cis'4
   b'2.
   dis'4
   a'4
   c'4
   gis'2.
   e'2.-"P4"
   g'2
   gis'4
   ais'2
   fis'4-"RI1"
   dis'2.
   d'4
   c'2
   e'2.
   gis'2.
   f'2.
   b'2.
   g'4
   a'2
   ais'2
   cis'4-"R6"
   e'2
   f'4
   g'4
   dis'4
   b'2.
   d'2
   gis'2.
   c'4
   ais'2
   a'2-"P9"
   c'2.
   cis'2.
   dis'4
   b'2
   f'2
   d'2.-"RI9"
   b'4
   ais'4-"I10"
   g'2
   fis'4
   e'4
   gis'4
   d'2
   f'2
   cis'4
   a'2
   b'2.
   c'2.-"RI7"
   a'2.
   gis'4
   fis'2
   ais'2
   d'2.-"R7"
   f'2.
   fis'4
   gis'4
   e'2
   c'2.
   dis'2
   a'2.
   cis'4
   b'2-"P11"
   d'4
   dis'2
   f'2.
   cis'2
   g'2
   e'4
   gis'2
   c'4
   ais'2.
   a'2.
   fis'4-"RI1"
   dis'2-"RI10"
   c'2.
   b'4
   a'4
   cis'2
   f'4
   d'4-"P2"
   f'4-"I5"
   d'2-"I2"
   b'2-"P11"
   d'4
   dis'2.
   f'2.
   cis'2
   g'4
   e'2.
   gis'2
   c'2
   ais'2.-"I10"
   g'2.
   fis'2.
   e'2.
   gis'2
   d'2-"RI9"
   b'4
   ais'2
   gis'2.
   c'2
   e'2.
   cis'2.
   g'2-"I7"
   e'2.
   dis'4
   cis'2
   f'4
   b'2
   d'2
   ais'4
   fis'2.
   gis'2.
   a'2-"P9"
   c'4
   cis'4
   dis'4
   b'4
   f'2.
   d'2-"I2"
   b'4
   ais'2.-"I10"
   g'2.
   fis'2.-"R11"
   a'4
   ais'4
   c'2
   gis'4
   e'2
   g'2
   cis'4
   f'2-"P5"
   gis'4
   a'2.
   b'2.
   g'4
   cis'2.
   ais'2.
   d'4
   fis'4-"RI1"
   dis'2.
   d'2
   c'2.
   e'2
   gis'4
   f'2.-"RI0"
   d'2.
   cis'4
   b'2.
   dis'2
   g'2
   e'2-"P4"
   g'4
   gis'2.
   ais'4-"R3"
   cis'2
   d'2.
   e'2
   c'4
   gis'4
   b'2
   f'2.
   a'2
   g'2.
   fis'2.
   dis'2-"I3"
   c'2
   b'2
   a'2
   cis'2
   g'4
   ais'2
   fis'4-"P6"
   a'4
   ais'2.
   c'2
   gis'2.-"R1"
   b'2
   c'2.
   d'4
   ais'2.
   fis'2
   a'4-"RI4"
   fis'2
   f'4
   dis'4
   g'2.
   b'2-"P11"
   d'2.
   dis'2.
   f'2
   cis'2
   g'4
   e'4
   gis'4-"RI3"
   f'2.
   e'4
   d'4
   fis'4
   ais'2.
   g'2-"R0"
   ais'4
   b'2.
   cis'2.
   a'4
   f'2.
   gis'4
   d'4-"P2"
   f'2.
   fis'2.
   gis'2
   e'2
   ais'4
   g'2.
   b'4
   dis'4
   cis'2
   c'2.-"P0"
   dis'2.
   e'4
   fis'2
   d'4
   gis'4
   f'2
   a'2.
   cis'4
   b'4
   ais'4
   g'2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
