%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   g'!4-"I7"
   fis'!4
   ais'!2
   f'!2
   dis'!2
   d'!4
   cis'!2
   gis'!4
   e'!2-"RI11"
   cis'!4
   dis'!2
   gis'!4
   c'!2
   f'!2
   fis'!4
   g'!4
   a'!4-"R2"
   c'!2.
   ais'!2
   f'!2.
   cis'!4
   gis'!2.
   g'!4
   fis'!4-"R11"
   a'!2.
   g'!2.
   d'!4
   ais'!2
   f'!4
   e'!4
   dis'!4
   cis'!2.
   gis'!4
   c'!2.
   b'!2-"I11"
   ais'!2
   d'!2.
   a'!2
   g'!2.
   fis'!2.-"I6"
   f'!4
   a'!2.
   e'!2
   d'!2.-"P2"
   dis'!2.
   b'!2
   e'!2
   fis'!2.
   g'!4
   gis'!2.
   cis'!4
   f'!4
   ais'!4
   c'!4
   a'!2.-"R2"
   c'!2.
   ais'!2
   f'!2
   cis'!4
   gis'!4
   g'!4
   fis'!2.
   e'!2-"RI11"
   cis'!2.-"P1"
   d'!2.
   ais'!2
   dis'!2
   f'!2.
   fis'!4
   g'!4
   c'!2.
   e'!2.
   a'!4-"I9"
   gis'!2.
   c'!2.
   g'!4
   f'!2.
   e'!4
   dis'!2.
   ais'!4
   fis'!2.-"RI1"
   dis'!2.
   f'!2.-"R10"
   gis'!2.
   fis'!2.-"R11"
   a'!2.
   g'!2
   d'!4
   ais'!2.
   f'!2.
   e'!2
   dis'!2.
   cis'!4
   gis'!2
   c'!2.
   b'!2-"P11"
   c'!2.
   gis'!2
   cis'!2
   dis'!2
   e'!2.
   f'!2.
   ais'!2.
   d'!2.
   g'!4-"I7"
   fis'!2.
   ais'!2.
   f'!2
   dis'!2.
   d'!2
   cis'!2.
   gis'!2-"P8"
   a'!2
   f'!2.
   ais'!4
   c'!4
   cis'!2
   d'!2.
   g'!2.-"I7"
   fis'!2.
   ais'!4
   f'!2.
   dis'!2
   d'!2.
   cis'!2
   gis'!4
   e'!4
   b'!4
   a'!2.-"R2"
   c'!2.
   ais'!2
   f'!4
   cis'!2.
   gis'!4
   g'!4
   fis'!4-"P6"
   g'!4
   dis'!2.
   gis'!2.
   ais'!4
   b'!4
   c'!4
   f'!2
   a'!2.
   d'!2-"R7"
   f'!2
   dis'!4
   ais'!4
   fis'!4
   cis'!2.
   c'!2.
   b'!2.
   a'!2
   e'!4-"RI11"
   cis'!2
   dis'!2
   gis'!2
   c'!2
   f'!2.-"P5"
   fis'!4
   d'!4
   g'!2.
   a'!2
   ais'!4
   b'!2.
   e'!2
   gis'!2.
   cis'!4-"RI8"
   ais'!2
   c'!2
   f'!4
   a'!2.-"R2"
   c'!4
   ais'!2.
   f'!2.
   cis'!4
   gis'!4
   g'!4
   fis'!4
   e'!2.-"RI11"
   cis'!4
   dis'!2
   gis'!2.-"R1"
   b'!4
   a'!2.
   e'!2.
   c'!2.
   g'!2
   fis'!2.
   f'!4-"RI0"
   d'!2
   e'!2.-"RI11"
   cis'!2
   dis'!4
   gis'!4
   c'!2
   f'!4-"P5"
   fis'!2.-"I6"
   f'!2
   a'!2
   e'!2.
   d'!2
   cis'!2.
   c'!4
   g'!4
   dis'!4-"R8"
   fis'!2.
   e'!2.
   b'!4
   g'!2
   d'!2.
   cis'!4
   c'!2.
   ais'!2
   f'!2.
   a'!4-"I9"
   gis'!2.
   c'!4
   g'!2.
   f'!2
   e'!2.
   dis'!4
   ais'!4
   fis'!4-"R11"
   a'!2.
   g'!2.
   d'!4
   ais'!4
   f'!4
   e'!2.-"I4"
   dis'!2-"P3"
   e'!2
   c'!4
   f'!2.
   g'!2
   gis'!4
   a'!2.-"R2"
   c'!2.
   ais'!2.
   f'!4
   cis'!4
   gis'!2.
   g'!2
   fis'!2.
   e'!2-"RI11"
   cis'!2.
   dis'!2
   gis'!2
   c'!2
   f'!2
   fis'!4
   g'!2
   a'!4-"RI4"
   fis'!2
   gis'!2.-"RI3"
   f'!2
   g'!2.
   c'!2
   e'!2.-"RI11"
   cis'!4
   dis'!4
   gis'!2.
   c'!2.-"P0"
   cis'!2
   a'!2.
   d'!4
   e'!2
   f'!2.
   fis'!2.
   b'!4
   dis'!2.
   gis'!4
   ais'!4
   g'!4
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
