%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f4-"2"
    c1-"1"
    c8-"3"
    c1-"10"
    fis4-"12"
    f4-"8"
    c1-"10"
    c1-"1"
    gis8-"5"
    f4-"2"
    c8-"3"
    c8-"11"
    g8-"7"
    gis8-"5"
    f4-"2"
    gis8-"6"
    a2-"9"
    a2-"9"
    gis8-"5"
    f4-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    g16\p-"2"
    e1-"1"
    d1-"3"
    e1-"10"
    b2-"12"
    g16\p-"8"
    e1-"10"
    e1-"1"
    a8-"5"
    g16\p-"2"
    d1-"3"
    d1-"11"
    dis1-"7"
    a8-"5"
    g16\p-"2"
    fis2-"6"
    cis8-"9"
    cis8-"9"
    a8-"5"
    g16\p-"2"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis1-"2"
    a1-"1"
    b8-"3"
    a1-"10"
    gis2-"12"
    fis1-"8"
    a1-"10"
    a1-"1"
    e2-"5"
    fis1-"2"
    b8-"3"
    b8-"11"
    a16-"7"
    e2-"5"
    fis1-"2"
    ais16\pp-"6"
    fis2-"9"
    fis2-"9"
    e2-"5"
    fis1-"2"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
