%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=484\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 484\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 484\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   a'!2.-"R7"
   f'!2
   cis'!4
   ais'!2
   dis'!2.
   c'!4
   b'!4
   d'!2
   gis'!4
   e'!2.
   fis'!2-"P6"
   f'!2.
   dis'!2-"RI5"
   g'!4
   b'!2.
   d'!2
   a'!2.
   c'!4
   cis'!4
   ais'!4-"P10"
   a'!4-"RI11"
   cis'!2
   f'!2.
   gis'!2
   dis'!4
   fis'!2
   g'!4
   e'!2.
   ais'!4
   d'!4-"P2"
   cis'!2
   b'!2
   dis'!2
   a'!2.
   fis'!4
   g'!2
   ais'!2
   f'!2-"R3"
   cis'!2.
   a'!2
   fis'!2.
   b'!4
   gis'!2
   g'!4
   ais'!2.
   e'!2
   c'!2
   d'!2-"RI4"
   fis'!2.
   ais'!2.
   cis'!2
   gis'!2
   b'!4
   c'!2
   a'!2
   dis'!4
   g'!4-"P7"
   fis'!2.
   e'!2.
   gis'!2.
   d'!2.
   b'!2
   c'!4
   dis'!2
   ais'!4
   cis'!2.
   f'!4
   a'!2.-"I9"
   ais'!2
   c'!4-"R10"
   gis'!2.
   e'!4
   cis'!2.
   fis'!2-"I6"
   g'!2
   a'!4
   f'!2.
   b'!2.
   d'!4
   cis'!2
   ais'!4
   dis'!2
   c'!2
   gis'!2-"P8"
   g'!4
   f'!4
   a'!2.
   dis'!4
   c'!2.
   cis'!4
   e'!4
   b'!2
   d'!2.-"RI4"
   fis'!2
   ais'!4-"R8"
   fis'!2
   d'!2.
   b'!4
   e'!2
   cis'!2
   c'!2.
   dis'!2.-"RI5"
   g'!2.
   b'!2.
   d'!2.
   a'!2.
   c'!2.
   cis'!2.
   ais'!2
   e'!2.
   gis'!4
   fis'!4-"P6"
   f'!4
   dis'!2
   g'!2.
   cis'!4
   ais'!4
   b'!4
   d'!2
   a'!2
   c'!4
   e'!4-"R2"
   c'!4
   gis'!2.
   f'!2
   ais'!2.
   g'!2
   fis'!2
   a'!2
   dis'!2
   b'!2.-"R9"
   g'!2
   dis'!2
   c'!4
   f'!4
   d'!2.
   cis'!2.
   e'!4
   ais'!4
   fis'!4
   gis'!2
   a'!2-"R7"
   f'!4
   cis'!4
   ais'!2
   dis'!2.
   c'!2
   b'!2.
   d'!4
   gis'!4
   e'!4
   fis'!4
   g'!2.-"R5"
   dis'!4
   b'!4
   gis'!2
   cis'!2.
   ais'!2.
   a'!4
   c'!2
   fis'!4
   d'!2.
   e'!4-"RI6"
   gis'!2
   c'!4
   dis'!2.
   ais'!2.
   cis'!2
   d'!2.
   b'!2
   f'!4
   a'!4-"R7"
   f'!2
   cis'!2.
   ais'!2.
   dis'!2-"I3"
   e'!4
   fis'!2
   d'!2
   gis'!4
   b'!4-"RI1"
   dis'!4
   g'!4
   ais'!4
   f'!2
   gis'!4
   a'!2.
   fis'!4
   c'!4
   e'!2.-"R2"
   c'!2.
   gis'!4
   f'!4
   ais'!2
   g'!2.-"I7"
   gis'!2-"RI10"
   c'!2
   e'!2
   g'!2.
   d'!4
   f'!2
   fis'!2
   dis'!4
   a'!2
   cis'!4
   b'!2-"RI1"
   dis'!2.
   g'!4
   ais'!2
   f'!4
   gis'!4
   a'!4
   fis'!4-"I6"
   g'!2.
   a'!2.-"P9"
   gis'!4
   fis'!2
   ais'!2.
   e'!2
   cis'!2
   d'!4
   f'!4-"P5"
   e'!2.
   d'!4
   fis'!2
   c'!2.
   a'!2
   ais'!4-"R8"
   fis'!2
   d'!4
   b'!4
   e'!2.
   cis'!2
   c'!4
   dis'!2
   a'!4
   f'!2
   g'!4-"R5"
   dis'!4
   b'!4-"I11"
   c'!4-"P0"
   b'!4
   a'!4
   cis'!2.
   g'!2
   e'!2
   f'!4
   gis'!4
   dis'!4
   fis'!2.
   ais'!2.
   d'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
