%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a2-"7"
    a2-"7"
    b16-"3"
    g4\mf-"12"
    dis2-"4"
    g4\mf-"1"
    dis2-"4"
    g4\mf-"12"
    e1-"9"
    b16-"3"
    a2-"7"
    a2-"7"
    a2-"7"
    g4\mf-"2"
    g4\mf-"12"
    g4\mf-"11"
    g4\mf-"12"
    g4\mf-"1"
    e1-"9"
    e1-"9"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    a1\mp-"7"
    a1\mp-"7"
    cis1-"3"
    cis4-"12"
    f8\pp-"4"
    cis4-"1"
    f8\pp-"4"
    cis4-"12"
    fis4-"9"
    cis1-"3"
    a1\mp-"7"
    a1\mp-"7"
    a1\mp-"7"
    cis4-"2"
    cis4-"12"
    cis4-"11"
    cis4-"12"
    cis4-"1"
    fis4-"9"
    fis4-"9"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d16-"7"
    d16-"7"
    d16-"3"
    fis2-"12"
    d16-"4"
    fis2-"1"
    d16-"4"
    fis2-"12"
    e8-"9"
    d16-"3"
    d16-"7"
    d16-"7"
    d16-"7"
    fis2-"2"
    fis2-"12"
    fis2-"11"
    fis2-"12"
    fis2-"1"
    e8-"9"
    e8-"9"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
