%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 

\layout{}


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   ais'!2.-"R0"
   dis'!2.
   cis'!4
   a'!2.
   f'!4
   e'!2
   d'!4-"I2"
   fis'!2
   dis'!2.-"RI1"
   ais'!2-"I10"
   d'!2
   b'!2.
   dis'!2
   e'!2
   gis'!2
   fis'!4
   f'!2
   cis'!2
   a'!2.
   g'!4-"R9"
   c'!4
   ais'!4
   fis'!4
   d'!4
   cis'!2.
   b'!4
   dis'!2
   e'!2.-"I4"
   gis'!2.
   f'!2
   a'!4
   ais'!2.
   d'!2.-"RI0"
   a'!2.
   b'!2.
   dis'!4
   g'!2
   gis'!2.
   ais'!2-"P10"
   fis'!2
   a'!4
   f'!4
   e'!2.
   c'!2.
   d'!4-"I2"
   fis'!2
   dis'!2
   g'!4
   gis'!2
   c'!2.
   ais'!4
   a'!2.
   f'!2
   cis'!2.
   b'!4
   e'!2-"P4"
   c'!2.
   dis'!2.
   b'!2-"I11"
   dis'!2.
   c'!2
   e'!2
   f'!4-"P5"
   cis'!4
   e'!2
   c'!4
   b'!2
   g'!4
   a'!4
   ais'!4
   d'!2
   fis'!4
   gis'!4
   dis'!4-"R5"
   gis'!2.
   fis'!2.
   d'!2.
   ais'!4
   a'!2
   g'!2.
   b'!4
   c'!2
   e'!2.-"I4"
   gis'!2
   f'!2.
   a'!2.
   ais'!4
   d'!2.
   c'!2-"R2"
   f'!4
   dis'!2.
   b'!2-"R1"
   e'!2
   d'!2.-"R4"
   g'!2.
   f'!4
   cis'!2.
   a'!4
   gis'!2.
   fis'!4
   ais'!4
   b'!4
   dis'!2.-"P3"
   b'!4
   d'!2.
   ais'!2
   a'!2
   f'!2.
   g'!2
   gis'!2-"I8"
   c'!2.
   a'!2.
   cis'!2.
   d'!2.
   fis'!2
   e'!2.
   dis'!2.-"R5"
   gis'!4
   fis'!2
   d'!2
   ais'!2
   a'!2
   g'!2
   b'!2-"R1"
   e'!2
   d'!2
   ais'!2
   fis'!2
   f'!4
   dis'!2.-"P3"
   b'!4
   d'!2
   ais'!2
   a'!2.
   f'!4
   g'!4
   gis'!4
   c'!4
   e'!4-"I4"
   gis'!2
   f'!4
   a'!2
   ais'!2
   d'!2.
   c'!2.
   b'!2.-"RI9"
   fis'!2.
   gis'!2.
   c'!2
   e'!2
   f'!2
   g'!2
   dis'!2
   d'!4
   ais'!2
   cis'!4
   a'!2-"RI7"
   e'!4
   fis'!2
   ais'!4
   d'!2
   dis'!4
   f'!4
   cis'!2-"RI11"
   gis'!2
   ais'!4-"I10"
   d'!2.
   b'!2.
   dis'!2-"P3"
   b'!4
   d'!2
   ais'!2.
   a'!2
   f'!2.-"P5"
   cis'!4
   e'!4
   c'!4
   b'!2.
   g'!2
   a'!2
   ais'!2.-"P10"
   fis'!4
   a'!2.
   f'!4
   e'!2
   c'!2
   d'!2
   dis'!2.
   g'!2
   b'!4-"R1"
   e'!4
   d'!2.
   ais'!4
   fis'!4
   f'!4-"RI3"
   c'!2.
   d'!4
   fis'!4
   ais'!2-"P10"
   fis'!2.
   a'!2
   f'!4
   e'!2.
   c'!4
   d'!2
   dis'!2.-"RI1"
   ais'!4
   c'!4
   e'!2
   gis'!2.
   a'!2.
   b'!2.
   g'!4
   fis'!4-"I6"
   ais'!2
   g'!2.
   b'!2.
   c'!2.
   e'!2.
   d'!2.
   cis'!2
   a'!4
   f'!4
   dis'!4-"R5"
   gis'!2.
   fis'!4
   d'!2.
   ais'!2.
   a'!4
   g'!4
   b'!4-"P11"
   g'!4
   ais'!4
   fis'!4
   f'!4
   cis'!2
   dis'!2.-"P3"
   b'!2.
   d'!2.
   ais'!2
   a'!2.
   f'!2
   g'!4
   gis'!2.
   c'!4
   e'!2
   fis'!2
   cis'!2-"RI11"
   gis'!2.
   ais'!2.
   d'!4
   fis'!4
   g'!2
   a'!2.
   f'!2
   e'!2.
   c'!2.
   dis'!4-"P3"
   b'!2.
   d'!4
   ais'!4
   a'!2.
   f'!4-"RI3"
   c'!4
   d'!2.
   fis'!2
   ais'!4
   b'!2.
   cis'!2.
   a'!2
   gis'!2.
   e'!2.
   g'!2
   dis'!2-"P3"
   b'!2.
   d'!4-"R4"
   g'!4
   f'!4
   cis'!2
   a'!2
   gis'!2
   fis'!2.
   ais'!4
   b'!2
   dis'!2.
   c'!2-"P0"
   gis'!2.
   b'!2.
   g'!2
   fis'!4
   d'!4
   e'!2
   f'!2.
   a'!2.
   cis'!2.
   dis'!2
   ais'!2.
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
