%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 



\score{

 
\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   fis'!4-"R5"
   gis'!4
   g'!2.
   e'!4-"P4"
   c'!2.
   b'!2
   gis'!4
   d'!2
   a'!2.
   ais'!2.-"I10"
   d'!2.
   dis'!2.
   fis'!4
   c'!4
   f'!2.
   e'!4
   cis'!4-"RI2"
   b'!2.
   c'!2
   dis'!4
   f'!2.
   gis'!4
   a'!2.
   e'!4
   ais'!2.
   g'!2.
   fis'!2
   d'!4-"P2"
   ais'!4
   a'!4
   fis'!4
   c'!2
   g'!2
   gis'!2.
   b'!2
   cis'!2.
   e'!2.-"P4"
   c'!4
   b'!2
   gis'!4
   d'!2
   a'!2.
   ais'!2
   cis'!2
   dis'!2.-"I3"
   g'!2
   gis'!4
   b'!2.
   f'!4
   ais'!2-"RI11"
   gis'!2
   a'!2.
   c'!2
   d'!2.
   f'!2.
   fis'!2
   cis'!2.
   g'!2.
   e'!4
   dis'!2-"P3"
   b'!4
   ais'!2
   g'!2.
   cis'!4
   gis'!4
   a'!2
   c'!4-"R11"
   d'!2
   cis'!2.
   ais'!2.
   gis'!4
   f'!2
   e'!2
   a'!2.
   dis'!4
   fis'!4-"R5"
   gis'!2.
   g'!2.
   e'!2
   d'!4
   b'!2.
   ais'!2-"R9"
   c'!4
   b'!2
   gis'!4
   fis'!4-"I6"
   ais'!2.
   b'!4
   d'!2
   gis'!2
   cis'!2
   c'!4
   a'!2-"P9"
   f'!4
   e'!2.
   cis'!4
   g'!4
   d'!2.
   dis'!4-"R2"
   f'!2.
   e'!2.
   cis'!2
   b'!4
   gis'!4
   g'!4
   c'!2.
   fis'!4
   a'!4
   ais'!2-"I10"
   d'!2.
   dis'!2
   fis'!4
   c'!2
   f'!2
   e'!2
   cis'!4
   b'!2.
   gis'!2
   g'!4-"P7"
   dis'!4
   d'!2
   b'!4
   f'!2
   c'!2-"R11"
   d'!2
   cis'!2
   ais'!2
   gis'!2.
   f'!2.-"P5"
   cis'!2
   c'!2.
   a'!4
   dis'!2.
   ais'!2
   b'!2
   d'!2.
   e'!2.
   g'!4-"P7"
   dis'!2
   d'!2
   b'!2.
   f'!2.-"R4"
   g'!2
   fis'!4
   dis'!2
   cis'!4
   ais'!2.
   a'!4
   d'!2-"I2"
   fis'!4
   g'!4-"RI8"
   f'!4
   fis'!4
   a'!2.-"RI10"
   g'!2.
   gis'!2
   b'!2.
   cis'!2
   e'!2.
   f'!4
   c'!2.
   fis'!2-"RI7"
   e'!2.
   f'!2.
   gis'!4
   ais'!4
   cis'!4
   d'!4
   a'!4-"R8"
   b'!4
   ais'!2.
   g'!2.
   f'!4
   d'!4
   cis'!2
   fis'!2.-"P6"
   d'!2.
   cis'!2.
   ais'!4
   e'!2.
   b'!2
   c'!2.
   dis'!4
   f'!2
   gis'!2
   a'!4
   g'!2-"RI8"
   f'!2
   fis'!4
   a'!2.
   b'!2.
   d'!2
   dis'!2.-"RI4"
   cis'!4
   d'!2.-"R1"
   e'!4
   dis'!2
   c'!4
   ais'!2.
   g'!4
   fis'!2
   b'!2.-"I11"
   dis'!2
   e'!2.-"I4"
   gis'!4
   a'!2
   c'!2
   fis'!2
   b'!2.
   ais'!4
   g'!2.-"P7"
   dis'!2
   d'!4
   b'!2
   f'!4
   c'!4-"RI1"
   ais'!2.
   b'!2
   d'!2
   e'!4
   g'!2.-"R6"
   a'!2
   gis'!2.
   f'!2
   dis'!4
   c'!4
   b'!2
   e'!2.
   ais'!2
   cis'!2.-"RI2"
   b'!2
   c'!2
   dis'!2
   f'!4
   gis'!2
   a'!2.
   e'!4
   ais'!4
   g'!2.
   fis'!2.
   d'!4-"R1"
   e'!4
   dis'!2.
   c'!2
   ais'!4
   g'!4
   fis'!2
   b'!4
   f'!2.
   gis'!4-"I8"
   c'!2
   cis'!4
   e'!2.
   ais'!2
   dis'!4
   d'!2.
   b'!2.-"RI0"
   a'!2
   ais'!2.
   cis'!4
   dis'!2.
   fis'!4
   g'!2.
   d'!2
   gis'!2-"RI9"
   fis'!2
   g'!2
   ais'!4
   c'!2.
   dis'!2
   e'!2
   b'!2.-"RI0"
   a'!4
   ais'!4
   cis'!4
   dis'!4
   fis'!2.
   g'!2
   d'!4
   gis'!4
   f'!2.
   e'!2
   c'!2-"R11"
   d'!4
   cis'!4
   ais'!2
   gis'!4
   f'!4
   e'!2.
   a'!4
   dis'!2.-"P3"
   b'!2-"P11"
   g'!2-"R6"
   a'!4
   gis'!2.
   f'!2
   dis'!2
   c'!2
   b'!4
   e'!4-"P4"
   c'!2.
   b'!2
   gis'!2.
   d'!2.
   a'!2
   ais'!2.
   cis'!2
   dis'!2.
   fis'!4
   g'!2
   f'!4-"P5"
   cis'!2.
   c'!4
   a'!2
   dis'!4-"I3"
   g'!2.
   gis'!4
   b'!2.
   f'!2-"I5"
   a'!2.
   ais'!2.
   cis'!2.
   g'!4
   c'!4
   b'!4
   gis'!2.
   fis'!2.
   dis'!4-"I3"
   g'!4
   gis'!4
   b'!4-"R10"
   cis'!2
   c'!4
   a'!2.
   g'!4
   e'!4
   dis'!2.-"I3"
   g'!2.
   gis'!2.
   b'!2
   f'!2
   ais'!2
   a'!2.
   fis'!2.
   e'!2-"I4"
   gis'!4
   a'!2.
   c'!2
   fis'!2
   b'!4
   ais'!2.
   g'!2
   f'!4
   d'!2.-"RI3"
   c'!2
   cis'!4
   e'!2.
   fis'!4
   a'!2.-"RI10"
   g'!2
   gis'!4-"P8"
   e'!2.
   dis'!2.
   c'!2
   fis'!2
   cis'!2-"P1"
   a'!4
   gis'!2
   f'!4
   b'!2
   fis'!2.
   g'!2-"RI8"
   f'!2.
   fis'!2.
   a'!2
   b'!2.-"RI0"
   a'!2.
   ais'!2
   cis'!4
   dis'!4
   fis'!2
   g'!4
   d'!2.
   gis'!2-"RI9"
   fis'!2.
   g'!2
   ais'!2.
   c'!4
   dis'!2.
   e'!4
   b'!4
   f'!2.
   d'!2
   cis'!2.-"RI2"
   b'!4-"P11"
   g'!2.
   fis'!2.
   dis'!2.
   a'!2
   e'!2-"RI5"
   d'!2.-"R1"
   e'!2
   dis'!2
   c'!2
   ais'!4
   g'!2-"P7"
   dis'!2
   d'!4
   b'!2.
   f'!2
   c'!2
   cis'!4
   e'!4
   fis'!2.
   a'!4
   ais'!2.-"RI11"
   gis'!2
   a'!2
   c'!4
   d'!2.
   f'!2
   fis'!4-"I6"
   ais'!4
   b'!2.
   d'!2.
   gis'!4
   cis'!2
   c'!2.
   a'!2.
   g'!2
   e'!2.-"I4"
   gis'!2.
   a'!2-"I9"
   cis'!4
   d'!2.
   f'!2.-"RI6"
   dis'!2.
   e'!4
   g'!4
   a'!2
   c'!4
   cis'!2-"I1"
   f'!2
   fis'!4
   a'!4
   dis'!2.
   gis'!2
   g'!4
   e'!2.
   d'!2
   b'!2.
   ais'!4
   c'!2.-"I0"
   e'!2
   f'!2.
   gis'!2
   d'!2
   g'!2
   fis'!4
   dis'!2
   cis'!4
   ais'!2.
   a'!4
   b'!2
}
}
>>
>>

\midi{}

}


% ****************************************************************
% end ly snippet
% ****************************************************************
