%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    f1\f-"1"
    d16-"2"
    g1-"3"
    dis8-"4"
    a16-"5"
    c2-"6"
    fis1\f-"7"
    dis2-"8"
    cis4-"9"
    e8\p-"10"
    a1-"11"
    gis16-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"1"
    g1-"2"
    ais16-"3"
    f1-"4"
    fis16-"5"
    cis1\mp-"6"
    g2-"7"
    gis4-"8"
    d16-"9"
    dis4-"10"
    f4-"11"
    b4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16-"1"
    cis8-"2"
    ais2\pp-"3"
    d1-"4"
    ais4-"5"
    c16-"6"
    e16-"7"
    e1-"8"
    f2-"9"
    dis8-"10"
    d1-"11"
    gis16-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
