%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-bank.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais8-"1"
    e8-"2"
    dis4-"3"
    g1-"4"
    dis4-"5"
    gis4-"6"
    ais16-"7"
    fis16-"8"
    g2\f-"9"
    c4-"10"
    d2\mf-"11"
    e4-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    dis8-"1"
    cis2\ff-"2"
    a16-"3"
    c4\p-"4"
    cis16-"5"
    d8-"6"
    c16-"7"
    cis8-"8"
    e8\ff-"9"
    dis16-"10"
    gis16-"11"
    g8\mf-"12"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis1-"1"
    a2-"2"
    fis1\ff-"3"
    gis8-"4"
    dis2-"5"
    cis4-"6"
    c16-"7"
    a2-"8"
    fis16-"9"
    e2-"10"
    dis1-"11"
    a4-"12"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
