%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=345\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 345\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 345\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   f'!2.-"P5"
   g'!2
   gis'!2-"I8"
   fis'!2
   f'!2
   b'!4
   d'!2
   g'!4
   dis'!2.
   ais'!2
   cis'!2
   a'!2-"I9"
   g'!2
   fis'!2.
   c'!2-"RI8"
   e'!2
   a'!2
   cis'!2
   ais'!2.
   dis'!4
   g'!2.
   d'!4
   b'!2
   f'!4-"I5"
   dis'!2.
   d'!2.
   gis'!4-"P8"
   ais'!2
   b'!2.
   f'!2
   d'!2.
   a'!2
   cis'!4
   fis'!2.
   dis'!2
   g'!2.
   c'!2-"R4"
   gis'!4-"P8"
   ais'!2
   b'!4
   f'!4
   d'!2-"RI10"
   fis'!4
   b'!2.
   dis'!2.
   c'!2
   f'!2.
   a'!2-"P9"
   b'!4
   c'!4
   fis'!2
   dis'!4
   ais'!2
   d'!4
   g'!2
   e'!2
   gis'!4
   cis'!2.-"P1"
   dis'!4-"I3"
   cis'!4
   c'!4
   fis'!2
   a'!2.
   d'!4
   ais'!2.
   f'!2.
   gis'!2
   e'!2.-"RI0"
   gis'!2.
   cis'!2
   f'!2.
   d'!4
   g'!4
   b'!2.
   fis'!2
   dis'!2.-"I3"
   cis'!4
   c'!2
   fis'!4
   a'!4
   d'!2.
   ais'!4
   f'!2.
   gis'!2.
   e'!4
   b'!2
   g'!2.-"P7"
   a'!2.
   ais'!4
   e'!2.
   cis'!2.
   gis'!2
   c'!2.
   f'!4
   d'!2.
   fis'!4-"RI2"
   ais'!2.
   dis'!2.
   g'!4
   e'!2
   a'!2.-"RI5"
   cis'!2.
   fis'!2
   ais'!2
   g'!2.
   c'!4
   e'!4
   b'!4
   gis'!2.
   d'!4-"R6"
   ais'!2
   f'!2.-"I5"
   dis'!2
   d'!4
   gis'!2
   b'!2
   e'!2.
   c'!2.
   g'!2-"P7"
   a'!4-"RI5"
   cis'!2
   fis'!2
   ais'!4
   g'!4
   c'!4
   e'!2-"R8"
   c'!2
   g'!2
   dis'!2
   fis'!2
   cis'!2.
   a'!2.
   d'!2.
   f'!4
   b'!2-"I11"
   a'!4
   gis'!4
   d'!2
   f'!2.
   ais'!2.-"P10"
   c'!2
   cis'!2
   g'!4
   e'!2
   b'!2.
   dis'!2
   gis'!2
   f'!2.
   a'!2-"I9"
   g'!2.
   fis'!2
   c'!2.
   dis'!2.
   gis'!2.
   e'!4
   b'!2-"P11"
   cis'!4
   d'!2
   gis'!2.
   f'!2
   c'!4
   e'!2
   a'!4
   fis'!4-"P6"
   gis'!2.
   a'!2
   dis'!2.
   c'!2
   g'!4-"P7"
   a'!2.
   ais'!2.
   e'!2.
   cis'!4-"I1"
   b'!2
   ais'!2
   e'!4
   g'!2
   c'!4
   gis'!2.
   dis'!2
   fis'!2.
   d'!4
   a'!4
   f'!4-"I5"
   dis'!2.
   d'!2.
   gis'!2
   b'!4-"P11"
   cis'!4
   d'!4
   gis'!4
   f'!2
   c'!2
   e'!2.
   a'!2.
   fis'!2
   ais'!2.-"R2"
   fis'!2
   cis'!2
   a'!2
   c'!2
   g'!2.
   dis'!4-"P3"
   f'!2
   fis'!2.
   c'!2.
   a'!2
   e'!4
   gis'!2
   cis'!2.-"I1"
   b'!4
   ais'!4
   e'!2.
   g'!2
   c'!2.
   gis'!2.
   dis'!4
   fis'!2.
   d'!4-"I2"
   c'!4
   b'!2.
   f'!4
   gis'!2
   cis'!2.
   a'!2
   e'!2
   g'!2-"RI3"
   b'!2
   e'!4
   gis'!2.
   f'!2
   ais'!4
   d'!2.
   a'!2
   fis'!2.-"RI2"
   ais'!2
   dis'!4
   g'!4-"I7"
   f'!4
   e'!2
   ais'!2
   cis'!2.
   fis'!4
   d'!4
   a'!2.
   c'!2.
   gis'!4
   dis'!2-"I3"
   cis'!4
   c'!2.
   fis'!2.
   a'!4
   d'!2
   ais'!4
   f'!2.
   gis'!2.-"R0"
   e'!4-"P4"
   fis'!2.
   g'!4
   cis'!4
   ais'!2.
   f'!2
   a'!2
   d'!4
   b'!4-"P11"
   cis'!2
   d'!2
   gis'!2
   f'!4
   c'!4
   e'!4
   a'!2
   fis'!2
   ais'!2.
   dis'!2-"P3"
   f'!2
   fis'!2
   c'!2
   a'!2
   e'!2
   gis'!4
   cis'!2.
   ais'!4
   d'!4
   g'!4-"R11"
   dis'!4
   ais'!2.
   fis'!2
   a'!2.
   e'!2.
   c'!2.
   f'!4
   gis'!4
   d'!2-"P2"
   e'!2.
   f'!2
   b'!2
   gis'!2.
   dis'!4
   g'!2
   c'!2.-"RI8"
   e'!2
   a'!2
   cis'!2.
   ais'!2
   dis'!4-"RI11"
   g'!2
   c'!2
   e'!2.
   cis'!2
   fis'!2
   ais'!2
   f'!2.
   d'!2.
   gis'!4-"RI4"
   c'!2-"I0"
   ais'!4
   a'!2.
   dis'!2.
   fis'!2.
   b'!2
   g'!2
   d'!4
   f'!2
   cis'!2
   gis'!2.
   e'!2.
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
