%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=484\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 484\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 484\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   cis'!4-"P1"
   c'!4
   ais'!4
   d'!2.
   gis'!2-"I8"
   a'!4
   b'!4
   g'!2.
   cis'!2
   e'!2
   dis'!4
   c'!4
   f'!4
   d'!2
   ais'!2.
   fis'!2-"I6"
   g'!2
   a'!2.
   f'!4-"R3"
   cis'!4
   a'!2
   fis'!4
   b'!2.
   gis'!4
   g'!2-"RI9"
   b'!4
   dis'!2.
   fis'!2
   cis'!4
   e'!4
   f'!2.
   d'!2.
   gis'!4
   c'!2.-"P0"
   b'!2.-"I11"
   c'!2
   d'!2.
   ais'!2
   e'!2.
   g'!4
   fis'!4
   dis'!2.
   gis'!2.
   f'!4
   cis'!4-"I1"
   d'!4
   e'!4
   c'!2.-"RI2"
   e'!4
   gis'!2
   b'!2.
   fis'!2.
   a'!4
   ais'!2.
   g'!4
   cis'!4-"I1"
   d'!2.
   e'!2
   c'!4
   fis'!4
   a'!4
   gis'!2
   f'!2-"R3"
   cis'!4
   a'!4
   fis'!4
   b'!4
   gis'!2
   g'!2.
   ais'!2.-"P10"
   a'!2.
   g'!4
   b'!4
   f'!2.-"I5"
   fis'!4
   gis'!2
   e'!4
   ais'!4
   cis'!2.
   c'!4
   a'!4
   d'!4
   b'!2.
   g'!4
   dis'!4-"I3"
   e'!4
   fis'!2
   d'!4
   gis'!2
   b'!4
   ais'!2
   g'!2
   c'!4
   a'!2
   f'!2.
   cis'!2-"RI3"
   f'!2
   a'!2.
   c'!2.
   g'!2.-"I7"
   gis'!2.
   ais'!4
   fis'!2
   c'!2.
   dis'!4
   d'!4
   b'!2
   e'!2.
   cis'!2
   a'!2.-"P9"
   gis'!2
   fis'!4-"R4"
   d'!2
   ais'!2
   g'!2.
   c'!4
   a'!2.
   gis'!4
   b'!2
   f'!2
   cis'!2.-"I1"
   d'!2.
   e'!4
   c'!2.-"P0"
   b'!2
   a'!2
   cis'!2.
   g'!2.
   e'!2.
   f'!4
   gis'!2.
   dis'!2.
   fis'!4
   ais'!2
   d'!4
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
