%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    d16-"2"
    g4-"3"
    gis8-"1"
    d16-"5"
    g4-"3"
    dis8-"4"
    g4-"3"
    g4-"3"
    dis8-"4"
    dis8-"4"
    d16-"7"
    d16-"2"
    g4-"3"
    gis8-"1"
    dis8-"4"
    dis8-"4"
    g4-"3"
    dis8-"4"
    g4-"3"
    d16-"5"

\midi{}
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    gis2\mf-"2"
    cis1-"3"
    e1-"1"
    gis2\mf-"5"
    cis1-"3"
    a8\f-"4"
    cis1-"3"
    cis1-"3"
    a8\f-"4"
    a8\f-"4"
    gis2\mf-"7"
    gis2\mf-"2"
    cis1-"3"
    e1-"1"
    a8\f-"4"
    a8\f-"4"
    cis1-"3"
    a8\f-"4"
    cis1-"3"
    gis2\mf-"5"

\midi{}
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais1-"2"
    b2-"3"
    ais2-"1"
    ais1-"5"
    b2-"3"
    d2-"4"
    b2-"3"
    b2-"3"
    d2-"4"
    d2-"4"
    ais1-"7"
    ais1-"2"
    b2-"3"
    ais2-"1"
    d2-"4"
    d2-"4"
    b2-"3"
    d2-"4"
    b2-"3"
    ais1-"5"

\midi{}
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
