%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/flat-random.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef treble
  \time 4/4
  {
   ais2-RI 4
   cis2
   f4
   b2
   d2.-RI 8
   f2
   a2-R 3
   fis4
   d2
   gis2.
   f2.-R 11
   d2.
   ais2
   e2
   cis4
   c4
   g4
   a2
   dis4
   gis2-I 8
   cis2
   b4
   e2.-R 10
   cis4
   a2
   dis2.
   c2
   b4
   fis4-R 0
   dis2.
   b2
   f2.
   d4-RI 8
   f2.
   a4
   dis4
   fis2.
   g2.-RI 1
   ais2
   d2.
   gis4
   b2.
   c4
   f2.
   dis2
   a4-P 9
   e4
   fis2.-RI 0
   a4
   cis2.
   g4
   ais4
   b2
   e2
   d2.
   gis4
   dis2
   f4-P 5
   c2
   d4
   a2
   dis2
   cis4
   fis4
   g2
   ais2.
   e2.
   gis2.
   b2.-I 11
   e4
   d4
   g4
   cis2
   dis2.-R 9
   c2
   gis2
   d2
   b2.
   ais2
   f2.
   g2.
   cis4
   fis2-RI 0
   a2.
   cis2.
   g2
   ais2.
   b4
   e4
   d2
   gis4
   dis4-RI 9
   fis4
   ais2
   e4
   g2
   gis4
   cis2.
   b4
   f4-R 11
   d2
   ais4
   e4
   cis4
   c4
   g2.
   a4
   dis2.-I 3
   gis2
   fis2
   b4-RI 5
   d2
   fis2.-RI 0
   a2
   cis2.
   g2.
   ais2
   b2.
   e4
   d2.
   gis2.
   dis4-R 9
   c2.
   gis2.
   d4
   b2.
   ais4-RI 4
   cis4
   f2
   b4
   d2
   dis2.
   gis2.
   fis2
   c2.
   g4
   a4
   e2-I 4
   a2.
   g2.-R 1
   e2
   c4
   fis2
   dis2
   d4
   a2
   b2.
   f4
   ais2.
   gis2
   cis2.-P 1
   gis2.
   ais2.
   f2.
   b2.
   a2.
   d2.
   dis2-R 9
   c2
   gis2.
   d2
   b2.
   ais2.
   f2.
   g4
   cis4
   fis4-P 6
   cis2.
   dis4
   ais2.
   e2.
   d2
   g2.
   gis2
   b2
   f2-RI 11
   gis2
   c2.-I 0
   f4
   dis2
   gis2
   d2
   e2
   b2.
   ais4
   g2.
   cis2.
   a2
   fis2
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
