%% Generated by lilypond-book
%% Options: [indent=0\mm,line-width=390\pt,quote,staffsize=12]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)

#(set-global-staff-size 12)

\paper {
  indent = 0\mm
  line-width = 390\pt
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
  line-width = 390\pt - 2.0 * 0.4\in
  % offset the left padding, also add 1mm as lilypond creates cropped
  % images with a little space on the right
  line-width = #(- line-width (* mm  3.000000) (* mm 1))
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefilename "../lilypond/markov-chain.ly"
\sourcefileline 0

\version "2.24.4" 


\new ChoirStaff <<



\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16-"5"
    cis4-"6"
    fis16-"5"
    cis2-"1"
    cis1-"7"
    cis2-"1"
    cis4-"4"
    cis4-"6"
    cis2-"1"
    cis1-"7"
    cis4-"4"
    fis16-"5"
    fis16-"5"
    gis2-"2"
    cis1-"7"
    cis2-"1"
    cis2-"1"
    gis2-"2"
    gis2-"2"
    cis2-"3"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    ais16-"5"
    e4-"6"
    ais16-"5"
    cis4\p-"1"
    e8-"7"
    cis4\p-"1"
    e4-"4"
    e4-"6"
    cis4\p-"1"
    e8-"7"
    e4-"4"
    ais16-"5"
    ais16-"5"
    f4-"2"
    e8-"7"
    cis4\p-"1"
    cis4\p-"1"
    f4-"2"
    f4-"2"
    cis4\p-"3"
}
}
>>


\new Staff <<
  \new Voice \with {
  \remove Note_heads_engraver
  \consists Completion_heads_engraver
  \remove Rest_engraver
  \consists Completion_rest_engraver
  }
  {
  \clef alto
  \time 4/4
  {
    fis16-"5"
    f8-"6"
    fis16-"5"
    f4-"1"
    dis1-"7"
    f4-"1"
    f8-"4"
    f8-"6"
    f4-"1"
    dis1-"7"
    f8-"4"
    fis16-"5"
    fis16-"5"
    c8-"2"
    dis1-"7"
    f4-"1"
    f4-"1"
    c8-"2"
    c8-"2"
    f4-"3"
}
}
>>
>>


% ****************************************************************
% end ly snippet
% ****************************************************************
